var age3LoadImage = function()
{
	gbox.addImage("by_3","images/Urban_upgrading/age3/by_3.png?v=1");
	gbox.addTiles({id :'by_3',image :'by_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_3_l","images/Urban_upgrading/age3/by_3_l.png?v=1");
	gbox.addTiles({id :'by_3_l',image :'by_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cjt_3","images/Urban_upgrading/age3/cjt_3.jpg?v=1");
	gbox.addTiles({id :'cjt_3',image :'cjt_3',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_3_l","images/Urban_upgrading/age3/cq_3_l.png?v=1");
	gbox.addTiles({id :'cq_3_l',image :'cq_3_l',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_3","images/Urban_upgrading/age3/dj_3.png?v=1");
	gbox.addTiles({id :'dj_3',image :'dj_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_3_l","images/Urban_upgrading/age3/dj_3_l.png?v=1");
	gbox.addTiles({id :'dj_3_l',image :'dj_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_3","images/Urban_upgrading/age3/gk_3.png?v=1");
	gbox.addTiles({id :'gk_3',image :'gk_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_3_l","images/Urban_upgrading/age3/gk_3_l.png?v=1");
	gbox.addTiles({id :'gk_3_l',image :'gk_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_3","images/Urban_upgrading/age3/jf_3.png?v=1");
	gbox.addTiles({id :'jf_3',image :'jf_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_3_l","images/Urban_upgrading/age3/jf_3_l.png?v=1");
	gbox.addTiles({id :'jf_3_l',image :'jf_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_3","images/Urban_upgrading/age3/jgf_3.png?v=1");
	gbox.addTiles({id :'jgf_3',image :'jgf_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_3_l","images/Urban_upgrading/age3/jgf_3_l.png?v=1");
	gbox.addTiles({id :'jgf_3_l',image :'jgf_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_3","images/Urban_upgrading/age3/jg_3.png?v=1");
	gbox.addTiles({id :'jg_3',image :'jg_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_3_l","images/Urban_upgrading/age3/jg_3_l.png?v=1");
	gbox.addTiles({id :'jg_3_l',image :'jg_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_3","images/Urban_upgrading/age3/jjc_3.png?v=1");
	gbox.addTiles({id :'jjc_3',image :'jjc_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_3_l","images/Urban_upgrading/age3/jjc_3_l.png?v=1");
	gbox.addTiles({id :'jjc_3_l',image :'jjc_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_3","images/Urban_upgrading/age3/js_3.png?v=1");
	gbox.addTiles({id :'js_3',image :'js_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_3_l","images/Urban_upgrading/age3/js_3_l.png?v=1");
	gbox.addTiles({id :'js_3_l',image :'js_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_3","images/Urban_upgrading/age3/jxg_3.png?v=1");
	gbox.addTiles({id :'jxg_3',image :'jxg_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_3_l","images/Urban_upgrading/age3/jxg_3_l.png?v=1");
	gbox.addTiles({id :'jxg_3_l',image :'jxg_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_3","images/Urban_upgrading/age3/kd_3.png?v=1");
	gbox.addTiles({id :'kd_3',image :'kd_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_3_l","images/Urban_upgrading/age3/kd_3_l.png?v=1");
	gbox.addTiles({id :'kd_3_l',image :'kd_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_3","images/Urban_upgrading/age3/kjg_3.png?v=1");
	gbox.addTiles({id :'kjg_3',image :'kjg_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_3_l","images/Urban_upgrading/age3/kjg_3_l.png?v=1");
	gbox.addTiles({id :'kjg_3_l',image :'kjg_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_3","images/Urban_upgrading/age3/lbc_3.png?v=1");
	gbox.addTiles({id :'lbc_3',image :'lbc_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_3_l","images/Urban_upgrading/age3/lbc_3_l.png?v=1");
	gbox.addTiles({id :'lbc_3_l',image :'lbc_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_3","images/Urban_upgrading/age3/mj_3.png?v=1");
	gbox.addTiles({id :'mj_3',image :'mj_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_3_l","images/Urban_upgrading/age3/mj_3_l.png?v=1");
	gbox.addTiles({id :'mj_3_l',image :'mj_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_3","images/Urban_upgrading/age3/twf_3.png?v=1");
	gbox.addTiles({id :'twf_3',image :'twf_3',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_3_l","images/Urban_upgrading/age3/twf_3_l.png?v=1");
	gbox.addTiles({id :'twf_3_l',image :'twf_3_l',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_3","images/Urban_upgrading/age3/tys_3.png?v=1");
	gbox.addTiles({id :'tys_3',image :'tys_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_3_l","images/Urban_upgrading/age3/tys_3_l.png?v=1");
	gbox.addTiles({id :'tys_3_l',image :'tys_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_3","images/Urban_upgrading/age3/wwg_3.png?v=1");
	gbox.addTiles({id :'wwg_3',image :'wwg_3',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_3_l","images/Urban_upgrading/age3/wwg_3_l.png?v=1");
	gbox.addTiles({id :'wwg_3_l',image :'wwg_3_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});

};