var age5LoadImage = function()
{
	gbox.addImage("by_5","images/Urban_upgrading/age5/by_5.png?v=1");
	gbox.addTiles({id :'by_5',image :'by_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_5_l","images/Urban_upgrading/age5/by_5_l.png?v=1");
	gbox.addTiles({id :'by_5_l',image :'by_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cjt_5","images/Urban_upgrading/age5/cjt_5.jpg?v=1");
	gbox.addTiles({id :'cjt_5',image :'cjt_5',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_5_l","images/Urban_upgrading/age5/cq_5_l.png?v=1");
	gbox.addTiles({id :'cq_5_l',image :'cq_5_l',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_5","images/Urban_upgrading/age5/dj_5.png?v=1");
	gbox.addTiles({id :'dj_5',image :'dj_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_5_l","images/Urban_upgrading/age5/dj_5_l.png?v=1");
	gbox.addTiles({id :'dj_5_l',image :'dj_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_5","images/Urban_upgrading/age5/gk_5.png?v=1");
	gbox.addTiles({id :'gk_5',image :'gk_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_5_l","images/Urban_upgrading/age5/gk_5_l.png?v=1");
	gbox.addTiles({id :'gk_5_l',image :'gk_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_5","images/Urban_upgrading/age5/jf_5.png?v=1");
	gbox.addTiles({id :'jf_5',image :'jf_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_5_l","images/Urban_upgrading/age5/jf_5_l.png?v=1");
	gbox.addTiles({id :'jf_5_l',image :'jf_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_5","images/Urban_upgrading/age5/jgf_5.png?v=1");
	gbox.addTiles({id :'jgf_5',image :'jgf_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_5_l","images/Urban_upgrading/age5/jgf_5_l.png?v=1");
	gbox.addTiles({id :'jgf_5_l',image :'jgf_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_5","images/Urban_upgrading/age5/jg_5.png?v=1");
	gbox.addTiles({id :'jg_5',image :'jg_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_5_l","images/Urban_upgrading/age5/jg_5_l.png?v=1");
	gbox.addTiles({id :'jg_5_l',image :'jg_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_5","images/Urban_upgrading/age5/jjc_5.png?v=1");
	gbox.addTiles({id :'jjc_5',image :'jjc_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_5_l","images/Urban_upgrading/age5/jjc_5_l.png?v=1");
	gbox.addTiles({id :'jjc_5_l',image :'jjc_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_5","images/Urban_upgrading/age5/js_5.png?v=1");
	gbox.addTiles({id :'js_5',image :'js_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_5_l","images/Urban_upgrading/age5/js_5_l.png?v=1");
	gbox.addTiles({id :'js_5_l',image :'js_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_5","images/Urban_upgrading/age5/jxg_5.png?v=1");
	gbox.addTiles({id :'jxg_5',image :'jxg_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_5_l","images/Urban_upgrading/age5/jxg_5_l.png?v=1");
	gbox.addTiles({id :'jxg_5_l',image :'jxg_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_5","images/Urban_upgrading/age5/kd_5.png?v=1");
	gbox.addTiles({id :'kd_5',image :'kd_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_5_l","images/Urban_upgrading/age5/kd_5_l.png?v=1");
	gbox.addTiles({id :'kd_5_l',image :'kd_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_5","images/Urban_upgrading/age5/kjg_5.png?v=1");
	gbox.addTiles({id :'kjg_5',image :'kjg_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_5_l","images/Urban_upgrading/age5/kjg_5_l.png?v=1");
	gbox.addTiles({id :'kjg_5_l',image :'kjg_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_5","images/Urban_upgrading/age5/lbc_5.png?v=1");
	gbox.addTiles({id :'lbc_5',image :'lbc_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_5_l","images/Urban_upgrading/age5/lbc_5_l.png?v=1");
	gbox.addTiles({id :'lbc_5_l',image :'lbc_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lcb_5","images/Urban_upgrading/age5/lcb_5.png?v=1");
	gbox.addTiles({id :'lcb_5',image :'lcb_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_5","images/Urban_upgrading/age5/mj_5.png?v=1");
	gbox.addTiles({id :'mj_5',image :'mj_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_5_l","images/Urban_upgrading/age5/mj_5_l.png?v=1");
	gbox.addTiles({id :'mj_5_l',image :'mj_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_5","images/Urban_upgrading/age5/twf_5.png?v=1");
	gbox.addTiles({id :'twf_5',image :'twf_5',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_5_l","images/Urban_upgrading/age5/twf_5_l.png?v=1");
	gbox.addTiles({id :'twf_5_l',image :'twf_5_l',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_5","images/Urban_upgrading/age5/tys_5.png?v=1");
	gbox.addTiles({id :'tys_5',image :'tys_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_5_l","images/Urban_upgrading/age5/tys_5_l.png?v=1");
	gbox.addTiles({id :'tys_5_l',image :'tys_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_5","images/Urban_upgrading/age5/wwg_5.png?v=1");
	gbox.addTiles({id :'wwg_5',image :'wwg_5',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_5_l","images/Urban_upgrading/age5/wwg_5_l.png?v=1");
	gbox.addTiles({id :'wwg_5_l',image :'wwg_5_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});

};