/*
 * 战斗_通用
 */
var Battle_UniversalLoadImage = function()
{
	gbox.addImage("zc_tb_14","images/Battle_Universal/zc_tb_14.png?v=1");
	gbox.addTiles({id :'zc_tb_14',image :'zc_tb_14',tilew:213,tileh:136,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_15","images/Battle_Universal/zc_tb_15.png?v=1");
	gbox.addTiles({id :'zc_tb_15',image :'zc_tb_15',tilew:149,tileh:298,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_16","images/Battle_Universal/zc_tb_16.png?v=1");
	gbox.addTiles({id :'zc_tb_16',image :'zc_tb_16',tilew:126,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_17","images/Battle_Universal/zc_tb_17.png?v=1");
	gbox.addTiles({id :'zc_tb_17',image :'zc_tb_17',tilew:126,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_20","images/Battle_Universal/zc_tb_20.png?v=1");
	gbox.addTiles({id :'zc_tb_20',image :'zc_tb_20',tilew:69,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	
	gbox.addImage("zc_tb_19","images/Battle_Universal/zc_tb_19.png?v=1");
	gbox.addTiles({id :'zc_tb_19',image :'zc_tb_19',tilew:69,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("num_1","images/Battle_Universal/num_1.png?v=1");
	gbox.addTiles({id :'num_1',image :'num_1',tilew:500,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("num_2","images/Battle_Universal/num_2.png?v=1");
	gbox.addTiles({id :'num_2',image :'num_2',tilew:500,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_01","images/Battle_Universal/zc_tb_01.png?v=1");
	gbox.addTiles({id :'zc_tb_01',image :'zc_tb_01',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_02","images/Battle_Universal/zc_tb_02.png?v=1");
	gbox.addTiles({id :'zc_tb_02',image :'zc_tb_02',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_03","images/Battle_Universal/zc_tb_03.png?v=1");
	gbox.addTiles({id :'zc_tb_03',image :'zc_tb_03',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_04","images/Battle_Universal/zc_tb_04.png?v=1");
	gbox.addTiles({id :'zc_tb_04',image :'zc_tb_04',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_05","images/Battle_Universal/zc_tb_05.png?v=1");
	gbox.addTiles({id :'zc_tb_05',image :'zc_tb_05',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_06","images/Battle_Universal/zc_tb_06.png?v=1");
	gbox.addTiles({id :'zc_tb_06',image :'zc_tb_06',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_07","images/Battle_Universal/zc_tb_07.png?v=1");
	gbox.addTiles({id :'zc_tb_07',image :'zc_tb_07',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_09","images/Battle_Universal/zc_tb_09.png?v=1");
	gbox.addTiles({id :'zc_tb_09',image :'zc_tb_09',tilew:237,tileh:122,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_10","images/Battle_Universal/zc_tb_10.png?v=1");
	gbox.addTiles({id :'zc_tb_10',image :'zc_tb_10',tilew:97,tileh:38,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_100","images/Battle_Universal/zc_tb_100.png?v=1");
	gbox.addTiles({id :'zc_tb_100',image :'zc_tb_100',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_101","images/Battle_Universal/zc_tb_101.png?v=1");
	gbox.addTiles({id :'zc_tb_101',image :'zc_tb_101',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_102","images/Battle_Universal/zc_tb_102.png?v=1");
	gbox.addTiles({id :'zc_tb_102',image :'zc_tb_102',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_103","images/Battle_Universal/zc_tb_103.png?v=1");
	gbox.addTiles({id :'zc_tb_103',image :'zc_tb_103',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_104","images/Battle_Universal/zc_tb_104.png?v=1");
	gbox.addTiles({id :'zc_tb_104',image :'zc_tb_104',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_105","images/Battle_Universal/zc_tb_105.png?v=1");
	gbox.addTiles({id :'zc_tb_105',image :'zc_tb_105',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_106","images/Battle_Universal/zc_tb_106.png?v=1");
	gbox.addTiles({id :'zc_tb_106',image :'zc_tb_106',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_107","images/Battle_Universal/zc_tb_107.png?v=1");
	gbox.addTiles({id :'zc_tb_107',image :'zc_tb_107',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_108","images/Battle_Universal/zc_tb_108.png?v=1");
	gbox.addTiles({id :'zc_tb_108',image :'zc_tb_108',tilew:34,tileh:56,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_112","images/Battle_Universal/zc_tb_112.png?v=1");
	gbox.addTiles({id :'zc_tb_112',image :'zc_tb_112',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_113","images/Battle_Universal/zc_tb_113.png?v=1");
	gbox.addTiles({id :'zc_tb_113',image :'zc_tb_113',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_114","images/Battle_Universal/zc_tb_114.png?v=1");
	gbox.addTiles({id :'zc_tb_114',image :'zc_tb_114',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_115","images/Battle_Universal/zc_tb_115.png?v=1");
	gbox.addTiles({id :'zc_tb_115',image :'zc_tb_115',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_18","images/Battle_Universal/zc_tb_18.png?v=1");
	gbox.addTiles({id :'zc_tb_18',image :'zc_tb_18',tilew:71,tileh:14,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_31","images/Battle_Universal/zc_tb_31.png?v=1");
	gbox.addTiles({id :'zc_tb_31',image :'zc_tb_31',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_32","images/Battle_Universal/zc_tb_32.png?v=1");
	gbox.addTiles({id :'zc_tb_32',image :'zc_tb_32',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_33","images/Battle_Universal/zc_tb_33.png?v=1");
	gbox.addTiles({id :'zc_tb_33',image :'zc_tb_33',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_34","images/Battle_Universal/zc_tb_34.png?v=1");
	gbox.addTiles({id :'zc_tb_34',image :'zc_tb_34',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_35","images/Battle_Universal/zc_tb_35.png?v=1");
	gbox.addTiles({id :'zc_tb_35',image :'zc_tb_35',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_36","images/Battle_Universal/zc_tb_36.png?v=1");
	gbox.addTiles({id :'zc_tb_36',image :'zc_tb_36',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_37","images/Battle_Universal/zc_tb_37.png?v=1");
	gbox.addTiles({id :'zc_tb_37',image :'zc_tb_37',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_38","images/Battle_Universal/zc_tb_38.png?v=1");
	gbox.addTiles({id :'zc_tb_38',image :'zc_tb_38',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_39","images/Battle_Universal/zc_tb_39.png?v=1");
	gbox.addTiles({id :'zc_tb_39',image :'zc_tb_39',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_40","images/Battle_Universal/zc_tb_40.png?v=1");
	gbox.addTiles({id :'zc_tb_40',image :'zc_tb_40',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_41","images/Battle_Universal/zc_tb_41.png?v=1");
	gbox.addTiles({id :'zc_tb_41',image :'zc_tb_41',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_42","images/Battle_Universal/zc_tb_42.png?v=1");
	gbox.addTiles({id :'zc_tb_42',image :'zc_tb_42',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_43","images/Battle_Universal/zc_tb_43.png?v=1");
	gbox.addTiles({id :'zc_tb_43',image :'zc_tb_43',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_44","images/Battle_Universal/zc_tb_44.png?v=1");
	gbox.addTiles({id :'zc_tb_44',image :'zc_tb_44',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_45","images/Battle_Universal/zc_tb_45.png?v=1");
	gbox.addTiles({id :'zc_tb_45',image :'zc_tb_45',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_46","images/Battle_Universal/zc_tb_46.png?v=1");
	gbox.addTiles({id :'zc_tb_46',image :'zc_tb_46',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_47","images/Battle_Universal/zc_tb_47.png?v=1");
	gbox.addTiles({id :'zc_tb_47',image :'zc_tb_47',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_48","images/Battle_Universal/zc_tb_48.png?v=1");
	gbox.addTiles({id :'zc_tb_48',image :'zc_tb_48',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_49","images/Battle_Universal/zc_tb_49.png?v=1");
	gbox.addTiles({id :'zc_tb_49',image :'zc_tb_49',tilew:90,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_50","images/Battle_Universal/zc_tb_50.png?v=1");
	gbox.addTiles({id :'zc_tb_50',image :'zc_tb_50',tilew:45,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_51","images/Battle_Universal/zc_tb_51.png?v=1");
	gbox.addTiles({id :'zc_tb_51',image :'zc_tb_51',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_52","images/Battle_Universal/zc_tb_52.png?v=1");
	gbox.addTiles({id :'zc_tb_52',image :'zc_tb_52',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_53","images/Battle_Universal/zc_tb_53.png?v=1");
	gbox.addTiles({id :'zc_tb_53',image :'zc_tb_53',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_54","images/Battle_Universal/zc_tb_54.png?v=1");
	gbox.addTiles({id :'zc_tb_54',image :'zc_tb_54',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_55","images/Battle_Universal/zc_tb_55.png?v=1");
	gbox.addTiles({id :'zc_tb_55',image :'zc_tb_55',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_56","images/Battle_Universal/zc_tb_56.png?v=1");
	gbox.addTiles({id :'zc_tb_56',image :'zc_tb_56',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_57","images/Battle_Universal/zc_tb_57.png?v=1");
	gbox.addTiles({id :'zc_tb_57',image :'zc_tb_57',tilew:465,tileh:56,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_58","images/Battle_Universal/zc_tb_58.png?v=1");
	gbox.addTiles({id :'zc_tb_58',image :'zc_tb_58',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_59","images/Battle_Universal/zc_tb_59.png?v=1");
	gbox.addTiles({id :'zc_tb_59',image :'zc_tb_59',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_60","images/Battle_Universal/zc_tb_60.png?v=1");
	gbox.addTiles({id :'zc_tb_60',image :'zc_tb_60',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_61","images/Battle_Universal/zc_tb_61.png?v=1");
	gbox.addTiles({id :'zc_tb_61',image :'zc_tb_61',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_62","images/Battle_Universal/zc_tb_62.png?v=1");
	gbox.addTiles({id :'zc_tb_62',image :'zc_tb_62',tilew:35,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_83","images/Battle_Universal/zc_tb_83.png?v=1");
	gbox.addTiles({id :'zc_tb_83',image :'zc_tb_83',tilew:120,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_84","images/Battle_Universal/zc_tb_84.png?v=1");
	gbox.addTiles({id :'zc_tb_84',image :'zc_tb_84',tilew:120,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_85","images/Battle_Universal/zc_tb_85.png?v=1");
	gbox.addTiles({id :'zc_tb_85',image :'zc_tb_85',tilew:120,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_86","images/Battle_Universal/zc_tb_86.png?v=1");
	gbox.addTiles({id :'zc_tb_86',image :'zc_tb_86',tilew:120,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_87","images/Battle_Universal/zc_tb_87.png?v=1");
	gbox.addTiles({id :'zc_tb_87',image :'zc_tb_87',tilew:170,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_88","images/Battle_Universal/zc_tb_88.png?v=1");
	gbox.addTiles({id :'zc_tb_88',image :'zc_tb_88',tilew:286,tileh:281,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_89","images/Battle_Universal/zc_tb_89.png?v=1");
	gbox.addTiles({id :'zc_tb_89',image :'zc_tb_89',tilew:639,tileh:425,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_90","images/Battle_Universal/zc_tb_90.png?v=1");
	gbox.addTiles({id :'zc_tb_90',image :'zc_tb_90',tilew:550,tileh:683,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_91","images/Battle_Universal/zc_tb_91.png?v=1");
	gbox.addTiles({id :'zc_tb_91',image :'zc_tb_91',tilew:102,tileh:66,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_92","images/Battle_Universal/zc_tb_92.png?v=1");
	gbox.addTiles({id :'zc_tb_92',image :'zc_tb_92',tilew:550,tileh:683,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_93","images/Battle_Universal/zc_tb_93.png?v=1");
	gbox.addTiles({id :'zc_tb_93',image :'zc_tb_93',tilew:102,tileh:66,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_94","images/Battle_Universal/zc_tb_94.png?v=1");
	gbox.addTiles({id :'zc_tb_94',image :'zc_tb_94',tilew:80,tileh:17,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_95","images/Battle_Universal/zc_tb_95.png?v=1");
	gbox.addTiles({id :'zc_tb_95',image :'zc_tb_95',tilew:80,tileh:17,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_99","images/Battle_Universal/zc_tb_99.png?v=1");
	gbox.addTiles({id :'zc_tb_99',image :'zc_tb_99',tilew:50,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
};