/*
 * 战斗_讨伐
 */
var Battle_CrusadeLoadImage = function()
{
	gbox.addImage("zc_tb_08","images/Battle_Crusade/zc_tb_08.png?v=1");
	gbox.addTiles({id :'zc_tb_08',image :'zc_tb_08',tilew:416,tileh:79,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_109","images/Battle_Crusade/zc_tb_109.png?v=1");
	gbox.addTiles({id :'zc_tb_109',image :'zc_tb_109',tilew:122,tileh:114,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_110","images/Battle_Crusade/zc_tb_110.png?v=1");
	gbox.addTiles({id :'zc_tb_110',image :'zc_tb_110',tilew:122,tileh:114,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_111","images/Battle_Crusade/zc_tb_111.png?v=1");
	gbox.addTiles({id :'zc_tb_111',image :'zc_tb_111',tilew:32,tileh:33,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_116","images/Battle_Crusade/zc_tb_116.png?v=1");
	gbox.addTiles({id :'zc_tb_116',image :'zc_tb_116',tilew:178,tileh:138,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_12","images/Battle_Crusade/zc_tb_12.png?v=1");
	gbox.addTiles({id :'zc_tb_12',image :'zc_tb_12',tilew:435,tileh:34,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_13","images/Battle_Crusade/zc_tb_13.png?v=1");
	gbox.addTiles({id :'zc_tb_13',image :'zc_tb_13',tilew:435,tileh:34,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_14","images/Battle_Crusade/zc_tb_14.png?v=1");
	gbox.addTiles({id :'zc_tb_14',image :'zc_tb_14',tilew:213,tileh:136,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_15","images/Battle_Crusade/zc_tb_15.png?v=1");
	gbox.addTiles({id :'zc_tb_15',image :'zc_tb_15',tilew:143,tileh:298,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_16","images/Battle_Crusade/zc_tb_16.png?v=1");
	gbox.addTiles({id :'zc_tb_16',image :'zc_tb_16',tilew:126,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_17","images/Battle_Crusade/zc_tb_17.png?v=1");
	gbox.addTiles({id :'zc_tb_17',image :'zc_tb_17',tilew:126,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_19","images/Battle_Crusade/zc_tb_19.png?v=1");
	gbox.addTiles({id :'zc_tb_19',image :'zc_tb_19',tilew:69,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_20","images/Battle_Crusade/zc_tb_20.png?v=1");
	gbox.addTiles({id :'zc_tb_20',image :'zc_tb_20',tilew:69,tileh:5,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_23","images/Battle_Crusade/zc_tb_23.png?v=1");
	gbox.addTiles({id :'zc_tb_23',image :'zc_tb_23',tilew:34,tileh:56,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_25","images/Battle_Crusade/zc_tb_25.png?v=1");
	gbox.addTiles({id :'zc_tb_25',image :'zc_tb_25',tilew:208,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_26","images/Battle_Crusade/zc_tb_26.png?v=1");
	gbox.addTiles({id :'zc_tb_26',image :'zc_tb_26',tilew:208,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_27","images/Battle_Crusade/zc_tb_27.png?v=1");
	gbox.addTiles({id :'zc_tb_27',image :'zc_tb_27',tilew:208,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_28","images/Battle_Crusade/zc_tb_28.png?v=1");
	gbox.addTiles({id :'zc_tb_28',image :'zc_tb_28',tilew:137,tileh:86,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_96","images/Battle_Crusade/zc_tb_96.png?v=1");
	gbox.addTiles({id :'zc_tb_96',image :'zc_tb_96',tilew:635,tileh:377,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_97","images/Battle_Crusade/zc_tb_97.jpg?v=1");
	gbox.addTiles({id :'zc_tb_97',image :'zc_tb_97',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zc_tb_98","images/Battle_Crusade/zc_tb_98.jpg?v=1");
	gbox.addTiles({id :'zc_tb_98',image :'zc_tb_98',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
    gbox.addImage("zc_tb_118","images/Battle_Crusade/zc_tb_118.png?v=1");
	gbox.addTiles({id :'zc_tb_118',image :'zc_tb_118',tilew:47,tileh:58,tilerow : 1,gapx : 0,gapy : 0});
	
	gbox.addImage("daobingshangfangbeiji","images/Battle_Crusade/anim/bingzhong/daobingshangfangbeiji.png?v=1");
	gbox.addTiles({id :'daobingshangfangbeiji',image :'daobingshangfangbeiji',tilew:1464,tileh:722,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("daobingshangfanggongji","images/Battle_Crusade/anim/bingzhong/daobingshangfanggongji.png?v=1");
	gbox.addTiles({id :'daobingshangfanggongji',image :'daobingshangfanggongji',tilew:1024,tileh:297,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("daobingxiafangbeiji","images/Battle_Crusade/anim/bingzhong/daobingxiafangbeiji.png?v=1");
	gbox.addTiles({id :'daobingxiafangbeiji',image :'daobingxiafangbeiji',tilew:1473,tileh:692,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("daobingxiafanggongji","images/Battle_Crusade/anim/bingzhong/daobingxiafanggongji.png?v=1");
	gbox.addTiles({id :'daobingxiafanggongji',image :'daobingxiafanggongji',tilew:1024,tileh:297,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gongbingshangfangbeiji","images/Battle_Crusade/anim/bingzhong/gongbingshangfangbeiji.png?v=1");
	gbox.addTiles({id :'gongbingshangfangbeiji',image :'gongbingshangfangbeiji',tilew:1650,tileh:307,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gongbingshangfanggongji","images/Battle_Crusade/anim/bingzhong/gongbingshangfanggongji.png?v=1");
	gbox.addTiles({id :'gongbingshangfanggongji',image :'gongbingshangfanggongji',tilew:1024,tileh:500,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gongbingxiafangbeiji","images/Battle_Crusade/anim/bingzhong/gongbingxiafangbeiji.png?v=1");
	gbox.addTiles({id :'gongbingxiafangbeiji',image :'gongbingxiafangbeiji',tilew:1650,tileh:307,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gongbingxiafanggongji","images/Battle_Crusade/anim/bingzhong/gongbingxiafanggongji.png?v=1");
	gbox.addTiles({id :'gongbingxiafanggongji',image :'gongbingxiafanggongji',tilew:1024,tileh:500,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("manzufangduigongji","images/Battle_Crusade/anim/bingzhong/manzufangduigongji.png?v=1");
	gbox.addTiles({id :'manzufangduigongji',image :'manzufangduigongji',tilew:788,tileh:402,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("manzufangduishoushang","images/Battle_Crusade/anim/bingzhong/manzufangduishoushang.png?v=1");
	gbox.addTiles({id :'manzufangduishoushang',image :'manzufangduishoushang',tilew:957,tileh:321,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("manzufangduixingzou","images/Battle_Crusade/anim/bingzhong/manzufangduixingzou.png?v=1");
	gbox.addTiles({id :'manzufangduixingzou',image :'manzufangduixingzou',tilew:764,tileh:301,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mazeifangduigongji","images/Battle_Crusade/anim/bingzhong/mazeifangduigongji.png?v=1");
	gbox.addTiles({id :'mazeifangduigongji',image :'mazeifangduigongji',tilew:714,tileh:260,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mazeifangduishoushang","images/Battle_Crusade/anim/bingzhong/mazeifangduishoushang.png?v=1");
	gbox.addTiles({id :'mazeifangduishoushang',image :'mazeifangduishoushang',tilew:790,tileh:276,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mazeifangduixingzou","images/Battle_Crusade/anim/bingzhong/mazeifangduixingzou.png?v=1");
	gbox.addTiles({id :'mazeifangduixingzou',image :'mazeifangduixingzou',tilew:694,tileh:159,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qiangbingshangfangbeiji","images/Battle_Crusade/anim/bingzhong/qiangbingshangfangbeiji.png?v=1");
	gbox.addTiles({id :'qiangbingshangfangbeiji',image :'qiangbingshangfangbeiji',tilew:1623,tileh:247,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qiangbingshangfanggongji","images/Battle_Crusade/anim/bingzhong/qiangbingshangfanggongji.png?v=1");
	gbox.addTiles({id :'qiangbingshangfanggongji',image :'qiangbingshangfanggongji',tilew:1024,tileh:402,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qiangbingxiafangbeiji","images/Battle_Crusade/anim/bingzhong/qiangbingxiafangbeiji.png?v=1");
	gbox.addTiles({id :'qiangbingxiafangbeiji',image :'qiangbingxiafangbeiji',tilew:1623,tileh:247,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qiangbingxiafanggongji","images/Battle_Crusade/anim/bingzhong/qiangbingxiafanggongji.png?v=1");
	gbox.addTiles({id :'qiangbingxiafanggongji',image :'qiangbingxiafanggongji',tilew:1024,tileh:402,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qibingshangfangbeiji","images/Battle_Crusade/anim/bingzhong/qibingshangfangbeiji.png?v=1");
	gbox.addTiles({id :'qibingshangfangbeiji',image :'qibingshangfangbeiji',tilew:1654,tileh:269,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qibingshangfanggongji","images/Battle_Crusade/anim/bingzhong/qibingshangfanggongji.png?v=1");
	gbox.addTiles({id :'qibingshangfanggongji',image :'qibingshangfanggongji',tilew:1500,tileh:332,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qibingxiafangbeiji","images/Battle_Crusade/anim/bingzhong/qibingxiafangbeiji.png?v=1");
	gbox.addTiles({id :'qibingxiafangbeiji',image :'qibingxiafangbeiji',tilew:1623,tileh:247,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qibingxiafanggongji","images/Battle_Crusade/anim/bingzhong/qibingxiafanggongji.png?v=1");
	gbox.addTiles({id :'qibingxiafanggongji',image :'qibingxiafanggongji',tilew:1500,tileh:394,tilerow : 1,gapx : 0,gapy : 0});
	//车兵
	gbox.addImage("chebingshangfanggongji",  "images/Battle_Crusade/anim/bingzhong/chebingshangfanggongji.png?v=1");
	gbox.addTiles({id :'chebingshangfanggongji',image : 'chebingshangfanggongji',tilew : 899,tileh : 170,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("chebingxiafanggongji",  "images/Battle_Crusade/anim/bingzhong/chebingxiafanggongji.png?v=1");
	gbox.addTiles({id :'chebingxiafanggongji',image : 'chebingxiafanggongji',tilew : 923,tileh : 219,tilerow : 1,gapx : 0,gapy : 0});

	




	gbox.addImage("biaoqiangyu","images/Battle_Crusade/anim/jineng/biaoqiangyu.png?v=1");
	gbox.addTiles({id :'biaoqiangyu',image :'biaoqiangyu',tilew:1000,tileh:821,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buquzhanhun","images/Battle_Crusade/anim/jineng/buquzhanhun.png?v=1");
	gbox.addTiles({id :'buquzhanhun',image :'buquzhanhun',tilew:987,tileh:425,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("chuxing","images/Battle_Crusade/anim/jineng/chuxing.png?v=1");
	gbox.addTiles({id :'chuxing',image :'chuxing',tilew:987,tileh:599,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("duci","images/Battle_Crusade/anim/jineng/duci.png?v=1");
	gbox.addTiles({id :'duci',image :'duci',tilew:1657,tileh:868,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dushi","images/Battle_Crusade/anim/jineng/dushi.png?v=1");
	gbox.addTiles({id :'dushi',image :'dushi',tilew:2007,tileh:412,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("fenghoujian","images/Battle_Crusade/anim/jineng/fenghoujian.png?v=1");
	gbox.addTiles({id :'fenghoujian',image :'fenghoujian',tilew:999,tileh:370,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gelie","images/Battle_Crusade/anim/jineng/gelie.png?v=1");
	gbox.addTiles({id :'gelie',image :'gelie',tilew:987,tileh:599,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gongbingputonggongji","images/Battle_Crusade/anim/jineng/gongbingputonggongji.png?v=1");
	gbox.addTiles({id :'gongbingputonggongji',image :'gongbingputonggongji',tilew:600,tileh:347,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("guhuo","images/Battle_Crusade/anim/jineng/guhuo.png?v=1");
	gbox.addTiles({id :'guhuo',image :'guhuo',tilew:1000,tileh:446,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gushou","images/Battle_Crusade/anim/jineng/gushou.png?v=1");
	gbox.addTiles({id :'gushou',image :'gushou',tilew:893,tileh:391,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("guwu","images/Battle_Crusade/anim/jineng/guwu.png?v=1");
	gbox.addTiles({id :'guwu',image :'guwu',tilew:1000,tileh:345,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("huichunshou","images/Battle_Crusade/anim/jineng/huichunshou.png?v=1");
	gbox.addTiles({id :'huichunshou',image :'huichunshou',tilew:1000,tileh:761,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jianzhen","images/Battle_Crusade/anim/jineng/jianzhen.png?v=1");
	gbox.addTiles({id :'jianzhen',image :'jianzhen',tilew:2472,tileh:334,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jianzhiling","images/Battle_Crusade/anim/jineng/jianzhiling.png?v=1");
	gbox.addTiles({id :'jianzhiling',image :'jianzhiling',tilew:1030,tileh:388,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jinghunzhizhun","images/Battle_Crusade/anim/jineng/jinghunzhizhun.png?v=1");
	gbox.addTiles({id :'jinghunzhizhun',image :'jinghunzhizhun',tilew:1988,tileh:269,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jinglingshouhu","images/Battle_Crusade/anim/jineng/jinglingshouhu.png?v=1");
	gbox.addTiles({id :'jinglingshouhu',image :'jinglingshouhu',tilew:1988,tileh:269,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jiusifushang","images/Battle_Crusade/anim/jineng/jiusifushang.png?v=1");
	gbox.addTiles({id :'jiusifushang',image :'jiusifushang',tilew:943,tileh:474,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("juexingzhanhun","images/Battle_Crusade/anim/jineng/juexingzhanhun.png?v=1");
	gbox.addTiles({id :'juexingzhanhun',image :'juexingzhanhun',tilew:2319,tileh:268,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("konghe","images/Battle_Crusade/anim/jineng/konghe.png?v=1");
	gbox.addTiles({id :'konghe',image :'konghe',tilew:863,tileh:459,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kongxian","images/Battle_Crusade/anim/jineng/kongxian.png?v=1");
	gbox.addTiles({id :'kongxian',image :'kongxian',tilew:1000,tileh:201,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kuanghua","images/Battle_Crusade/anim/jineng/kuanghua.png?v=1");
	gbox.addTiles({id :'kuanghua',image :'kuanghua',tilew:2646,tileh:364,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lengyuedaji","images/Battle_Crusade/anim/jineng/lengyuedaji.png?v=1");
	gbox.addTiles({id :'lengyuedaji',image :'lengyuedaji',tilew:1673,tileh:204,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("liefengzhan","images/Battle_Crusade/anim/jineng/liefengzhan.png?v=1");
	gbox.addTiles({id :'liefengzhan',image :'liefengzhan',tilew:799,tileh:408,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lieyanshi","images/Battle_Crusade/anim/jineng/lieyanshi.png?v=1");
	gbox.addTiles({id :'lieyanshi',image :'lieyanshi',tilew:2550,tileh:412,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mengduzhiya","images/Battle_Crusade/anim/jineng/mengduzhiya.png?v=1");
	gbox.addTiles({id :'mengduzhiya',image :'mengduzhiya',tilew:891,tileh:450,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mengxi","images/Battle_Crusade/anim/jineng/mengxi.png?v=1");
	gbox.addTiles({id :'mengxi',image :'mengxi',tilew:1322,tileh:268,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shaluzhanhun","images/Battle_Crusade/anim/jineng/shaluzhanhun.png?v=1");
	gbox.addTiles({id :'shaluzhanhun',image :'shaluzhanhun',tilew:1850,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shifangjineng","images/Battle_Crusade/anim/jineng/shifangjineng.png?v=1");
	gbox.addTiles({id :'shifangjineng',image :'shifangjineng',tilew:1000,tileh:489,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tiaoxin","images/Battle_Crusade/anim/jineng/tiaoxin.png?v=1");
	gbox.addTiles({id :'tiaoxin',image :'tiaoxin',tilew:1000,tileh:446,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tuji","images/Battle_Crusade/anim/jineng/tuji.png?v=1");
	gbox.addTiles({id :'tuji',image :'tuji',tilew:1322,tileh:268,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wanwuguijin","images/Battle_Crusade/anim/jineng/wanwuguijin.png?v=1");
	gbox.addTiles({id :'wanwuguijin',image :'wanwuguijin',tilew:1786,tileh:228,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wenyizhiyun","images/Battle_Crusade/anim/jineng/wenyizhiyun.png?v=1");
	gbox.addTiles({id :'wenyizhiyun',image :'wenyizhiyun',tilew:1000,tileh:944,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xianjing_dilie","images/Battle_Crusade/anim/jineng/xianjing_dilie.png?v=1");
	gbox.addTiles({id :'xianjing_dilie',image :'xianjing_dilie',tilew:1675,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xianjing_honglian","images/Battle_Crusade/anim/jineng/xianjing_honglian.png?v=1");
	gbox.addTiles({id :'xianjing_honglian',image :'xianjing_honglian',tilew:1740,tileh:285,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xianjing_lingshe","images/Battle_Crusade/anim/jineng/xianjing_lingshe.png?v=1");
	gbox.addTiles({id :'xianjing_lingshe',image :'xianjing_lingshe',tilew:1345,tileh:202,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xinlinganfu","images/Battle_Crusade/anim/jineng/xinlinganfu.png?v=1");
	gbox.addTiles({id :'xinlinganfu',image :'xinlinganfu',tilew:1030,tileh:388,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("yanyangdaji","images/Battle_Crusade/anim/jineng/yanyangdaji.png?v=1");
	gbox.addTiles({id :'yanyangdaji',image :'yanyangdaji',tilew:1286,tileh:878,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("yibing","images/Battle_Crusade/anim/jineng/yibing.png?v=1");
	gbox.addTiles({id :'yibing',image :'yibing',tilew:1943,tileh:252,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("yuntifengshen","images/Battle_Crusade/anim/jineng/yuntifengshen.png?v=1");
	gbox.addTiles({id :'yuntifengshen',image :'yuntifengshen',tilew:1139,tileh:502,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zhandijijiu","images/Battle_Crusade/anim/jineng/zhandijijiu.png?v=1");
	gbox.addTiles({id :'zhandijijiu',image :'zhandijijiu',tilew:1630,tileh:234,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zhanyibilei","images/Battle_Crusade/anim/jineng/zhanyibilei.png?v=1");
	gbox.addTiles({id :'zhanyibilei',image :'zhanyibilei',tilew:1192,tileh:489,tilerow : 1,gapx : 0,gapy : 0});
};