/*
 * 兵营
 */
var foreignMuseumLoadImage = function()
{
	gbox.addImage("wwg_zjm_01","images/Foreign_Museum/wwg_zjm_01.png?v=1");
	gbox.addTiles({id :'wwg_zjm_01',image :'wwg_zjm_01',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_02","images/Foreign_Museum/wwg_zjm_02.png?v=1");
	gbox.addTiles({id :'wwg_zjm_02',image :'wwg_zjm_02',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_03","images/Foreign_Museum/wwg_zjm_03.png?v=1");
	gbox.addTiles({id :'wwg_zjm_03',image :'wwg_zjm_03',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_04","images/Foreign_Museum/wwg_zjm_04.png?v=1");
	gbox.addTiles({id :'wwg_zjm_04',image :'wwg_zjm_04',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_05","images/Foreign_Museum/wwg_zjm_05.png?v=1");
	gbox.addTiles({id :'wwg_zjm_05',image :'wwg_zjm_05',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_06","images/Foreign_Museum/wwg_zjm_06.png?v=1");
	gbox.addTiles({id :'wwg_zjm_06',image :'wwg_zjm_06',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_07","images/Foreign_Museum/wwg_zjm_07.png?v=1");
	gbox.addTiles({id :'wwg_zjm_07',image :'wwg_zjm_07',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_08","images/Foreign_Museum/wwg_zjm_08.png?v=1");
	gbox.addTiles({id :'wwg_zjm_08',image :'wwg_zjm_08',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_09","images/Foreign_Museum/wwg_zjm_09.png?v=1");
	gbox.addTiles({id :'wwg_zjm_09',image :'wwg_zjm_09',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_10","images/Foreign_Museum/wwg_zjm_10.png?v=1");
	gbox.addTiles({id :'wwg_zjm_10',image :'wwg_zjm_10',tilew:565,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_11","images/Foreign_Museum/wwg_zjm_11.png?v=1");
	gbox.addTiles({id :'wwg_zjm_11',image :'wwg_zjm_11',tilew:33,tileh:113,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_12","images/Foreign_Museum/wwg_zjm_12.png?v=1");
	gbox.addTiles({id :'wwg_zjm_12',image :'wwg_zjm_12',tilew:33,tileh:113,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_13","images/Foreign_Museum/wwg_zjm_13.png?v=1");
	gbox.addTiles({id :'wwg_zjm_13',image :'wwg_zjm_13',tilew:330,tileh:278,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_15","images/Foreign_Museum/wwg_zjm_15.png?v=1");
	gbox.addTiles({id :'wwg_zjm_15',image :'wwg_zjm_15',tilew:358,tileh:287,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_16","images/Foreign_Museum/wwg_zjm_16.png?v=1");
	gbox.addTiles({id :'wwg_zjm_16',image :'wwg_zjm_16',tilew:411,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_17","images/Foreign_Museum/wwg_zjm_17.png?v=1");
	gbox.addTiles({id :'wwg_zjm_17',image :'wwg_zjm_17',tilew:432,tileh:283,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_18","images/Foreign_Museum/wwg_zjm_18.png?v=1");
	gbox.addTiles({id :'wwg_zjm_18',image :'wwg_zjm_18',tilew:432,tileh:219,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_19","images/Foreign_Museum/wwg_zjm_19.png?v=1");
	gbox.addTiles({id :'wwg_zjm_19',image :'wwg_zjm_19',tilew:432,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_20","images/Foreign_Museum/wwg_zjm_20.png?v=1");
	gbox.addTiles({id :'wwg_zjm_20',image :'wwg_zjm_20',tilew:432,tileh:219,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_21","images/Foreign_Museum/wwg_zjm_21.png?v=1");
	gbox.addTiles({id :'wwg_zjm_21',image :'wwg_zjm_21',tilew:432,tileh:219,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_22","images/Foreign_Museum/wwg_zjm_22.png?v=1");
	gbox.addTiles({id :'wwg_zjm_22',image :'wwg_zjm_22',tilew:432,tileh:302,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_23","images/Foreign_Museum/wwg_zjm_23.png?v=1");
	gbox.addTiles({id :'wwg_zjm_23',image :'wwg_zjm_23',tilew:274,tileh:119,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_24","images/Foreign_Museum/wwg_zjm_24.png?v=1");
	gbox.addTiles({id :'wwg_zjm_24',image :'wwg_zjm_24',tilew:274,tileh:145,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_25","images/Foreign_Museum/wwg_zjm_25.png?v=1");
	gbox.addTiles({id :'wwg_zjm_25',image :'wwg_zjm_25',tilew:432,tileh:283,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_26","images/Foreign_Museum/wwg_zjm_26.png?v=1");
	gbox.addTiles({id :'wwg_zjm_26',image :'wwg_zjm_26',tilew:432,tileh:283,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_27","images/Foreign_Museum/wwg_zjm_27.png?v=1");
	gbox.addTiles({id :'wwg_zjm_27',image :'wwg_zjm_27',tilew:432,tileh:322,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_28","images/Foreign_Museum/wwg_zjm_28.png?v=1");
	gbox.addTiles({id :'wwg_zjm_28',image :'wwg_zjm_28',tilew:432,tileh:125,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_29","images/Foreign_Museum/wwg_zjm_29.png?v=1");
	gbox.addTiles({id :'wwg_zjm_29',image :'wwg_zjm_29',tilew:82,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_30","images/Foreign_Museum/wwg_zjm_30.png?v=1");
	gbox.addTiles({id :'wwg_zjm_30',image :'wwg_zjm_30',tilew:82,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_31","images/Foreign_Museum/wwg_zjm_31.png?v=1");
	gbox.addTiles({id :'wwg_zjm_31',image :'wwg_zjm_31',tilew:324,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_34","images/Foreign_Museum/wwg_zjm_34.png?v=1");
	gbox.addTiles({id :'wwg_zjm_34',image :'wwg_zjm_34',tilew:151,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_35","images/Foreign_Museum/wwg_zjm_35.png?v=1");
	gbox.addTiles({id :'wwg_zjm_35',image :'wwg_zjm_35',tilew:407,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_36","images/Foreign_Museum/wwg_zjm_36.png?v=1");
	gbox.addTiles({id :'wwg_zjm_36',image :'wwg_zjm_36',tilew:2,tileh:176,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_37","images/Foreign_Museum/wwg_zjm_37.png?v=1");
	gbox.addTiles({id :'wwg_zjm_37',image :'wwg_zjm_37',tilew:358,tileh:287,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_38","images/Foreign_Museum/wwg_zjm_38.png?v=1");
	gbox.addTiles({id :'wwg_zjm_38',image :'wwg_zjm_38',tilew:407,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_39","images/Foreign_Museum/wwg_zjm_39.png?v=1");
	gbox.addTiles({id :'wwg_zjm_39',image :'wwg_zjm_39',tilew:407,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_40","images/Foreign_Museum/wwg_zjm_40.png?v=1");
	gbox.addTiles({id :'wwg_zjm_40',image :'wwg_zjm_40',tilew:330,tileh:278,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_41","images/Foreign_Museum/wwg_zjm_41.png?v=1");
	gbox.addTiles({id :'wwg_zjm_41',image :'wwg_zjm_41',tilew:432,tileh:283,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_42","images/Foreign_Museum/wwg_zjm_42.png?v=1");
	gbox.addTiles({id :'wwg_zjm_42',image :'wwg_zjm_42',tilew:578,tileh:340,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_43","images/Foreign_Museum/wwg_zjm_43.png?v=1");
	gbox.addTiles({id :'wwg_zjm_43',image :'wwg_zjm_43',tilew:319,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_44","images/Foreign_Museum/wwg_zjm_44.png?v=1");
	gbox.addTiles({id :'wwg_zjm_44',image :'wwg_zjm_44',tilew:319,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_45","images/Foreign_Museum/wwg_zjm_45.png?v=1");
	gbox.addTiles({id :'wwg_zjm_45',image :'wwg_zjm_45',tilew:274,tileh:145,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_46","images/Foreign_Museum/wwg_zjm_46.png?v=1");
	gbox.addTiles({id :'wwg_zjm_46',image :'wwg_zjm_46',tilew:32,tileh:33,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_zjm_47","images/Foreign_Museum/wwg_zjm_47.png?v=1");
	gbox.addTiles({id :'wwg_zjm_47',image :'wwg_zjm_47',tilew:82,tileh:21,tilerow : 1,gapx : 0,gapy : 0});

};