var Formation_IconLoadImage = function()
{
	gbox.addImage("x_zx_dy","images/Formation_Icon/x_zx_dy.png?v=1");
	gbox.addTiles({id :'x_zx_dy',image :'x_zx_dy',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_fs","images/Formation_Icon/x_zx_fs.png?v=1");
	gbox.addTiles({id :'x_zx_fs',image :'x_zx_fs',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_gx","images/Formation_Icon/x_zx_gx.png?v=1");
	gbox.addTiles({id :'x_zx_gx',image :'x_zx_gx',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_hg","images/Formation_Icon/x_zx_hg.png?v=1");
	gbox.addTiles({id :'x_zx_hg',image :'x_zx_hg',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_hy","images/Formation_Icon/x_zx_hy.png?v=1");
	gbox.addTiles({id :'x_zx_hy',image :'x_zx_hy',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_jx","images/Formation_Icon/x_zx_jx.png?v=1");
	gbox.addTiles({id :'x_zx_jx',image :'x_zx_jx',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_wy","images/Formation_Icon/x_zx_wy.png?v=1");
	gbox.addTiles({id :'x_zx_wy',image :'x_zx_wy',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_xx","images/Formation_Icon/x_zx_xx.png?v=1");
	gbox.addTiles({id :'x_zx_xx',image :'x_zx_xx',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_yl","images/Formation_Icon/x_zx_yl.png?v=1");
	gbox.addTiles({id :'x_zx_yl',image :'x_zx_yl',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_yy","images/Formation_Icon/x_zx_yy.png?v=1");
	gbox.addTiles({id :'x_zx_yy',image :'x_zx_yy',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_yz","images/Formation_Icon/x_zx_yz.png?v=1");
	gbox.addTiles({id :'x_zx_yz',image :'x_zx_yz',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("x_zx_zx","images/Formation_Icon/x_zx_zx.png?v=1");
	gbox.addTiles({id :'x_zx_zx',image :'x_zx_zx',tilew:55,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_dy","images/Formation_Icon/zx_dy.png?v=1");
	gbox.addTiles({id :'zx_dy',image :'zx_dy',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_fs","images/Formation_Icon/zx_fs.png?v=1");
	gbox.addTiles({id :'zx_fs',image :'zx_fs',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_gx","images/Formation_Icon/zx_gx.png?v=1");
	gbox.addTiles({id :'zx_gx',image :'zx_gx',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_hg","images/Formation_Icon/zx_hg.png?v=1");
	gbox.addTiles({id :'zx_hg',image :'zx_hg',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_hy","images/Formation_Icon/zx_hy.png?v=1");
	gbox.addTiles({id :'zx_hy',image :'zx_hy',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_jx","images/Formation_Icon/zx_jx.png?v=1");
	gbox.addTiles({id :'zx_jx',image :'zx_jx',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_wy","images/Formation_Icon/zx_wy.png?v=1");
	gbox.addTiles({id :'zx_wy',image :'zx_wy',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_xx","images/Formation_Icon/zx_xx.png?v=1");
	gbox.addTiles({id :'zx_xx',image :'zx_xx',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_yl","images/Formation_Icon/zx_yl.png?v=1");
	gbox.addTiles({id :'zx_yl',image :'zx_yl',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_yy","images/Formation_Icon/zx_yy.png?v=1");
	gbox.addTiles({id :'zx_yy',image :'zx_yy',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_yz","images/Formation_Icon/zx_yz.png?v=1");
	gbox.addTiles({id :'zx_yz',image :'zx_yz',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zx_zx","images/Formation_Icon/zx_zx.png?v=1");
	gbox.addTiles({id :'zx_zx',image :'zx_zx',tilew:76,tileh:76,tilerow : 1,gapx : 0,gapy : 0});

};