var gemLoadImage = function()
{
	gbox.addImage("CL_BCXS_1","images/Gem/CL_BCXS_1.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_1',image :'CL_BCXS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_2","images/Gem/CL_BCXS_2.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_2',image :'CL_BCXS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_3","images/Gem/CL_BCXS_3.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_3',image :'CL_BCXS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_4","images/Gem/CL_BCXS_4.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_4',image :'CL_BCXS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_5","images/Gem/CL_BCXS_5.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_5',image :'CL_BCXS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_6","images/Gem/CL_BCXS_6.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_6',image :'CL_BCXS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BCXS_7","images/Gem/CL_BCXS_7.jpg?v=1");
	gbox.addTiles({id :'CL_BCXS_7',image :'CL_BCXS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_1","images/Gem/CL_BHXS_1.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_1',image :'CL_BHXS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_2","images/Gem/CL_BHXS_2.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_2',image :'CL_BHXS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_3","images/Gem/CL_BHXS_3.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_3',image :'CL_BHXS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_4","images/Gem/CL_BHXS_4.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_4',image :'CL_BHXS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_5","images/Gem/CL_BHXS_5.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_5',image :'CL_BHXS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_6","images/Gem/CL_BHXS_6.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_6',image :'CL_BHXS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BHXS_7","images/Gem/CL_BHXS_7.jpg?v=1");
	gbox.addTiles({id :'CL_BHXS_7',image :'CL_BHXS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_1","images/Gem/CL_BQYS_1.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_1',image :'CL_BQYS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_2","images/Gem/CL_BQYS_2.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_2',image :'CL_BQYS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_3","images/Gem/CL_BQYS_3.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_3',image :'CL_BQYS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_4","images/Gem/CL_BQYS_4.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_4',image :'CL_BQYS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_5","images/Gem/CL_BQYS_5.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_5',image :'CL_BQYS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_6","images/Gem/CL_BQYS_6.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_6',image :'CL_BQYS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BQYS_7","images/Gem/CL_BQYS_7.jpg?v=1");
	gbox.addTiles({id :'CL_BQYS_7',image :'CL_BQYS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_1","images/Gem/CL_GGYS_1.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_1',image :'CL_GGYS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_2","images/Gem/CL_GGYS_2.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_2',image :'CL_GGYS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_3","images/Gem/CL_GGYS_3.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_3',image :'CL_GGYS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_4","images/Gem/CL_GGYS_4.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_4',image :'CL_GGYS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_5","images/Gem/CL_GGYS_5.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_5',image :'CL_GGYS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_6","images/Gem/CL_GGYS_6.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_6',image :'CL_GGYS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_GGYS_7","images/Gem/CL_GGYS_7.jpg?v=1");
	gbox.addTiles({id :'CL_GGYS_7',image :'CL_GGYS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_1","images/Gem/CL_HHJS_1.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_1',image :'CL_HHJS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_2","images/Gem/CL_HHJS_2.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_2',image :'CL_HHJS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_3","images/Gem/CL_HHJS_3.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_3',image :'CL_HHJS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_4","images/Gem/CL_HHJS_4.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_4',image :'CL_HHJS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_5","images/Gem/CL_HHJS_5.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_5',image :'CL_HHJS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_6","images/Gem/CL_HHJS_6.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_6',image :'CL_HHJS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_HHJS_7","images/Gem/CL_HHJS_7.jpg?v=1");
	gbox.addTiles({id :'CL_HHJS_7',image :'CL_HHJS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_1","images/Gem/CL_LJYS_1.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_1',image :'CL_LJYS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_2","images/Gem/CL_LJYS_2.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_2',image :'CL_LJYS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_3","images/Gem/CL_LJYS_3.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_3',image :'CL_LJYS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_4","images/Gem/CL_LJYS_4.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_4',image :'CL_LJYS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_5","images/Gem/CL_LJYS_5.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_5',image :'CL_LJYS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_6","images/Gem/CL_LJYS_6.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_6',image :'CL_LJYS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LJYS_7","images/Gem/CL_LJYS_7.jpg?v=1");
	gbox.addTiles({id :'CL_LJYS_7',image :'CL_LJYS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_1","images/Gem/CL_LSJS_1.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_1',image :'CL_LSJS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_2","images/Gem/CL_LSJS_2.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_2',image :'CL_LSJS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_3","images/Gem/CL_LSJS_3.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_3',image :'CL_LSJS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_4","images/Gem/CL_LSJS_4.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_4',image :'CL_LSJS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_5","images/Gem/CL_LSJS_5.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_5',image :'CL_LSJS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_6","images/Gem/CL_LSJS_6.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_6',image :'CL_LSJS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_LSJS_7","images/Gem/CL_LSJS_7.jpg?v=1");
	gbox.addTiles({id :'CL_LSJS_7',image :'CL_LSJS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_1","images/Gem/CL_MZJS_1.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_1',image :'CL_MZJS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_2","images/Gem/CL_MZJS_2.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_2',image :'CL_MZJS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_3","images/Gem/CL_MZJS_3.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_3',image :'CL_MZJS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_4","images/Gem/CL_MZJS_4.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_4',image :'CL_MZJS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_5","images/Gem/CL_MZJS_5.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_5',image :'CL_MZJS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_6","images/Gem/CL_MZJS_6.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_6',image :'CL_MZJS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MZJS_7","images/Gem/CL_MZJS_7.jpg?v=1");
	gbox.addTiles({id :'CL_MZJS_7',image :'CL_MZJS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_1","images/Gem/CL_QHYS_1.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_1',image :'CL_QHYS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_2","images/Gem/CL_QHYS_2.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_2',image :'CL_QHYS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_3","images/Gem/CL_QHYS_3.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_3',image :'CL_QHYS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_4","images/Gem/CL_QHYS_4.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_4',image :'CL_QHYS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_5","images/Gem/CL_QHYS_5.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_5',image :'CL_QHYS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_6","images/Gem/CL_QHYS_6.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_6',image :'CL_QHYS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_QHYS_7","images/Gem/CL_QHYS_7.jpg?v=1");
	gbox.addTiles({id :'CL_QHYS_7',image :'CL_QHYS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_1","images/Gem/CL_TLXS_1.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_1',image :'CL_TLXS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_2","images/Gem/CL_TLXS_2.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_2',image :'CL_TLXS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_3","images/Gem/CL_TLXS_3.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_3',image :'CL_TLXS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_4","images/Gem/CL_TLXS_4.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_4',image :'CL_TLXS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_5","images/Gem/CL_TLXS_5.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_5',image :'CL_TLXS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_6","images/Gem/CL_TLXS_6.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_6',image :'CL_TLXS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_TLXS_7","images/Gem/CL_TLXS_7.jpg?v=1");
	gbox.addTiles({id :'CL_TLXS_7',image :'CL_TLXS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_1","images/Gem/CL_WFXS_1.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_1',image :'CL_WFXS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_2","images/Gem/CL_WFXS_2.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_2',image :'CL_WFXS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_3","images/Gem/CL_WFXS_3.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_3',image :'CL_WFXS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_4","images/Gem/CL_WFXS_4.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_4',image :'CL_WFXS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_5","images/Gem/CL_WFXS_5.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_5',image :'CL_WFXS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_6","images/Gem/CL_WFXS_6.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_6',image :'CL_WFXS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_WFXS_7","images/Gem/CL_WFXS_7.jpg?v=1");
	gbox.addTiles({id :'CL_WFXS_7',image :'CL_WFXS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_1","images/Gem/CL_XSJS_1.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_1',image :'CL_XSJS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_2","images/Gem/CL_XSJS_2.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_2',image :'CL_XSJS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_3","images/Gem/CL_XSJS_3.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_3',image :'CL_XSJS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_4","images/Gem/CL_XSJS_4.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_4',image :'CL_XSJS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_5","images/Gem/CL_XSJS_5.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_5',image :'CL_XSJS_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_6","images/Gem/CL_XSJS_6.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_6',image :'CL_XSJS_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_XSJS_7","images/Gem/CL_XSJS_7.jpg?v=1");
	gbox.addTiles({id :'CL_XSJS_7',image :'CL_XSJS_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
};