var mmarketLoadImage = function()
{
	gbox.addImage("js_npc_1","images/Market/js_npc_1.png?v=1");
	gbox.addTiles({id :'js_npc_1',image :'js_npc_1',tilew:760,tileh:754,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_npc_2","images/Market/js_npc_2.png?v=1");
	gbox.addTiles({id :'js_npc_2',image :'js_npc_2',tilew:2000,tileh:204,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_zjm_01","images/Market/js_zjm_01.jpg?v=1");
	gbox.addTiles({id :'js_zjm_01',image :'js_zjm_01',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jy_zjm_01","images/Market/jy_zjm_01.png?v=1");
	gbox.addTiles({id :'jy_zjm_01',image :'jy_zjm_01',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jy_zjm_08","images/Market/jy_zjm_08.png?v=1");
	gbox.addTiles({id :'jy_zjm_08',image :'jy_zjm_08',tilew:324,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_01","images/Market/pmh_zjm_01.png?v=1");
	gbox.addTiles({id :'pmh_zjm_01',image :'pmh_zjm_01',tilew:805,tileh:497,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_02","images/Market/pmh_zjm_02.png?v=1");
	gbox.addTiles({id :'pmh_zjm_02',image :'pmh_zjm_02',tilew:805,tileh:497,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_03","images/Market/pmh_zjm_03.png?v=1");
	gbox.addTiles({id :'pmh_zjm_03',image :'pmh_zjm_03',tilew:805,tileh:497,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_04","images/Market/pmh_zjm_04.png?v=1");
	gbox.addTiles({id :'pmh_zjm_04',image :'pmh_zjm_04',tilew:324,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_05","images/Market/pmh_zjm_05.png?v=1");
	gbox.addTiles({id :'pmh_zjm_05',image :'pmh_zjm_05',tilew:70,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_06","images/Market/pmh_zjm_06.png?v=1");
	gbox.addTiles({id :'pmh_zjm_06',image :'pmh_zjm_06',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_07","images/Market/pmh_zjm_07.png?v=1");
	gbox.addTiles({id :'pmh_zjm_07',image :'pmh_zjm_07',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_08","images/Market/pmh_zjm_08.png?v=1");
	gbox.addTiles({id :'pmh_zjm_08',image :'pmh_zjm_08',tilew:70,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_09","images/Market/pmh_zjm_09.png?v=1");
	gbox.addTiles({id :'pmh_zjm_09',image :'pmh_zjm_09',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_10","images/Market/pmh_zjm_10.png?v=1");
	gbox.addTiles({id :'pmh_zjm_10',image :'pmh_zjm_10',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_11","images/Market/pmh_zjm_11.png?v=1");
	gbox.addTiles({id :'pmh_zjm_11',image :'pmh_zjm_11',tilew:70,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_12","images/Market/pmh_zjm_12.png?v=1");
	gbox.addTiles({id :'pmh_zjm_12',image :'pmh_zjm_12',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_13","images/Market/pmh_zjm_13.png?v=1");
	gbox.addTiles({id :'pmh_zjm_13',image :'pmh_zjm_13',tilew:57,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_15","images/Market/pmh_zjm_15.png?v=1");
	gbox.addTiles({id :'pmh_zjm_15',image :'pmh_zjm_15',tilew:33,tileh:74,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_16","images/Market/pmh_zjm_16.png?v=1");
	gbox.addTiles({id :'pmh_zjm_16',image :'pmh_zjm_16',tilew:33,tileh:74,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_17","images/Market/pmh_zjm_17.png?v=1");
	gbox.addTiles({id :'pmh_zjm_17',image :'pmh_zjm_17',tilew:33,tileh:74,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_18","images/Market/pmh_zjm_18.png?v=1");
	gbox.addTiles({id :'pmh_zjm_18',image :'pmh_zjm_18',tilew:33,tileh:74,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_19","images/Market/pmh_zjm_19.png?v=1");
	gbox.addTiles({id :'pmh_zjm_19',image :'pmh_zjm_19',tilew:33,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_20","images/Market/pmh_zjm_20.png?v=1");
	gbox.addTiles({id :'pmh_zjm_20',image :'pmh_zjm_20',tilew:33,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_21","images/Market/pmh_zjm_21.png?v=1");
	gbox.addTiles({id :'pmh_zjm_21',image :'pmh_zjm_21',tilew:33,tileh:70,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_29","images/Market/pmh_zjm_29.png?v=1");
	gbox.addTiles({id :'pmh_zjm_29',image :'pmh_zjm_29',tilew:99,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_30","images/Market/pmh_zjm_30.png?v=1");
	gbox.addTiles({id :'pmh_zjm_30',image :'pmh_zjm_30',tilew:99,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_31","images/Market/pmh_zjm_31.png?v=1");
	gbox.addTiles({id :'pmh_zjm_31',image :'pmh_zjm_31',tilew:99,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_39","images/Market/pmh_zjm_39.png?v=1");
	gbox.addTiles({id :'pmh_zjm_39',image :'pmh_zjm_39',tilew:278,tileh:236,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_45","images/Market/pmh_zjm_45.png?v=1");
	gbox.addTiles({id :'pmh_zjm_45',image :'pmh_zjm_45',tilew:60,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_47","images/Market/pmh_zjm_47.png?v=1");
	gbox.addTiles({id :'pmh_zjm_47',image :'pmh_zjm_47',tilew:92,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_49","images/Market/pmh_zjm_49.png?v=1");
	gbox.addTiles({id :'pmh_zjm_49',image :'pmh_zjm_49',tilew:172,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_51","images/Market/pmh_zjm_51.png?v=1");
	gbox.addTiles({id :'pmh_zjm_51',image :'pmh_zjm_51',tilew:40,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_52","images/Market/pmh_zjm_52.png?v=1");
	gbox.addTiles({id :'pmh_zjm_52',image :'pmh_zjm_52',tilew:16,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pmh_zjm_53","images/Market/pmh_zjm_53.png?v=1");
	gbox.addTiles({id :'pmh_zjm_53',image :'pmh_zjm_53',tilew:15,tileh:8,tilerow : 1,gapx : 0,gapy : 0});
	
};