var materiaIconLoadImage = function()
{
	gbox.addImage("CL_BT_1","images/Materia_icon/CL_BT_1.jpg?v=1");
	gbox.addTiles({id :'CL_BT_1',image :'CL_BT_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_10","images/Materia_icon/CL_BT_10.jpg?v=1");
	gbox.addTiles({id :'CL_BT_10',image :'CL_BT_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_2","images/Materia_icon/CL_BT_2.jpg?v=1");
	gbox.addTiles({id :'CL_BT_2',image :'CL_BT_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_3","images/Materia_icon/CL_BT_3.jpg?v=1");
	gbox.addTiles({id :'CL_BT_3',image :'CL_BT_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_4","images/Materia_icon/CL_BT_4.jpg?v=1");
	gbox.addTiles({id :'CL_BT_4',image :'CL_BT_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_5","images/Materia_icon/CL_BT_5.jpg?v=1");
	gbox.addTiles({id :'CL_BT_5',image :'CL_BT_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_6","images/Materia_icon/CL_BT_6.jpg?v=1");
	gbox.addTiles({id :'CL_BT_6',image :'CL_BT_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_7","images/Materia_icon/CL_BT_7.jpg?v=1");
	gbox.addTiles({id :'CL_BT_7',image :'CL_BT_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_8","images/Materia_icon/CL_BT_8.jpg?v=1");
	gbox.addTiles({id :'CL_BT_8',image :'CL_BT_8',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_BT_9","images/Materia_icon/CL_BT_9.jpg?v=1");
	gbox.addTiles({id :'CL_BT_9',image :'CL_BT_9',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_1","images/Materia_icon/CL_JT_1.jpg?v=1");
	gbox.addTiles({id :'CL_JT_1',image :'CL_JT_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_10","images/Materia_icon/CL_JT_10.jpg?v=1");
	gbox.addTiles({id :'CL_JT_10',image :'CL_JT_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_2","images/Materia_icon/CL_JT_2.jpg?v=1");
	gbox.addTiles({id :'CL_JT_2',image :'CL_JT_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_3","images/Materia_icon/CL_JT_3.jpg?v=1");
	gbox.addTiles({id :'CL_JT_3',image :'CL_JT_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_4","images/Materia_icon/CL_JT_4.jpg?v=1");
	gbox.addTiles({id :'CL_JT_4',image :'CL_JT_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_5","images/Materia_icon/CL_JT_5.jpg?v=1");
	gbox.addTiles({id :'CL_JT_5',image :'CL_JT_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_6","images/Materia_icon/CL_JT_6.jpg?v=1");
	gbox.addTiles({id :'CL_JT_6',image :'CL_JT_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_7","images/Materia_icon/CL_JT_7.jpg?v=1");
	gbox.addTiles({id :'CL_JT_7',image :'CL_JT_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_8","images/Materia_icon/CL_JT_8.jpg?v=1");
	gbox.addTiles({id :'CL_JT_8',image :'CL_JT_8',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_JT_9","images/Materia_icon/CL_JT_9.jpg?v=1");
	gbox.addTiles({id :'CL_JT_9',image :'CL_JT_9',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_1","images/Materia_icon/CL_MB_1.jpg?v=1");
	gbox.addTiles({id :'CL_MB_1',image :'CL_MB_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_10","images/Materia_icon/CL_MB_10.jpg?v=1");
	gbox.addTiles({id :'CL_MB_10',image :'CL_MB_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_2","images/Materia_icon/CL_MB_2.jpg?v=1");
	gbox.addTiles({id :'CL_MB_2',image :'CL_MB_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_3","images/Materia_icon/CL_MB_3.jpg?v=1");
	gbox.addTiles({id :'CL_MB_3',image :'CL_MB_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_4","images/Materia_icon/CL_MB_4.jpg?v=1");
	gbox.addTiles({id :'CL_MB_4',image :'CL_MB_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_5","images/Materia_icon/CL_MB_5.jpg?v=1");
	gbox.addTiles({id :'CL_MB_5',image :'CL_MB_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_6","images/Materia_icon/CL_MB_6.jpg?v=1");
	gbox.addTiles({id :'CL_MB_6',image :'CL_MB_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_7","images/Materia_icon/CL_MB_7.jpg?v=1");
	gbox.addTiles({id :'CL_MB_7',image :'CL_MB_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_8","images/Materia_icon/CL_MB_8.jpg?v=1");
	gbox.addTiles({id :'CL_MB_8',image :'CL_MB_8',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MB_9","images/Materia_icon/CL_MB_9.jpg?v=1");
	gbox.addTiles({id :'CL_MB_9',image :'CL_MB_9',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_1","images/Materia_icon/CL_MX_1.jpg?v=1");
	gbox.addTiles({id :'CL_MX_1',image :'CL_MX_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_10","images/Materia_icon/CL_MX_10.jpg?v=1");
	gbox.addTiles({id :'CL_MX_10',image :'CL_MX_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_2","images/Materia_icon/CL_MX_2.jpg?v=1");
	gbox.addTiles({id :'CL_MX_2',image :'CL_MX_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_3","images/Materia_icon/CL_MX_3.jpg?v=1");
	gbox.addTiles({id :'CL_MX_3',image :'CL_MX_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_4","images/Materia_icon/CL_MX_4.jpg?v=1");
	gbox.addTiles({id :'CL_MX_4',image :'CL_MX_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_5","images/Materia_icon/CL_MX_5.jpg?v=1");
	gbox.addTiles({id :'CL_MX_5',image :'CL_MX_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_6","images/Materia_icon/CL_MX_6.jpg?v=1");
	gbox.addTiles({id :'CL_MX_6',image :'CL_MX_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_7","images/Materia_icon/CL_MX_7.jpg?v=1");
	gbox.addTiles({id :'CL_MX_7',image :'CL_MX_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_8","images/Materia_icon/CL_MX_8.jpg?v=1");
	gbox.addTiles({id :'CL_MX_8',image :'CL_MX_8',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_MX_9","images/Materia_icon/CL_MX_9.jpg?v=1");
	gbox.addTiles({id :'CL_MX_9',image :'CL_MX_9',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_1","images/Materia_icon/CL_PG_1.jpg?v=1");
	gbox.addTiles({id :'CL_PG_1',image :'CL_PG_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_10","images/Materia_icon/CL_PG_10.jpg?v=1");
	gbox.addTiles({id :'CL_PG_10',image :'CL_PG_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_2","images/Materia_icon/CL_PG_2.jpg?v=1");
	gbox.addTiles({id :'CL_PG_2',image :'CL_PG_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_3","images/Materia_icon/CL_PG_3.jpg?v=1");
	gbox.addTiles({id :'CL_PG_3',image :'CL_PG_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_4","images/Materia_icon/CL_PG_4.jpg?v=1");
	gbox.addTiles({id :'CL_PG_4',image :'CL_PG_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_5","images/Materia_icon/CL_PG_5.jpg?v=1");
	gbox.addTiles({id :'CL_PG_5',image :'CL_PG_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_6","images/Materia_icon/CL_PG_6.jpg?v=1");
	gbox.addTiles({id :'CL_PG_6',image :'CL_PG_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_7","images/Materia_icon/CL_PG_7.jpg?v=1");
	gbox.addTiles({id :'CL_PG_7',image :'CL_PG_7',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_8","images/Materia_icon/CL_PG_8.jpg?v=1");
	gbox.addTiles({id :'CL_PG_8',image :'CL_PG_8',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("CL_PG_9","images/Materia_icon/CL_PG_9.jpg?v=1");
	gbox.addTiles({id :'CL_PG_9',image :'CL_PG_9',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
};