var skilIconLoadImage = function()
{ 
	gbox.addImage("buff_bqzh","images/Skil_icons/buff_bqzh.jpg?v=1");
	gbox.addTiles({id :'buff_bqzh',image :'buff_bqzh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_dc","images/Skil_icons/buff_dc.jpg?v=1");
	gbox.addTiles({id :'buff_dc',image :'buff_dc',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_ds","images/Skil_icons/buff_ds.jpg?v=1");
	gbox.addTiles({id :'buff_ds',image :'buff_ds',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_fhj","images/Skil_icons/buff_fhj.jpg?v=1");
	gbox.addTiles({id :'buff_fhj',image :'buff_fhj',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_gh","images/Skil_icons/buff_gh.jpg?v=1");
	gbox.addTiles({id :'buff_gh',image :'buff_gh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_gksh","images/Skil_icons/buff_gksh.jpg?v=1");
	gbox.addTiles({id :'buff_gksh',image :'buff_gksh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_gl","images/Skil_icons/buff_gl.jpg?v=1");
	gbox.addTiles({id :'buff_gl',image :'buff_gl',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_gs","images/Skil_icons/buff_gs.jpg?v=1");
	gbox.addTiles({id :'buff_gs',image :'buff_gs',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_gw","images/Skil_icons/buff_gw.jpg?v=1");
	gbox.addTiles({id :'buff_gw',image :'buff_gw',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_jlsh","images/Skil_icons/buff_jlsh.jpg?v=1");
	gbox.addTiles({id :'buff_jlsh',image :'buff_jlsh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_jxzh","images/Skil_icons/buff_jxzh.jpg?v=1");
	gbox.addTiles({id :'buff_jxzh',image :'buff_jxzh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_jy","images/Skil_icons/buff_jy.jpg?v=1");
	gbox.addTiles({id :'buff_jy',image :'buff_jy',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_jzl","images/Skil_icons/buff_jzl.jpg?v=1");
	gbox.addTiles({id :'buff_jzl',image :'buff_jzl',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_jzzh","images/Skil_icons/buff_jzzh.jpg?v=1");
	gbox.addTiles({id :'buff_jzzh',image :'buff_jzzh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_kh","images/Skil_icons/buff_kh.jpg?v=1");
	gbox.addTiles({id :'buff_kh',image :'buff_kh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_lydj","images/Skil_icons/buff_lydj.jpg?v=1");
	gbox.addTiles({id :'buff_lydj',image :'buff_lydj',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_mdzy","images/Skil_icons/buff_mdzy.jpg?v=1");
	gbox.addTiles({id :'buff_mdzy',image :'buff_mdzy',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_mx","images/Skil_icons/buff_mx.jpg?v=1");
	gbox.addTiles({id :'buff_mx',image :'buff_mx',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_my","images/Skil_icons/buff_my.jpg?v=1");
	gbox.addTiles({id :'buff_my',image :'buff_my',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_slzh","images/Skil_icons/buff_slzh.jpg?v=1");
	gbox.addTiles({id :'buff_slzh',image :'buff_slzh',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_tx","images/Skil_icons/buff_tx.jpg?v=1");
	gbox.addTiles({id :'buff_tx',image :'buff_tx',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_wyzy","images/Skil_icons/buff_wyzy.jpg?v=1");
	gbox.addTiles({id :'buff_wyzy',image :'buff_wyzy',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_xjdl","images/Skil_icons/buff_xjdl.jpg?v=1");
	gbox.addTiles({id :'buff_xjdl',image :'buff_xjdl',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_xjls","images/Skil_icons/buff_xjls.jpg?v=1");
	gbox.addTiles({id :'buff_xjls',image :'buff_xjls',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_yb","images/Skil_icons/buff_yb.jpg?v=1");
	gbox.addTiles({id :'buff_yb',image :'buff_yb',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_ytfs","images/Skil_icons/buff_ytfs.jpg?v=1");
	gbox.addTiles({id :'buff_ytfs',image :'buff_ytfs',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_zdjj","images/Skil_icons/buff_zdjj.jpg?v=1");
	gbox.addTiles({id :'buff_zdjj',image :'buff_zdjj',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_zf","images/Skil_icons/buff_zf.jpg?v=1");
	gbox.addTiles({id :'buff_zf',image :'buff_zf',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("buff_zybl","images/Skil_icons/buff_zybl.jpg?v=1");
	gbox.addTiles({id :'buff_zybl',image :'buff_zybl',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ji_0_jz","images/Skil_icons/ji_0_jz.jpg?v=1");
	gbox.addTiles({id :'ji_0_jz',image :'ji_0_jz',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jngh","images/Skil_icons/jngh.jpg?v=1");
	gbox.addTiles({id :'jngh',image :'jngh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_0_ds","images/Skil_icons/jn_0_ds.jpg?v=1");
	gbox.addTiles({id :'jn_0_ds',image :'jn_0_ds',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_0_gl","images/Skil_icons/jn_0_gl.jpg?v=1");
	gbox.addTiles({id :'jn_0_gl',image :'jn_0_gl',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_0_gw","images/Skil_icons/jn_0_gw.jpg?v=1");
	gbox.addTiles({id :'jn_0_gw',image :'jn_0_gw',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_0_hcs","images/Skil_icons/jn_0_hcs.jpg?v=1");
	gbox.addTiles({id :'jn_0_hcs',image :'jn_0_hcs',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_0_tj","images/Skil_icons/jn_0_tj.jpg?v=1");
	gbox.addTiles({id :'jn_0_tj',image :'jn_0_tj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_dhj","images/Skil_icons/jn_1_dhj.jpg?v=1");
	gbox.addTiles({id :'jn_1_dhj',image :'jn_1_dhj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_fhj","images/Skil_icons/jn_1_fhj.jpg?v=1");
	gbox.addTiles({id :'jn_1_fhj',image :'jn_1_fhj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_jlsh","images/Skil_icons/jn_1_jlsh.jpg?v=1");
	gbox.addTiles({id :'jn_1_jlsh',image :'jn_1_jlsh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_jzl","images/Skil_icons/jn_1_jzl.jpg?v=1");
	gbox.addTiles({id :'jn_1_jzl',image :'jn_1_jzl',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_jzzh","images/Skil_icons/jn_1_jzzh.jpg?v=1");
	gbox.addTiles({id :'jn_1_jzzh',image :'jn_1_jzzh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_lys","images/Skil_icons/jn_1_lys.jpg?v=1");
	gbox.addTiles({id :'jn_1_lys',image :'jn_1_lys',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_my","images/Skil_icons/jn_1_my.jpg?v=1");
	gbox.addTiles({id :'jn_1_my',image :'jn_1_my',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_wjqf","images/Skil_icons/jn_1_wjqf.jpg?v=1");
	gbox.addTiles({id :'jn_1_wjqf',image :'jn_1_wjqf',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_xjdl","images/Skil_icons/jn_1_xjdl.jpg?v=1");
	gbox.addTiles({id :'jn_1_xjdl',image :'jn_1_xjdl',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_xjhl","images/Skil_icons/jn_1_xjhl.jpg?v=1");
	gbox.addTiles({id :'jn_1_xjhl',image :'jn_1_xjhl',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_xjls","images/Skil_icons/jn_1_xjls.jpg?v=1");
	gbox.addTiles({id :'jn_1_xjls',image :'jn_1_xjls',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_ytfs","images/Skil_icons/jn_1_ytfs.jpg?v=1");
	gbox.addTiles({id :'jn_1_ytfs',image :'jn_1_ytfs',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_1_zds","images/Skil_icons/jn_1_zds.jpg?v=1");
	gbox.addTiles({id :'jn_1_zds',image :'jn_1_zds',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_bqzh","images/Skil_icons/jn_2_bqzh.jpg?v=1");
	gbox.addTiles({id :'jn_2_bqzh',image :'jn_2_bqzh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_cx","images/Skil_icons/jn_2_cx.jpg?v=1");
	gbox.addTiles({id :'jn_2_cx',image :'jn_2_cx',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_dc","images/Skil_icons/jn_2_dc.jpg?v=1");
	gbox.addTiles({id :'jn_2_dc',image :'jn_2_dc',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_gksh","images/Skil_icons/jn_2_gksh.jpg?v=1");
	gbox.addTiles({id :'jn_2_gksh',image :'jn_2_gksh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_gs","images/Skil_icons/jn_2_gs.jpg?v=1");
	gbox.addTiles({id :'jn_2_gs',image :'jn_2_gs',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_jxzh","images/Skil_icons/jn_2_jxzh.jpg?v=1");
	gbox.addTiles({id :'jn_2_jxzh',image :'jn_2_jxzh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_kh","images/Skil_icons/jn_2_kh.jpg?v=1");
	gbox.addTiles({id :'jn_2_kh',image :'jn_2_kh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_kx","images/Skil_icons/jn_2_kx.jpg?v=1");
	gbox.addTiles({id :'jn_2_kx',image :'jn_2_kx',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_lfz","images/Skil_icons/jn_2_lfz.jpg?v=1");
	gbox.addTiles({id :'jn_2_lfz',image :'jn_2_lfz',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_lydj","images/Skil_icons/jn_2_lydj.jpg?v=1");
	gbox.addTiles({id :'jn_2_lydj',image :'jn_2_lydj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_mx","images/Skil_icons/jn_2_mx.jpg?v=1");
	gbox.addTiles({id :'jn_2_mx',image :'jn_2_mx',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_slzh","images/Skil_icons/jn_2_slzh.jpg?v=1");
	gbox.addTiles({id :'jn_2_slzh',image :'jn_2_slzh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_tx","images/Skil_icons/jn_2_tx.jpg?v=1");
	gbox.addTiles({id :'jn_2_tx',image :'jn_2_tx',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_2_yydj","images/Skil_icons/jn_2_yydj.jpg?v=1");
	gbox.addTiles({id :'jn_2_yydj',image :'jn_2_yydj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_dg","images/Skil_icons/jn_3_dg.jpg?v=1");
	gbox.addTiles({id :'jn_3_dg',image :'jn_3_dg',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_gh","images/Skil_icons/jn_3_gh.jpg?v=1");
	gbox.addTiles({id :'jn_3_gh',image :'jn_3_gh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_jsfs","images/Skil_icons/jn_3_jsfs.jpg?v=1");
	gbox.addTiles({id :'jn_3_jsfs',image :'jn_3_jsfs',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_jy","images/Skil_icons/jn_3_jy.jpg?v=1");
	gbox.addTiles({id :'jn_3_jy',image :'jn_3_jy',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_mdzy","images/Skil_icons/jn_3_mdzy.jpg?v=1");
	gbox.addTiles({id :'jn_3_mdzy',image :'jn_3_mdzy',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_ssjh","images/Skil_icons/jn_3_ssjh.jpg?v=1");
	gbox.addTiles({id :'jn_3_ssjh',image :'jn_3_ssjh',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_wwgj","images/Skil_icons/jn_3_wwgj.jpg?v=1");
	gbox.addTiles({id :'jn_3_wwgj',image :'jn_3_wwgj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_wyzy","images/Skil_icons/jn_3_wyzy.jpg?v=1");
	gbox.addTiles({id :'jn_3_wyzy',image :'jn_3_wyzy',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_xlaf","images/Skil_icons/jn_3_xlaf.jpg?v=1");
	gbox.addTiles({id :'jn_3_xlaf',image :'jn_3_xlaf',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_yb","images/Skil_icons/jn_3_yb.jpg?v=1");
	gbox.addTiles({id :'jn_3_yb',image :'jn_3_yb',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_zdjj","images/Skil_icons/jn_3_zdjj.jpg?v=1");
	gbox.addTiles({id :'jn_3_zdjj',image :'jn_3_zdjj',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_zf","images/Skil_icons/jn_3_zf.jpg?v=1");
	gbox.addTiles({id :'jn_3_zf',image :'jn_3_zf',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jn_3_zybl","images/Skil_icons/jn_3_zybl.jpg?v=1");
	gbox.addTiles({id :'jn_3_zybl',image :'jn_3_zybl',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("testjn","images/Skil_icons/testjn.jpg?v=1");
	gbox.addTiles({id :'testjn',image :'testjn',tilew:45,tileh:45,tilerow : 1,gapx : 0,gapy : 0});

};