var SmallGeneralsAvatarLoadImage = function()
{
	gbox.addImage("X_FH_01","images/Small_generals_Avatar/X_FH_01.jpg?v=1");
	gbox.addTiles({id :'X_FH_01',image :'X_FH_01',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_02","images/Small_generals_Avatar/X_FH_02.jpg?v=1");
	gbox.addTiles({id :'X_FH_02',image :'X_FH_02',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_03","images/Small_generals_Avatar/X_FH_03.jpg?v=1");
	gbox.addTiles({id :'X_FH_03',image :'X_FH_03',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_04","images/Small_generals_Avatar/X_FH_04.jpg?v=1");
	gbox.addTiles({id :'X_FH_04',image :'X_FH_04',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_05","images/Small_generals_Avatar/X_FH_05.jpg?v=1");
	gbox.addTiles({id :'X_FH_05',image :'X_FH_05',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_06","images/Small_generals_Avatar/X_FH_06.jpg?v=1");
	gbox.addTiles({id :'X_FH_06',image :'X_FH_06',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_07","images/Small_generals_Avatar/X_FH_07.jpg?v=1");
	gbox.addTiles({id :'X_FH_07',image :'X_FH_07',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_08","images/Small_generals_Avatar/X_FH_08.jpg?v=1");
	gbox.addTiles({id :'X_FH_08',image :'X_FH_08',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_09","images/Small_generals_Avatar/X_FH_09.jpg?v=1");
	gbox.addTiles({id :'X_FH_09',image :'X_FH_09',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_10","images/Small_generals_Avatar/X_FH_10.jpg?v=1");
	gbox.addTiles({id :'X_FH_10',image :'X_FH_10',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_11","images/Small_generals_Avatar/X_FH_11.jpg?v=1");
	gbox.addTiles({id :'X_FH_11',image :'X_FH_11',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_12","images/Small_generals_Avatar/X_FH_12.jpg?v=1");
	gbox.addTiles({id :'X_FH_12',image :'X_FH_12',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_13","images/Small_generals_Avatar/X_FH_13.jpg?v=1");
	gbox.addTiles({id :'X_FH_13',image :'X_FH_13',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_14","images/Small_generals_Avatar/X_FH_14.jpg?v=1");
	gbox.addTiles({id :'X_FH_14',image :'X_FH_14',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_15","images/Small_generals_Avatar/X_FH_15.jpg?v=1");
	gbox.addTiles({id :'X_FH_15',image :'X_FH_15',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_16","images/Small_generals_Avatar/X_FH_16.jpg?v=1");
	gbox.addTiles({id :'X_FH_16',image :'X_FH_16',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_17","images/Small_generals_Avatar/X_FH_17.jpg?v=1");
	gbox.addTiles({id :'X_FH_17',image :'X_FH_17',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_18","images/Small_generals_Avatar/X_FH_18.jpg?v=1");
	gbox.addTiles({id :'X_FH_18',image :'X_FH_18',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_19","images/Small_generals_Avatar/X_FH_19.jpg?v=1");
	gbox.addTiles({id :'X_FH_19',image :'X_FH_19',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_20","images/Small_generals_Avatar/X_FH_20.jpg?v=1");
	gbox.addTiles({id :'X_FH_20',image :'X_FH_20',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_21","images/Small_generals_Avatar/X_FH_21.jpg?v=1");
	gbox.addTiles({id :'X_FH_21',image :'X_FH_21',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_22","images/Small_generals_Avatar/X_FH_22.jpg?v=1");
	gbox.addTiles({id :'X_FH_22',image :'X_FH_22',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_23","images/Small_generals_Avatar/X_FH_23.jpg?v=1");
	gbox.addTiles({id :'X_FH_23',image :'X_FH_23',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_24","images/Small_generals_Avatar/X_FH_24.jpg?v=1");
	gbox.addTiles({id :'X_FH_24',image :'X_FH_24',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_25","images/Small_generals_Avatar/X_FH_25.jpg?v=1");
	gbox.addTiles({id :'X_FH_25',image :'X_FH_25',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_26","images/Small_generals_Avatar/X_FH_26.jpg?v=1");
	gbox.addTiles({id :'X_FH_26',image :'X_FH_26',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_27","images/Small_generals_Avatar/X_FH_27.jpg?v=1");
	gbox.addTiles({id :'X_FH_27',image :'X_FH_27',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_28","images/Small_generals_Avatar/X_FH_28.jpg?v=1");
	gbox.addTiles({id :'X_FH_28',image :'X_FH_28',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_29","images/Small_generals_Avatar/X_FH_29.jpg?v=1");
	gbox.addTiles({id :'X_FH_29',image :'X_FH_29',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_30","images/Small_generals_Avatar/X_FH_30.jpg?v=1");
	gbox.addTiles({id :'X_FH_30',image :'X_FH_30',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_31","images/Small_generals_Avatar/X_FH_31.jpg?v=1");
	gbox.addTiles({id :'X_FH_31',image :'X_FH_31',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_FH_32","images/Small_generals_Avatar/X_FH_32.jpg?v=1");
	gbox.addTiles({id :'X_FH_32',image :'X_FH_32',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_01","images/Small_generals_Avatar/X_MH_01.jpg?v=1");
	gbox.addTiles({id :'X_MH_01',image :'X_MH_01',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_02","images/Small_generals_Avatar/X_MH_02.jpg?v=1");
	gbox.addTiles({id :'X_MH_02',image :'X_MH_02',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_03","images/Small_generals_Avatar/X_MH_03.jpg?v=1");
	gbox.addTiles({id :'X_MH_03',image :'X_MH_03',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_04","images/Small_generals_Avatar/X_MH_04.jpg?v=1");
	gbox.addTiles({id :'X_MH_04',image :'X_MH_04',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_05","images/Small_generals_Avatar/X_MH_05.jpg?v=1");
	gbox.addTiles({id :'X_MH_05',image :'X_MH_05',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_06","images/Small_generals_Avatar/X_MH_06.jpg?v=1");
	gbox.addTiles({id :'X_MH_06',image :'X_MH_06',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_07","images/Small_generals_Avatar/X_MH_07.jpg?v=1");
	gbox.addTiles({id :'X_MH_07',image :'X_MH_07',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_08","images/Small_generals_Avatar/X_MH_08.jpg?v=1");
	gbox.addTiles({id :'X_MH_08',image :'X_MH_08',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_09","images/Small_generals_Avatar/X_MH_09.jpg?v=1");
	gbox.addTiles({id :'X_MH_09',image :'X_MH_09',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_10","images/Small_generals_Avatar/X_MH_10.jpg?v=1");
	gbox.addTiles({id :'X_MH_10',image :'X_MH_10',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_11","images/Small_generals_Avatar/X_MH_11.jpg?v=1");
	gbox.addTiles({id :'X_MH_11',image :'X_MH_11',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_12","images/Small_generals_Avatar/X_MH_12.jpg?v=1");
	gbox.addTiles({id :'X_MH_12',image :'X_MH_12',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_13","images/Small_generals_Avatar/X_MH_13.jpg?v=1");
	gbox.addTiles({id :'X_MH_13',image :'X_MH_13',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_14","images/Small_generals_Avatar/X_MH_14.jpg?v=1");
	gbox.addTiles({id :'X_MH_14',image :'X_MH_14',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_15","images/Small_generals_Avatar/X_MH_15.jpg?v=1");
	gbox.addTiles({id :'X_MH_15',image :'X_MH_15',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_16","images/Small_generals_Avatar/X_MH_16.jpg?v=1");
	gbox.addTiles({id :'X_MH_16',image :'X_MH_16',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_17","images/Small_generals_Avatar/X_MH_17.jpg?v=1");
	gbox.addTiles({id :'X_MH_17',image :'X_MH_17',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_18","images/Small_generals_Avatar/X_MH_18.jpg?v=1");
	gbox.addTiles({id :'X_MH_18',image :'X_MH_18',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_19","images/Small_generals_Avatar/X_MH_19.jpg?v=1");
	gbox.addTiles({id :'X_MH_19',image :'X_MH_19',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_20","images/Small_generals_Avatar/X_MH_20.jpg?v=1");
	gbox.addTiles({id :'X_MH_20',image :'X_MH_20',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_21","images/Small_generals_Avatar/X_MH_21.jpg?v=1");
	gbox.addTiles({id :'X_MH_21',image :'X_MH_21',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_22","images/Small_generals_Avatar/X_MH_22.jpg?v=1");
	gbox.addTiles({id :'X_MH_22',image :'X_MH_22',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_23","images/Small_generals_Avatar/X_MH_23.jpg?v=1");
	gbox.addTiles({id :'X_MH_23',image :'X_MH_23',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_24","images/Small_generals_Avatar/X_MH_24.jpg?v=1");
	gbox.addTiles({id :'X_MH_24',image :'X_MH_24',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_25","images/Small_generals_Avatar/X_MH_25.jpg?v=1");
	gbox.addTiles({id :'X_MH_25',image :'X_MH_25',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_26","images/Small_generals_Avatar/X_MH_26.jpg?v=1");
	gbox.addTiles({id :'X_MH_26',image :'X_MH_26',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_27","images/Small_generals_Avatar/X_MH_27.jpg?v=1");
	gbox.addTiles({id :'X_MH_27',image :'X_MH_27',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_28","images/Small_generals_Avatar/X_MH_28.jpg?v=1");
	gbox.addTiles({id :'X_MH_28',image :'X_MH_28',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_29","images/Small_generals_Avatar/X_MH_29.jpg?v=1");
	gbox.addTiles({id :'X_MH_29',image :'X_MH_29',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_30","images/Small_generals_Avatar/X_MH_30.jpg?v=1");
	gbox.addTiles({id :'X_MH_30',image :'X_MH_30',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_31","images/Small_generals_Avatar/X_MH_31.jpg?v=1");
	gbox.addTiles({id :'X_MH_31',image :'X_MH_31',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_32","images/Small_generals_Avatar/X_MH_32.jpg?v=1");
	gbox.addTiles({id :'X_MH_32',image :'X_MH_32',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_33","images/Small_generals_Avatar/X_MH_33.jpg?v=1");
	gbox.addTiles({id :'X_MH_33',image :'X_MH_33',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_34","images/Small_generals_Avatar/X_MH_34.jpg?v=1");
	gbox.addTiles({id :'X_MH_34',image :'X_MH_34',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_35","images/Small_generals_Avatar/X_MH_35.jpg?v=1");
	gbox.addTiles({id :'X_MH_35',image :'X_MH_35',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_36","images/Small_generals_Avatar/X_MH_36.jpg?v=1");
	gbox.addTiles({id :'X_MH_36',image :'X_MH_36',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_37","images/Small_generals_Avatar/X_MH_37.jpg?v=1");
	gbox.addTiles({id :'X_MH_37',image :'X_MH_37',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_38","images/Small_generals_Avatar/X_MH_38.jpg?v=1");
	gbox.addTiles({id :'X_MH_38',image :'X_MH_38',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_39","images/Small_generals_Avatar/X_MH_39.jpg?v=1");
	gbox.addTiles({id :'X_MH_39',image :'X_MH_39',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_40","images/Small_generals_Avatar/X_MH_40.jpg?v=1");
	gbox.addTiles({id :'X_MH_40',image :'X_MH_40',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_41","images/Small_generals_Avatar/X_MH_41.jpg?v=1");
	gbox.addTiles({id :'X_MH_41',image :'X_MH_41',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_42","images/Small_generals_Avatar/X_MH_42.jpg?v=1");
	gbox.addTiles({id :'X_MH_42',image :'X_MH_42',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_43","images/Small_generals_Avatar/X_MH_43.jpg?v=1");
	gbox.addTiles({id :'X_MH_43',image :'X_MH_43',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_44","images/Small_generals_Avatar/X_MH_44.jpg?v=1");
	gbox.addTiles({id :'X_MH_44',image :'X_MH_44',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_45","images/Small_generals_Avatar/X_MH_45.jpg?v=1");
	gbox.addTiles({id :'X_MH_45',image :'X_MH_45',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_46","images/Small_generals_Avatar/X_MH_46.jpg?v=1");
	gbox.addTiles({id :'X_MH_46',image :'X_MH_46',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_47","images/Small_generals_Avatar/X_MH_47.jpg?v=1");
	gbox.addTiles({id :'X_MH_47',image :'X_MH_47',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_48","images/Small_generals_Avatar/X_MH_48.jpg?v=1");
	gbox.addTiles({id :'X_MH_48',image :'X_MH_48',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_49","images/Small_generals_Avatar/X_MH_49.jpg?v=1");
	gbox.addTiles({id :'X_MH_49',image :'X_MH_49',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_50","images/Small_generals_Avatar/X_MH_50.jpg?v=1");
	gbox.addTiles({id :'X_MH_50',image :'X_MH_50',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_51","images/Small_generals_Avatar/X_MH_51.jpg?v=1");
	gbox.addTiles({id :'X_MH_51',image :'X_MH_51',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_52","images/Small_generals_Avatar/X_MH_52.jpg?v=1");
	gbox.addTiles({id :'X_MH_52',image :'X_MH_52',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_53","images/Small_generals_Avatar/X_MH_53.jpg?v=1");
	gbox.addTiles({id :'X_MH_53',image :'X_MH_53',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_54","images/Small_generals_Avatar/X_MH_54.jpg?v=1");
	gbox.addTiles({id :'X_MH_54',image :'X_MH_54',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_55","images/Small_generals_Avatar/X_MH_55.jpg?v=1");
	gbox.addTiles({id :'X_MH_55',image :'X_MH_55',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_56","images/Small_generals_Avatar/X_MH_56.jpg?v=1");
	gbox.addTiles({id :'X_MH_56',image :'X_MH_56',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("X_MH_57","images/Small_generals_Avatar/X_MH_57.jpg?v=1");
	gbox.addTiles({id :'X_MH_57',image :'X_MH_57',tilew:70,tileh:94,tilerow : 1,gapx : 0,gapy : 0});	
};