var WorldLoadImage = function()
{
	gbox.addImage("71","images/World/71.png?v=1");
	gbox.addTiles({id :'71',image :'71',tilew:160,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("72","images/World/72.png?v=1");
	gbox.addTiles({id :'72',image :'72',tilew:160,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("73","images/World/73.png?v=1");
	gbox.addTiles({id :'73',image :'73',tilew:160,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("74","images/World/74.png?v=1");
	gbox.addTiles({id :'74',image :'74',tilew:160,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("75","images/World/75.png?v=1");
	gbox.addTiles({id :'75',image :'75',tilew:160,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("arrow","images/World/arrow.png?v=1");
	gbox.addTiles({id :'arrow',image :'arrow',tilew:24,tileh:17,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("caijiBg","images/World/caijiBg.png?v=1");
	gbox.addTiles({id :'caijiBg',image :'caijiBg',tilew:233,tileh:320,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_1","images/World/cc_1.png?v=1");
	gbox.addTiles({id :'cc_1',image :'cc_1',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_1_l","images/World/cc_1_l.png?v=1");
	gbox.addTiles({id :'cc_1_l',image :'cc_1_l',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_2","images/World/cc_2.png?v=1");
	gbox.addTiles({id :'cc_2',image :'cc_2',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_2_l","images/World/cc_2_l.png?v=1");
	gbox.addTiles({id :'cc_2_l',image :'cc_2_l',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_3","images/World/cc_3.png?v=1");
	gbox.addTiles({id :'cc_3',image :'cc_3',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_3_l","images/World/cc_3_l.png?v=1");
	gbox.addTiles({id :'cc_3_l',image :'cc_3_l',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_4","images/World/cc_4.png?v=1");
	gbox.addTiles({id :'cc_4',image :'cc_4',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_4_l","images/World/cc_4_l.png?v=1");
	gbox.addTiles({id :'cc_4_l',image :'cc_4_l',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_5","images/World/cc_5.png?v=1");
	gbox.addTiles({id :'cc_5',image :'cc_5',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cc_5_l","images/World/cc_5_l.png?v=1");
	gbox.addTiles({id :'cc_5_l',image :'cc_5_l',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("circle1","images/World/circle1.png?v=1");
	gbox.addTiles({id :'circle1',image :'circle1',tilew:44,tileh:44,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("circle2","images/World/circle2.png?v=1");
	gbox.addTiles({id :'circle2',image :'circle2',tilew:38,tileh:36,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cityPoint","images/World/cityPoint.png?v=1");
	gbox.addTiles({id :'cityPoint',image :'cityPoint',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_HP_01","images/World/DT_BJ_HP_01.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_HP_01',image :'DT_BJ_HP_01',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_HP_02","images/World/DT_BJ_HP_02.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_HP_02',image :'DT_BJ_HP_02',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_HP_03","images/World/DT_BJ_HP_03.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_HP_03',image :'DT_BJ_HP_03',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_01","images/World/DT_BJ_PY_01.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_01',image :'DT_BJ_PY_01',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_02","images/World/DT_BJ_PY_02.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_02',image :'DT_BJ_PY_02',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_03","images/World/DT_BJ_PY_03.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_03',image :'DT_BJ_PY_03',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_04","images/World/DT_BJ_PY_04.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_04',image :'DT_BJ_PY_04',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_05","images/World/DT_BJ_PY_05.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_05',image :'DT_BJ_PY_05',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_06","images/World/DT_BJ_PY_06.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_06',image :'DT_BJ_PY_06',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_07","images/World/DT_BJ_PY_07.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_07',image :'DT_BJ_PY_07',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_08","images/World/DT_BJ_PY_08.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_08',image :'DT_BJ_PY_08',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_PY_09","images/World/DT_BJ_PY_09.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_PY_09',image :'DT_BJ_PY_09',tilew:200,tileh:100,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SD_01","images/World/DT_BJ_SD_01.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SD_01',image :'DT_BJ_SD_01',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SD_02","images/World/DT_BJ_SD_02.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SD_02',image :'DT_BJ_SD_02',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SD_03","images/World/DT_BJ_SD_03.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SD_03',image :'DT_BJ_SD_03',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SD_04","images/World/DT_BJ_SD_04.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SD_04',image :'DT_BJ_SD_04',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SD_05","images/World/DT_BJ_SD_05.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SD_05',image :'DT_BJ_SD_05',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_01","images/World/DT_BJ_SL_01.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_01',image :'DT_BJ_SL_01',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_02","images/World/DT_BJ_SL_02.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_02',image :'DT_BJ_SL_02',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_03","images/World/DT_BJ_SL_03.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_03',image :'DT_BJ_SL_03',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_04","images/World/DT_BJ_SL_04.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_04',image :'DT_BJ_SL_04',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_05","images/World/DT_BJ_SL_05.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_05',image :'DT_BJ_SL_05',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SL_06","images/World/DT_BJ_SL_06.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SL_06',image :'DT_BJ_SL_06',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_01","images/World/DT_BJ_SM_01.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_01',image :'DT_BJ_SM_01',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_02","images/World/DT_BJ_SM_02.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_02',image :'DT_BJ_SM_02',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_03","images/World/DT_BJ_SM_03.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_03',image :'DT_BJ_SM_03',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_04","images/World/DT_BJ_SM_04.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_04',image :'DT_BJ_SM_04',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_05","images/World/DT_BJ_SM_05.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_05',image :'DT_BJ_SM_05',tilew:200,tileh:100,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_06","images/World/DT_BJ_SM_06.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_06',image :'DT_BJ_SM_06',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_07","images/World/DT_BJ_SM_07.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_07',image :'DT_BJ_SM_07',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_08","images/World/DT_BJ_SM_08.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_08',image :'DT_BJ_SM_08',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_09","images/World/DT_BJ_SM_09.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_09',image :'DT_BJ_SM_09',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_10","images/World/DT_BJ_SM_10.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_10',image :'DT_BJ_SM_10',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_11","images/World/DT_BJ_SM_11.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_11',image :'DT_BJ_SM_11',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_12","images/World/DT_BJ_SM_12.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_12',image :'DT_BJ_SM_12',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_13","images/World/DT_BJ_SM_13.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_13',image :'DT_BJ_SM_13',tilew:400,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_14","images/World/DT_BJ_SM_14.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_14',image :'DT_BJ_SM_14',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_15","images/World/DT_BJ_SM_15.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_15',image :'DT_BJ_SM_15',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_16","images/World/DT_BJ_SM_16.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_16',image :'DT_BJ_SM_16',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_17","images/World/DT_BJ_SM_17.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_17',image :'DT_BJ_SM_17',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_BJ_SM_18","images/World/DT_BJ_SM_18.jpg?v=1");
	gbox.addTiles({id :'DT_BJ_SM_18',image :'DT_BJ_SM_18',tilew:800,tileh:400,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_01","images/World/DT_TT_SB_01.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_01',image :'DT_TT_SB_01',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_02","images/World/DT_TT_SB_02.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_02',image :'DT_TT_SB_02',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_03","images/World/DT_TT_SB_03.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_03',image :'DT_TT_SB_03',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_04","images/World/DT_TT_SB_04.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_04',image :'DT_TT_SB_04',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_05","images/World/DT_TT_SB_05.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_05',image :'DT_TT_SB_05',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_SB_06","images/World/DT_TT_SB_06.png?v=1");
	gbox.addTiles({id :'DT_TT_SB_06',image :'DT_TT_SB_06',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_01","images/World/DT_TT_XB_01.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_01',image :'DT_TT_XB_01',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_02","images/World/DT_TT_XB_02.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_02',image :'DT_TT_XB_02',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_03","images/World/DT_TT_XB_03.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_03',image :'DT_TT_XB_03',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_04","images/World/DT_TT_XB_04.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_04',image :'DT_TT_XB_04',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_05","images/World/DT_TT_XB_05.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_05',image :'DT_TT_XB_05',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_XB_06","images/World/DT_TT_XB_06.png?v=1");
	gbox.addTiles({id :'DT_TT_XB_06',image :'DT_TT_XB_06',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_YB_01","images/World/DT_TT_YB_01.png?v=1");
	gbox.addTiles({id :'DT_TT_YB_01',image :'DT_TT_YB_01',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_YB_02","images/World/DT_TT_YB_02.png?v=1");
	gbox.addTiles({id :'DT_TT_YB_02',image :'DT_TT_YB_02',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_YB_03","images/World/DT_TT_YB_03.png?v=1");
	gbox.addTiles({id :'DT_TT_YB_03',image :'DT_TT_YB_03',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_YB_04","images/World/DT_TT_YB_04.png?v=1");
	gbox.addTiles({id :'DT_TT_YB_04',image :'DT_TT_YB_04',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_ZB_01","images/World/DT_TT_ZB_01.png?v=1");
	gbox.addTiles({id :'DT_TT_ZB_01',image :'DT_TT_ZB_01',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_ZB_02","images/World/DT_TT_ZB_02.png?v=1");
	gbox.addTiles({id :'DT_TT_ZB_02',image :'DT_TT_ZB_02',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_ZB_03","images/World/DT_TT_ZB_03.png?v=1");
	gbox.addTiles({id :'DT_TT_ZB_03',image :'DT_TT_ZB_03',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DT_TT_ZB_04","images/World/DT_TT_ZB_04.png?v=1");
	gbox.addTiles({id :'DT_TT_ZB_04',image :'DT_TT_ZB_04',tilew:200,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("radar","images/World/radar.png?v=1");
	gbox.addTiles({id :'radar',image :'radar',tilew:191,tileh:195,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("rhomb","images/World/rhomb.png?v=1");
	gbox.addTiles({id :'rhomb',image :'rhomb',tilew:100,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("rhomb1","images/World/rhomb1.png?v=1");
	gbox.addTiles({id :'rhomb1',image :'rhomb1',tilew:100,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_bm","images/World/sjdt_yg_bm.png?v=1");
	gbox.addTiles({id :'sjdt_yg_bm',image :'sjdt_yg_bm',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_cb","images/World/sjdt_yg_cb.png?v=1");
	gbox.addTiles({id :'sjdt_yg_cb',image :'sjdt_yg_cb',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_lk","images/World/sjdt_yg_lk.png?v=1");
	gbox.addTiles({id :'sjdt_yg_lk',image :'sjdt_yg_lk',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_mz","images/World/sjdt_yg_mz.png?v=1");
	gbox.addTiles({id :'sjdt_yg_mz',image :'sjdt_yg_mz',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_mzu","images/World/sjdt_yg_mzu.png?v=1");
	gbox.addTiles({id :'sjdt_yg_mzu',image :'sjdt_yg_mzu',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_pj","images/World/sjdt_yg_pj.png?v=1");
	gbox.addTiles({id :'sjdt_yg_pj',image :'sjdt_yg_pj',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_qd","images/World/sjdt_yg_qd.png?v=1");
	gbox.addTiles({id :'sjdt_yg_qd',image :'sjdt_yg_qd',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_yg_tf","images/World/sjdt_yg_tf.png?v=1");
	gbox.addTiles({id :'sjdt_yg_tf',image :'sjdt_yg_tf',tilew:120,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_01","images/World/sjdt_zjm_01.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_01',image :'sjdt_zjm_01',tilew:1023,tileh:542,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_10","images/World/sjdt_zjm_10.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_10',image :'sjdt_zjm_10',tilew:34,tileh:56,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_11","images/World/sjdt_zjm_11.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_11',image :'sjdt_zjm_11',tilew:274,tileh:151,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_18","images/World/sjdt_zjm_18.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_18',image :'sjdt_zjm_18',tilew:4,tileh:4,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_19","images/World/sjdt_zjm_19.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_19',image :'sjdt_zjm_19',tilew:10,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_20","images/World/sjdt_zjm_20.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_20',image :'sjdt_zjm_20',tilew:4,tileh:4,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_21","images/World/sjdt_zjm_21.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_21',image :'sjdt_zjm_21',tilew:10,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_22","images/World/sjdt_zjm_22.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_22',image :'sjdt_zjm_22',tilew:10,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_23","images/World/sjdt_zjm_23.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_23',image :'sjdt_zjm_23',tilew:4,tileh:4,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_24","images/World/sjdt_zjm_24.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_24',image :'sjdt_zjm_24',tilew:15,tileh:15,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_25","images/World/sjdt_zjm_25.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_25',image :'sjdt_zjm_25',tilew:9,tileh:9,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_26","images/World/sjdt_zjm_26.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_26',image :'sjdt_zjm_26',tilew:480,tileh:320,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_27","images/World/sjdt_zjm_27.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_27',image :'sjdt_zjm_27',tilew:480,tileh:320,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_28","images/World/sjdt_zjm_28.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_28',image :'sjdt_zjm_28',tilew:480,tileh:320,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_29","images/World/sjdt_zjm_29.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_29',image :'sjdt_zjm_29',tilew:480,tileh:320,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_30","images/World/sjdt_zjm_30.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_30',image :'sjdt_zjm_30',tilew:480,tileh:240,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_34","images/World/sjdt_zjm_34.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_34',image :'sjdt_zjm_34',tilew:45,tileh:19,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_35","images/World/sjdt_zjm_35.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_35',image :'sjdt_zjm_35',tilew:68,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("sjdt_zjm_37","images/World/sjdt_zjm_37.png?v=1");
	gbox.addTiles({id :'sjdt_zjm_37',image :'sjdt_zjm_37',tilew:34,tileh:34,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("world_bg","images/World/world_bg.jpg?v=1");
	gbox.addTiles({id :'world_bg',image :'world_bg',tilew:800,tileh:800,tilerow : 1,gapx : 0,gapy : 0});

};