var age1LoadImage = function()
{
	gbox.addImage("by_1","images/Urban_upgrading/age1/by_1.png?v=1");
	gbox.addTiles({id :'by_1',image :'by_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_1_l","images/Urban_upgrading/age1/by_1_l.png?v=1");
	gbox.addTiles({id :'by_1_l',image :'by_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cjt_1","images/Urban_upgrading/age1/cjt_1.jpg?v=1");
	gbox.addTiles({id :'cjt_1',image :'cjt_1',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_1","images/Urban_upgrading/age1/cq_1.png?v=1");
	gbox.addTiles({id :'cq_1',image :'cq_1',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_1_l","images/Urban_upgrading/age1/cq_1_l.png?v=1");
	gbox.addTiles({id :'cq_1_l',image :'cq_1_l',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_1","images/Urban_upgrading/age1/dj_1.png?v=1");
	gbox.addTiles({id :'dj_1',image :'dj_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_1_l","images/Urban_upgrading/age1/dj_1_l.png?v=1");
	gbox.addTiles({id :'dj_1_l',image :'dj_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_1","images/Urban_upgrading/age1/gk_1.png?v=1");
	gbox.addTiles({id :'gk_1',image :'gk_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_1_l","images/Urban_upgrading/age1/gk_1_l.png?v=1");
	gbox.addTiles({id :'gk_1_l',image :'gk_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_1","images/Urban_upgrading/age1/jf_1.png?v=1");
	gbox.addTiles({id :'jf_1',image :'jf_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_1_l","images/Urban_upgrading/age1/jf_1_l.png?v=1");
	gbox.addTiles({id :'jf_1_l',image :'jf_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_1","images/Urban_upgrading/age1/jgf_1.png?v=1");
	gbox.addTiles({id :'jgf_1',image :'jgf_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_1_l","images/Urban_upgrading/age1/jgf_1_l.png?v=1");
	gbox.addTiles({id :'jgf_1_l',image :'jgf_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_1","images/Urban_upgrading/age1/jg_1.png?v=1");
	gbox.addTiles({id :'jg_1',image :'jg_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_1_l","images/Urban_upgrading/age1/jg_1_l.png?v=1");
	gbox.addTiles({id :'jg_1_l',image :'jg_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_1","images/Urban_upgrading/age1/jjc_1.png?v=1");
	gbox.addTiles({id :'jjc_1',image :'jjc_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_1_l","images/Urban_upgrading/age1/jjc_1_l.png?v=1");
	gbox.addTiles({id :'jjc_1_l',image :'jjc_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_1","images/Urban_upgrading/age1/js_1.png?v=1");
	gbox.addTiles({id :'js_1',image :'js_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_1_l","images/Urban_upgrading/age1/js_1_l.png?v=1");
	gbox.addTiles({id :'js_1_l',image :'js_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_1","images/Urban_upgrading/age1/jxg_1.png?v=1");
	gbox.addTiles({id :'jxg_1',image :'jxg_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_1_l","images/Urban_upgrading/age1/jxg_1_l.png?v=1");
	gbox.addTiles({id :'jxg_1_l',image :'jxg_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_1","images/Urban_upgrading/age1/kd_1.png?v=1");
	gbox.addTiles({id :'kd_1',image :'kd_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_1_l","images/Urban_upgrading/age1/kd_1_l.png?v=1");
	gbox.addTiles({id :'kd_1_l',image :'kd_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_1","images/Urban_upgrading/age1/kjg_1.png?v=1");
	gbox.addTiles({id :'kjg_1',image :'kjg_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_1_l","images/Urban_upgrading/age1/kjg_1_l.png?v=1");
	gbox.addTiles({id :'kjg_1_l',image :'kjg_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_1","images/Urban_upgrading/age1/lbc_1.png?v=1");
	gbox.addTiles({id :'lbc_1',image :'lbc_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_1_l","images/Urban_upgrading/age1/lbc_1_l.png?v=1");
	gbox.addTiles({id :'lbc_1_l',image :'lbc_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_1","images/Urban_upgrading/age1/mj_1.png?v=1");
	gbox.addTiles({id :'mj_1',image :'mj_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_1_l","images/Urban_upgrading/age1/mj_1_l.png?v=1");
	gbox.addTiles({id :'mj_1_l',image :'mj_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_1","images/Urban_upgrading/age1/twf_1.png?v=1");
	gbox.addTiles({id :'twf_1',image :'twf_1',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_1_l","images/Urban_upgrading/age1/twf_1_l.png?v=1");
	gbox.addTiles({id :'twf_1_l',image :'twf_1_l',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_1","images/Urban_upgrading/age1/tys_1.png?v=1");
	gbox.addTiles({id :'tys_1',image :'tys_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_1_l","images/Urban_upgrading/age1/tys_1_l.png?v=1");
	gbox.addTiles({id :'tys_1_l',image :'tys_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_1","images/Urban_upgrading/age1/wwg_1.png?v=1");
	gbox.addTiles({id :'wwg_1',image :'wwg_1',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_1_l","images/Urban_upgrading/age1/wwg_1_l.png?v=1");
	gbox.addTiles({id :'wwg_1_l',image :'wwg_1_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});

};