var age2LoadImage = function()
{
	gbox.addImage("by_2","images/Urban_upgrading/age2/by_2.png?v=1");
	gbox.addTiles({id :'by_2',image :'by_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_2_l","images/Urban_upgrading/age2/by_2_l.png?v=1");
	gbox.addTiles({id :'by_2_l',image :'by_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cjt_2","images/Urban_upgrading/age2/cjt_2.jpg?v=1");
	gbox.addTiles({id :'cjt_2',image :'cjt_2',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_2_l","images/Urban_upgrading/age2/cq_2_l.png?v=1");
	gbox.addTiles({id :'cq_2_l',image :'cq_2_l',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_2","images/Urban_upgrading/age2/dj_2.png?v=1");
	gbox.addTiles({id :'dj_2',image :'dj_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_2_l","images/Urban_upgrading/age2/dj_2_l.png?v=1");
	gbox.addTiles({id :'dj_2_l',image :'dj_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_2","images/Urban_upgrading/age2/gk_2.png?v=1");
	gbox.addTiles({id :'gk_2',image :'gk_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_2_l","images/Urban_upgrading/age2/gk_2_l.png?v=1");
	gbox.addTiles({id :'gk_2_l',image :'gk_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_2","images/Urban_upgrading/age2/jf_2.png?v=1");
	gbox.addTiles({id :'jf_2',image :'jf_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_2_l","images/Urban_upgrading/age2/jf_2_l.png?v=1");
	gbox.addTiles({id :'jf_2_l',image :'jf_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_2","images/Urban_upgrading/age2/jgf_2.png?v=1");
	gbox.addTiles({id :'jgf_2',image :'jgf_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_2_l","images/Urban_upgrading/age2/jgf_2_l.png?v=1");
	gbox.addTiles({id :'jgf_2_l',image :'jgf_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_2","images/Urban_upgrading/age2/jg_2.png?v=1");
	gbox.addTiles({id :'jg_2',image :'jg_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_2_l","images/Urban_upgrading/age2/jg_2_l.png?v=1");
	gbox.addTiles({id :'jg_2_l',image :'jg_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_2","images/Urban_upgrading/age2/jjc_2.png?v=1");
	gbox.addTiles({id :'jjc_2',image :'jjc_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_2_l","images/Urban_upgrading/age2/jjc_2_l.png?v=1");
	gbox.addTiles({id :'jjc_2_l',image :'jjc_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_2","images/Urban_upgrading/age2/js_2.png?v=1");
	gbox.addTiles({id :'js_2',image :'js_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_2_l","images/Urban_upgrading/age2/js_2_l.png?v=1");
	gbox.addTiles({id :'js_2_l',image :'js_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_2","images/Urban_upgrading/age2/jxg_2.png?v=1");
	gbox.addTiles({id :'jxg_2',image :'jxg_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_2_l","images/Urban_upgrading/age2/jxg_2_l.png?v=1");
	gbox.addTiles({id :'jxg_2_l',image :'jxg_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_2","images/Urban_upgrading/age2/kd_2.png?v=1");
	gbox.addTiles({id :'kd_2',image :'kd_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_2_l","images/Urban_upgrading/age2/kd_2_l.png?v=1");
	gbox.addTiles({id :'kd_2_l',image :'kd_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_2","images/Urban_upgrading/age2/kjg_2.png?v=1");
	gbox.addTiles({id :'kjg_2',image :'kjg_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_2_l","images/Urban_upgrading/age2/kjg_2_l.png?v=1");
	gbox.addTiles({id :'kjg_2_l',image :'kjg_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_2","images/Urban_upgrading/age2/lbc_2.png?v=1");
	gbox.addTiles({id :'lbc_2',image :'lbc_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_2_l","images/Urban_upgrading/age2/lbc_2_l.png?v=1");
	gbox.addTiles({id :'lbc_2_l',image :'lbc_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_2","images/Urban_upgrading/age2/mj_2.png?v=1");
	gbox.addTiles({id :'mj_2',image :'mj_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_2_l","images/Urban_upgrading/age2/mj_2_l.png?v=1");
	gbox.addTiles({id :'mj_2_l',image :'mj_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_2","images/Urban_upgrading/age2/twf_2.png?v=1");
	gbox.addTiles({id :'twf_2',image :'twf_2',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_2_l","images/Urban_upgrading/age2/twf_2_l.png?v=1");
	gbox.addTiles({id :'twf_2_l',image :'twf_2_l',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_2","images/Urban_upgrading/age2/tys_2.png?v=1");
	gbox.addTiles({id :'tys_2',image :'tys_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_2_l","images/Urban_upgrading/age2/tys_2_l.png?v=1");
	gbox.addTiles({id :'tys_2_l',image :'tys_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_2","images/Urban_upgrading/age2/wwg_2.png?v=1");
	gbox.addTiles({id :'wwg_2',image :'wwg_2',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_2_l","images/Urban_upgrading/age2/wwg_2_l.png?v=1");
	gbox.addTiles({id :'wwg_2_l',image :'wwg_2_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});

};