var age4LoadImage = function()
{
	gbox.addImage("by_4","images/Urban_upgrading/age4/by_4.png?v=1");
	gbox.addTiles({id :'by_4',image :'by_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_4_l","images/Urban_upgrading/age4/by_4_l.png?v=1");
	gbox.addTiles({id :'by_4_l',image :'by_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cjt_4","images/Urban_upgrading/age4/cjt_4.jpg?v=1");
	gbox.addTiles({id :'cjt_4',image :'cjt_4',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cq_4_l","images/Urban_upgrading/age4/cq_4_l.png?v=1");
	gbox.addTiles({id :'cq_4_l',image :'cq_4_l',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_4","images/Urban_upgrading/age4/dj_4.png?v=1");
	gbox.addTiles({id :'dj_4',image :'dj_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_4_l","images/Urban_upgrading/age4/dj_4_l.png?v=1");
	gbox.addTiles({id :'dj_4_l',image :'dj_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_4","images/Urban_upgrading/age4/gk_4.png?v=1");
	gbox.addTiles({id :'gk_4',image :'gk_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_4_l","images/Urban_upgrading/age4/gk_4_l.png?v=1");
	gbox.addTiles({id :'gk_4_l',image :'gk_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_4","images/Urban_upgrading/age4/jf_4.png?v=1");
	gbox.addTiles({id :'jf_4',image :'jf_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_4_l","images/Urban_upgrading/age4/jf_4_l.png?v=1");
	gbox.addTiles({id :'jf_4_l',image :'jf_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_4","images/Urban_upgrading/age4/jgf_4.png?v=1");
	gbox.addTiles({id :'jgf_4',image :'jgf_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_4_l","images/Urban_upgrading/age4/jgf_4_l.png?v=1");
	gbox.addTiles({id :'jgf_4_l',image :'jgf_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_4","images/Urban_upgrading/age4/jg_4.png?v=1");
	gbox.addTiles({id :'jg_4',image :'jg_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_4_l","images/Urban_upgrading/age4/jg_4_l.png?v=1");
	gbox.addTiles({id :'jg_4_l',image :'jg_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_4","images/Urban_upgrading/age4/jjc_4.png?v=1");
	gbox.addTiles({id :'jjc_4',image :'jjc_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_4_l","images/Urban_upgrading/age4/jjc_4_l.png?v=1");
	gbox.addTiles({id :'jjc_4_l',image :'jjc_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_4","images/Urban_upgrading/age4/js_4.png?v=1");
	gbox.addTiles({id :'js_4',image :'js_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_4_l","images/Urban_upgrading/age4/js_4_l.png?v=1");
	gbox.addTiles({id :'js_4_l',image :'js_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_4","images/Urban_upgrading/age4/jxg_4.png?v=1");
	gbox.addTiles({id :'jxg_4',image :'jxg_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_4_l","images/Urban_upgrading/age4/jxg_4_l.png?v=1");
	gbox.addTiles({id :'jxg_4_l',image :'jxg_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_4","images/Urban_upgrading/age4/kd_4.png?v=1");
	gbox.addTiles({id :'kd_4',image :'kd_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kd_4_l","images/Urban_upgrading/age4/kd_4_l.png?v=1");
	gbox.addTiles({id :'kd_4_l',image :'kd_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_4","images/Urban_upgrading/age4/kjg_4.png?v=1");
	gbox.addTiles({id :'kjg_4',image :'kjg_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_4_l","images/Urban_upgrading/age4/kjg_4_l.png?v=1");
	gbox.addTiles({id :'kjg_4_l',image :'kjg_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_4","images/Urban_upgrading/age4/lbc_4.png?v=1");
	gbox.addTiles({id :'lbc_4',image :'lbc_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_4_l","images/Urban_upgrading/age4/lbc_4_l.png?v=1");
	gbox.addTiles({id :'lbc_4_l',image :'lbc_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_4","images/Urban_upgrading/age4/mj_4.png?v=1");
	gbox.addTiles({id :'mj_4',image :'mj_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_4_l","images/Urban_upgrading/age4/mj_4_l.png?v=1");
	gbox.addTiles({id :'mj_4_l',image :'mj_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_4","images/Urban_upgrading/age4/twf_4.png?v=1");
	gbox.addTiles({id :'twf_4',image :'twf_4',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("twf_4_l","images/Urban_upgrading/age4/twf_4_l.png?v=1");
	gbox.addTiles({id :'twf_4_l',image :'twf_4_l',tilew:394,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_4","images/Urban_upgrading/age4/tys_4.png?v=1");
	gbox.addTiles({id :'tys_4',image :'tys_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_4_l","images/Urban_upgrading/age4/tys_4_l.png?v=1");
	gbox.addTiles({id :'tys_4_l',image :'tys_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_4","images/Urban_upgrading/age4/wwg_4.png?v=1");
	gbox.addTiles({id :'wwg_4',image :'wwg_4',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_4_l","images/Urban_upgrading/age4/wwg_4_l.png?v=1");
	gbox.addTiles({id :'wwg_4_l',image :'wwg_4_l',tilew:156,tileh:160,tilerow : 1,gapx : 0,gapy : 0});

};