var Equipment_iconLoadImage = function()
{
	gbox.addImage("ZB_BC_30","images/Equipment_icon/ZB_BC_30.jpg?v=1");
	gbox.addTiles({id :'ZB_BC_30',image :'ZB_BC_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_BJD_60","images/Equipment_icon/ZB_BJD_60.jpg?v=1");
	gbox.addTiles({id :'ZB_BJD_60',image :'ZB_BJD_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CCHJ_30","images/Equipment_icon/ZB_CCHJ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_CCHJ_30',image :'ZB_CCHJ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CCHW_30","images/Equipment_icon/ZB_CCHW_30.jpg?v=1");
	gbox.addTiles({id :'ZB_CCHW_30',image :'ZB_CCHW_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CCTJ_30","images/Equipment_icon/ZB_CCTJ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_CCTJ_30',image :'ZB_CCTJ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CCTK_30","images/Equipment_icon/ZB_CCTK_30.jpg?v=1");
	gbox.addTiles({id :'ZB_CCTK_30',image :'ZB_CCTK_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CCZX_30","images/Equipment_icon/ZB_CCZX_30.jpg?v=1");
	gbox.addTiles({id :'ZB_CCZX_30',image :'ZB_CCZX_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CGJD_20","images/Equipment_icon/ZB_CGJD_20.jpg?v=1");
	gbox.addTiles({id :'ZB_CGJD_20',image :'ZB_CGJD_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CRD_20","images/Equipment_icon/ZB_CRD_20.jpg?v=1");
	gbox.addTiles({id :'ZB_CRD_20',image :'ZB_CRD_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_CTJ_40","images/Equipment_icon/ZB_CTJ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_CTJ_40',image :'ZB_CTJ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DCBX_10","images/Equipment_icon/ZB_DCBX_10.jpg?v=1");
	gbox.addTiles({id :'ZB_DCBX_10',image :'ZB_DCBX_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DCHT_10","images/Equipment_icon/ZB_DCHT_10.jpg?v=1");
	gbox.addTiles({id :'ZB_DCHT_10',image :'ZB_DCHT_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DCSW_10","images/Equipment_icon/ZB_DCSW_10.jpg?v=1");
	gbox.addTiles({id :'ZB_DCSW_10',image :'ZB_DCSW_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DCTZ_10","images/Equipment_icon/ZB_DCTZ_10.jpg?v=1");
	gbox.addTiles({id :'ZB_DCTZ_10',image :'ZB_DCTZ_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DCXJ_10","images/Equipment_icon/ZB_DCXJ_10.jpg?v=1");
	gbox.addTiles({id :'ZB_DCXJ_10',image :'ZB_DCXJ_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DG_01","images/Equipment_icon/ZB_DG_01.jpg?v=1");
	gbox.addTiles({id :'ZB_DG_01',image :'ZB_DG_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DHHJ_50","images/Equipment_icon/ZB_DHHJ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_DHHJ_50',image :'ZB_DHHJ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DHHW_50","images/Equipment_icon/ZB_DHHW_50.jpg?v=1");
	gbox.addTiles({id :'ZB_DHHW_50',image :'ZB_DHHW_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DHTJ_50","images/Equipment_icon/ZB_DHTJ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_DHTJ_50',image :'ZB_DHTJ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DHTK_50","images/Equipment_icon/ZB_DHTK_50.jpg?v=1");
	gbox.addTiles({id :'ZB_DHTK_50',image :'ZB_DHTK_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DHZX_50","images/Equipment_icon/ZB_DHZX_50.jpg?v=1");
	gbox.addTiles({id :'ZB_DHZX_50',image :'ZB_DHZX_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXBX_20","images/Equipment_icon/ZB_DXBX_20.jpg?v=1");
	gbox.addTiles({id :'ZB_DXBX_20',image :'ZB_DXBX_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXBX_40","images/Equipment_icon/ZB_DXBX_40.jpg?v=1");
	gbox.addTiles({id :'ZB_DXBX_40',image :'ZB_DXBX_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXHT_20","images/Equipment_icon/ZB_DXHT_20.jpg?v=1");
	gbox.addTiles({id :'ZB_DXHT_20',image :'ZB_DXHT_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXHT_40","images/Equipment_icon/ZB_DXHT_40.jpg?v=1");
	gbox.addTiles({id :'ZB_DXHT_40',image :'ZB_DXHT_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXHX_20","images/Equipment_icon/ZB_DXHX_20.jpg?v=1");
	gbox.addTiles({id :'ZB_DXHX_20',image :'ZB_DXHX_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXHX_40","images/Equipment_icon/ZB_DXHX_40.jpg?v=1");
	gbox.addTiles({id :'ZB_DXHX_40',image :'ZB_DXHX_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXSW_20","images/Equipment_icon/ZB_DXSW_20.jpg?v=1");
	gbox.addTiles({id :'ZB_DXSW_20',image :'ZB_DXSW_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXSW_40","images/Equipment_icon/ZB_DXSW_40.jpg?v=1");
	gbox.addTiles({id :'ZB_DXSW_40',image :'ZB_DXSW_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXTK_20","images/Equipment_icon/ZB_DXTK_20.jpg?v=1");
	gbox.addTiles({id :'ZB_DXTK_20',image :'ZB_DXTK_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_DXTK_40","images/Equipment_icon/ZB_DXTK_40.jpg?v=1");
	gbox.addTiles({id :'ZB_DXTK_40',image :'ZB_DXTK_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_FCYDJ_60","images/Equipment_icon/ZB_FCYDJ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_FCYDJ_60',image :'ZB_FCYDJ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_GLQ_20","images/Equipment_icon/ZB_GLQ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_GLQ_20',image :'ZB_GLQ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HFBX_60","images/Equipment_icon/ZB_HFBX_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HFBX_60',image :'ZB_HFBX_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HFHT_60","images/Equipment_icon/ZB_HFHT_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HFHT_60',image :'ZB_HFHT_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HFHX_60","images/Equipment_icon/ZB_HFHX_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HFHX_60',image :'ZB_HFHX_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HFSW_60","images/Equipment_icon/ZB_HFSW_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HFSW_60',image :'ZB_HFSW_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HFTK_60","images/Equipment_icon/ZB_HFTK_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HFTK_60',image :'ZB_HFTK_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HJG_50","images/Equipment_icon/ZB_HJG_50.jpg?v=1");
	gbox.addTiles({id :'ZB_HJG_50',image :'ZB_HJG_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZG_10","images/Equipment_icon/ZB_HZG_10.jpg?v=1");
	gbox.addTiles({id :'ZB_HZG_10',image :'ZB_HZG_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZZHW_60","images/Equipment_icon/ZB_HZZHW_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HZZHW_60',image :'ZB_HZZHW_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZZTK_60","images/Equipment_icon/ZB_HZZTK_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HZZTK_60',image :'ZB_HZZTK_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZZTZ_60","images/Equipment_icon/ZB_HZZTZ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HZZTZ_60',image :'ZB_HZZTZ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZZXJ_60","images/Equipment_icon/ZB_HZZXJ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HZZXJ_60',image :'ZB_HZZXJ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_HZZZX_60","images/Equipment_icon/ZB_HZZZX_60.jpg?v=1");
	gbox.addTiles({id :'ZB_HZZZX_60',image :'ZB_HZZZX_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JDBX_30","images/Equipment_icon/ZB_JDBX_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JDBX_30',image :'ZB_JDBX_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JDHT_30","images/Equipment_icon/ZB_JDHT_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JDHT_30',image :'ZB_JDHT_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JDHX_30","images/Equipment_icon/ZB_JDHX_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JDHX_30',image :'ZB_JDHX_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JDSW_30","images/Equipment_icon/ZB_JDSW_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JDSW_30',image :'ZB_JDSW_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JDTK_30","images/Equipment_icon/ZB_JDTK_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JDTK_30',image :'ZB_JDTK_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JRHW_30","images/Equipment_icon/ZB_JRHW_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JRHW_30',image :'ZB_JRHW_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JRTK_30","images/Equipment_icon/ZB_JRTK_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JRTK_30',image :'ZB_JRTK_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JRTZ_30","images/Equipment_icon/ZB_JRTZ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JRTZ_30',image :'ZB_JRTZ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JRXJ_30","images/Equipment_icon/ZB_JRXJ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JRXJ_30',image :'ZB_JRXJ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JRZX_30","images/Equipment_icon/ZB_JRZX_30.jpg?v=1");
	gbox.addTiles({id :'ZB_JRZX_30',image :'ZB_JRZX_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXHJ_20","images/Equipment_icon/ZB_JXHJ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_JXHJ_20',image :'ZB_JXHJ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXHW_20","images/Equipment_icon/ZB_JXHW_20.jpg?v=1");
	gbox.addTiles({id :'ZB_JXHW_20',image :'ZB_JXHW_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXQ_40","images/Equipment_icon/ZB_JXQ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_JXQ_40',image :'ZB_JXQ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXTJ_20","images/Equipment_icon/ZB_JXTJ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_JXTJ_20',image :'ZB_JXTJ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXTK_20","images/Equipment_icon/ZB_JXTK_20.jpg?v=1");
	gbox.addTiles({id :'ZB_JXTK_20',image :'ZB_JXTK_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JXZX_20","images/Equipment_icon/ZB_JXZX_20.jpg?v=1");
	gbox.addTiles({id :'ZB_JXZX_20',image :'ZB_JXZX_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_JZ_40","images/Equipment_icon/ZB_JZ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_JZ_40',image :'ZB_JZ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KLZD_60","images/Equipment_icon/ZB_KLZD_60.jpg?v=1");
	gbox.addTiles({id :'ZB_KLZD_60',image :'ZB_KLZD_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KXHW_20","images/Equipment_icon/ZB_KXHW_20.jpg?v=1");
	gbox.addTiles({id :'ZB_KXHW_20',image :'ZB_KXHW_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KXTK_20","images/Equipment_icon/ZB_KXTK_20.jpg?v=1");
	gbox.addTiles({id :'ZB_KXTK_20',image :'ZB_KXTK_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KXTZ_20","images/Equipment_icon/ZB_KXTZ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_KXTZ_20',image :'ZB_KXTZ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KXXJ_20","images/Equipment_icon/ZB_KXXJ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_KXXJ_20',image :'ZB_KXXJ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_KXZX_20","images/Equipment_icon/ZB_KXZX_20.jpg?v=1");
	gbox.addTiles({id :'ZB_KXZX_20',image :'ZB_KXZX_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_LFD_30","images/Equipment_icon/ZB_LFD_30.jpg?v=1");
	gbox.addTiles({id :'ZB_LFD_30',image :'ZB_LFD_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_LLFWD_40","images/Equipment_icon/ZB_LLFWD_40.jpg?v=1");
	gbox.addTiles({id :'ZB_LLFWD_40',image :'ZB_LLFWD_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_LSJ_50","images/Equipment_icon/ZB_LSJ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_LSJ_50',image :'ZB_LSJ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_LYJ_60","images/Equipment_icon/ZB_LYJ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_LYJ_60',image :'ZB_LYJ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MBHJ_01","images/Equipment_icon/ZB_MBHJ_01.jpg?v=1");
	gbox.addTiles({id :'ZB_MBHJ_01',image :'ZB_MBHJ_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MBHT_01","images/Equipment_icon/ZB_MBHT_01.jpg?v=1");
	gbox.addTiles({id :'ZB_MBHT_01',image :'ZB_MBHT_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MBHW_01","images/Equipment_icon/ZB_MBHW_01.jpg?v=1");
	gbox.addTiles({id :'ZB_MBHW_01',image :'ZB_MBHW_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MBTK_01","images/Equipment_icon/ZB_MBTK_01.jpg?v=1");
	gbox.addTiles({id :'ZB_MBTK_01',image :'ZB_MBTK_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MBZX_01","images/Equipment_icon/ZB_MBZX_01.jpg?v=1");
	gbox.addTiles({id :'ZB_MBZX_01',image :'ZB_MBZX_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MLHW_40","images/Equipment_icon/ZB_MLHW_40.jpg?v=1");
	gbox.addTiles({id :'ZB_MLHW_40',image :'ZB_MLHW_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MLTK_40","images/Equipment_icon/ZB_MLTK_40.jpg?v=1");
	gbox.addTiles({id :'ZB_MLTK_40',image :'ZB_MLTK_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MLTZ_40","images/Equipment_icon/ZB_MLTZ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_MLTZ_40',image :'ZB_MLTZ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MLXJ_40","images/Equipment_icon/ZB_MLXJ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_MLXJ_40',image :'ZB_MLXJ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_MLZX_40","images/Equipment_icon/ZB_MLZX_40.jpg?v=1");
	gbox.addTiles({id :'ZB_MLZX_40',image :'ZB_MLZX_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_PD_01","images/Equipment_icon/ZB_PD_01.jpg?v=1");
	gbox.addTiles({id :'ZB_PD_01',image :'ZB_PD_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_PFD_40","images/Equipment_icon/ZB_PFD_40.jpg?v=1");
	gbox.addTiles({id :'ZB_PFD_40',image :'ZB_PFD_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_QGD_10","images/Equipment_icon/ZB_QGD_10.jpg?v=1");
	gbox.addTiles({id :'ZB_QGD_10',image :'ZB_QGD_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_RZHT_10","images/Equipment_icon/ZB_RZHT_10.jpg?v=1");
	gbox.addTiles({id :'ZB_RZHT_10',image :'ZB_RZHT_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_RZHW_10","images/Equipment_icon/ZB_RZHW_10.jpg?v=1");
	gbox.addTiles({id :'ZB_RZHW_10',image :'ZB_RZHW_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_RZHX_10","images/Equipment_icon/ZB_RZHX_10.jpg?v=1");
	gbox.addTiles({id :'ZB_RZHX_10',image :'ZB_RZHX_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_RZTK_10","images/Equipment_icon/ZB_RZTK_10.jpg?v=1");
	gbox.addTiles({id :'ZB_RZTK_10',image :'ZB_RZTK_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_RZZX_10","images/Equipment_icon/ZB_RZZX_10.jpg?v=1");
	gbox.addTiles({id :'ZB_RZZX_10',image :'ZB_RZZX_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_SCJ_20","images/Equipment_icon/ZB_SCJ_20.jpg?v=1");
	gbox.addTiles({id :'ZB_SCJ_20',image :'ZB_SCJ_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_SJG_20","images/Equipment_icon/ZB_SJG_20.jpg?v=1");
	gbox.addTiles({id :'ZB_SJG_20',image :'ZB_SJG_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_STQ_10","images/Equipment_icon/ZB_STQ_10.jpg?v=1");
	gbox.addTiles({id :'ZB_STQ_10',image :'ZB_STQ_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_SXG_60","images/Equipment_icon/ZB_SXG_60.jpg?v=1");
	gbox.addTiles({id :'ZB_SXG_60',image :'ZB_SXG_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_TLZHJ_60","images/Equipment_icon/ZB_TLZHJ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_TLZHJ_60',image :'ZB_TLZHJ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_TLZHW_60","images/Equipment_icon/ZB_TLZHW_60.jpg?v=1");
	gbox.addTiles({id :'ZB_TLZHW_60',image :'ZB_TLZHW_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_TLZTJ_60","images/Equipment_icon/ZB_TLZTJ_60.jpg?v=1");
	gbox.addTiles({id :'ZB_TLZTJ_60',image :'ZB_TLZTJ_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_TLZTK_60","images/Equipment_icon/ZB_TLZTK_60.jpg?v=1");
	gbox.addTiles({id :'ZB_TLZTK_60',image :'ZB_TLZTK_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_TLZZX_60","images/Equipment_icon/ZB_TLZZX_60.jpg?v=1");
	gbox.addTiles({id :'ZB_TLZZX_60',image :'ZB_TLZZX_60',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WHQ_50","images/Equipment_icon/ZB_WHQ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WHQ_50',image :'ZB_WHQ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWHJ_40","images/Equipment_icon/ZB_WWHJ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_WWHJ_40',image :'ZB_WWHJ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWHW_40","images/Equipment_icon/ZB_WWHW_40.jpg?v=1");
	gbox.addTiles({id :'ZB_WWHW_40',image :'ZB_WWHW_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWHW_50","images/Equipment_icon/ZB_WWHW_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WWHW_50',image :'ZB_WWHW_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWTJ_40","images/Equipment_icon/ZB_WWTJ_40.jpg?v=1");
	gbox.addTiles({id :'ZB_WWTJ_40',image :'ZB_WWTJ_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWTK_40","images/Equipment_icon/ZB_WWTK_40.jpg?v=1");
	gbox.addTiles({id :'ZB_WWTK_40',image :'ZB_WWTK_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWTK_50","images/Equipment_icon/ZB_WWTK_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WWTK_50',image :'ZB_WWTK_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWTZ_50","images/Equipment_icon/ZB_WWTZ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WWTZ_50',image :'ZB_WWTZ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWXJ_50","images/Equipment_icon/ZB_WWXJ_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WWXJ_50',image :'ZB_WWXJ_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWZX_40","images/Equipment_icon/ZB_WWZX_40.jpg?v=1");
	gbox.addTiles({id :'ZB_WWZX_40',image :'ZB_WWZX_40',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_WWZX_50","images/Equipment_icon/ZB_WWZX_50.jpg?v=1");
	gbox.addTiles({id :'ZB_WWZX_50',image :'ZB_WWZX_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_XJ_01","images/Equipment_icon/ZB_XJ_01.jpg?v=1");
	gbox.addTiles({id :'ZB_XJ_01',image :'ZB_XJ_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_XYG_30","images/Equipment_icon/ZB_XYG_30.jpg?v=1");
	gbox.addTiles({id :'ZB_XYG_30',image :'ZB_XYG_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLBX_50","images/Equipment_icon/ZB_YLBX_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLBX_50',image :'ZB_YLBX_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLD_50","images/Equipment_icon/ZB_YLD_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLD_50',image :'ZB_YLD_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLHT_50","images/Equipment_icon/ZB_YLHT_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLHT_50',image :'ZB_YLHT_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLHX_50","images/Equipment_icon/ZB_YLHX_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLHX_50',image :'ZB_YLHX_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLSW_50","images/Equipment_icon/ZB_YLSW_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLSW_50',image :'ZB_YLSW_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YLTK_50","images/Equipment_icon/ZB_YLTK_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YLTK_50',image :'ZB_YLTK_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YXJD_50","images/Equipment_icon/ZB_YXJD_50.jpg?v=1");
	gbox.addTiles({id :'ZB_YXJD_50',image :'ZB_YXJD_50',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZHJ_10","images/Equipment_icon/ZB_YZHJ_10.jpg?v=1");
	gbox.addTiles({id :'ZB_YZHJ_10',image :'ZB_YZHJ_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZHT_10","images/Equipment_icon/ZB_YZHT_10.jpg?v=1");
	gbox.addTiles({id :'ZB_YZHT_10',image :'ZB_YZHT_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZHW_10","images/Equipment_icon/ZB_YZHW_10.jpg?v=1");
	gbox.addTiles({id :'ZB_YZHW_10',image :'ZB_YZHW_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZJ_30","images/Equipment_icon/ZB_YZJ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_YZJ_30',image :'ZB_YZJ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZTK_10","images/Equipment_icon/ZB_YZTK_10.jpg?v=1");
	gbox.addTiles({id :'ZB_YZTK_10',image :'ZB_YZTK_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_YZZX_10","images/Equipment_icon/ZB_YZZX_10.jpg?v=1");
	gbox.addTiles({id :'ZB_YZZX_10',image :'ZB_YZZX_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ZB_ZLQ_30","images/Equipment_icon/ZB_ZLQ_30.jpg?v=1");
	gbox.addTiles({id :'ZB_ZLQ_30',image :'ZB_ZLQ_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});

};