/*
 * 练兵场
 */
var MaidanLoadImage = function()
{
	gbox.addImage("cz_zjm_33","images/Maidan/cz_zjm_33.png?v=1");
	gbox.addTiles({id :'cz_zjm_33',image :'cz_zjm_33',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cancelImage","images/Maidan/cancelImage.png?v=1");
	gbox.addTiles({id :'cancelImage',image :'cancelImage',tilew:14,tileh:14,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_btn","images/Maidan/cz_btn.png?v=1");
	gbox.addTiles({id :'cz_btn',image :'cz_btn',tilew:125,tileh:27,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_didui1","images/Maidan/cz_didui1.png?v=1");
	gbox.addTiles({id :'cz_didui1',image :'cz_didui1',tilew:95,tileh:19,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_didui2","images/Maidan/cz_didui2.png?v=1");
	gbox.addTiles({id :'cz_didui2',image :'cz_didui2',tilew:95,tileh:19,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_yewai1","images/Maidan/cz_yewai1.png?v=1");
	gbox.addTiles({id :'cz_yewai1',image :'cz_yewai1',tilew:95,tileh:19,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_yewai2","images/Maidan/cz_yewai2.png?v=1");
	gbox.addTiles({id :'cz_yewai2',image :'cz_yewai2',tilew:95,tileh:19,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_01","images/Maidan/cz_zjm_01.png?v=1");
	gbox.addTiles({id :'cz_zjm_01',image :'cz_zjm_01',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_02","images/Maidan/cz_zjm_02.png?v=1");
	gbox.addTiles({id :'cz_zjm_02',image :'cz_zjm_02',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_03","images/Maidan/cz_zjm_03.png?v=1");
	gbox.addTiles({id :'cz_zjm_03',image :'cz_zjm_03',tilew:234,tileh:27,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_04","images/Maidan/cz_zjm_04.png?v=1");
	gbox.addTiles({id :'cz_zjm_04',image :'cz_zjm_04',tilew:44,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_05","images/Maidan/cz_zjm_05.png?v=1");
	gbox.addTiles({id :'cz_zjm_05',image :'cz_zjm_05',tilew:170,tileh:86,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_06","images/Maidan/cz_zjm_06.png?v=1");
	gbox.addTiles({id :'cz_zjm_06',image :'cz_zjm_06',tilew:129,tileh:172,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_07","images/Maidan/cz_zjm_07.png?v=1");
	gbox.addTiles({id :'cz_zjm_07',image :'cz_zjm_07',tilew:130,tileh:173,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_08","images/Maidan/cz_zjm_08.png?v=1");
	gbox.addTiles({id :'cz_zjm_08',image :'cz_zjm_08',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_09","images/Maidan/cz_zjm_09.png?v=1");
	gbox.addTiles({id :'cz_zjm_09',image :'cz_zjm_09',tilew:35,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_10","images/Maidan/cz_zjm_10.png?v=1");
	gbox.addTiles({id :'cz_zjm_10',image :'cz_zjm_10',tilew:35,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_11","images/Maidan/cz_zjm_11.png?v=1");
	gbox.addTiles({id :'cz_zjm_11',image :'cz_zjm_11',tilew:76,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_12","images/Maidan/cz_zjm_12.png?v=1");
	gbox.addTiles({id :'cz_zjm_12',image :'cz_zjm_12',tilew:81,tileh:105,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_13","images/Maidan/cz_zjm_13.png?v=1");
	gbox.addTiles({id :'cz_zjm_13',image :'cz_zjm_13',tilew:457,tileh:236,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_14","images/Maidan/cz_zjm_14.png?v=1");
	gbox.addTiles({id :'cz_zjm_14',image :'cz_zjm_14',tilew:465,tileh:310,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_15","images/Maidan/cz_zjm_15.png?v=1");
	gbox.addTiles({id :'cz_zjm_15',image :'cz_zjm_15',tilew:457,tileh:236,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_16","images/Maidan/cz_zjm_16.png?v=1");
	gbox.addTiles({id :'cz_zjm_16',image :'cz_zjm_16',tilew:75,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_17","images/Maidan/cz_zjm_17.png?v=1");
	gbox.addTiles({id :'cz_zjm_17',image :'cz_zjm_17',tilew:74,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_18","images/Maidan/cz_zjm_18.png?v=1");
	gbox.addTiles({id :'cz_zjm_18',image :'cz_zjm_18',tilew:36,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_21","images/Maidan/cz_zjm_21.png?v=1");
	gbox.addTiles({id :'cz_zjm_21',image :'cz_zjm_21',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_22","images/Maidan/cz_zjm_22.png?v=1");
	gbox.addTiles({id :'cz_zjm_22',image :'cz_zjm_22',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_23","images/Maidan/cz_zjm_23.png?v=1");
	gbox.addTiles({id :'cz_zjm_23',image :'cz_zjm_23',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_24","images/Maidan/cz_zjm_24.png?v=1");
	gbox.addTiles({id :'cz_zjm_24',image :'cz_zjm_24',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cz_zjm_32","images/Maidan/cz_zjm_32.png?v=1");
	gbox.addTiles({id :'cz_zjm_32',image :'cz_zjm_32',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("pb_zj_08","images/Maidan/pb_zj_08.png?v=1");
	gbox.addTiles({id :'pb_zj_08',image :'pb_zj_08',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("peibingBG","images/Maidan/peibingBG.png?v=1");
	gbox.addTiles({id :'peibingBG',image :'peibingBG',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("selectBg","images/Maidan/selectBg.png?v=1");
	gbox.addTiles({id :'selectBg',image :'selectBg',tilew:18,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
};