var mainInterfaceLoadImage = function()
{
	gbox.addImage("bubing","images/The_main_interface/bubing.png?v=1");
	gbox.addTiles({id :'bubing',image :'bubing',tilew:821,tileh:267,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("building","images/The_main_interface/building.png?v=1");
	gbox.addTiles({id :'building',image :'building',tilew:314,tileh:236,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_01","images/The_main_interface/by_01.jpg?v=1");
	gbox.addTiles({id :'by_01',image :'by_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_02","images/The_main_interface/by_02.jpg?v=1");
	gbox.addTiles({id :'by_02',image :'by_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("by_03","images/The_main_interface/by_03.jpg?v=1");
	gbox.addTiles({id :'by_03',image :'by_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("cityLevel","images/The_main_interface/cityLevel.png?v=1");
	gbox.addTiles({id :'cityLevel',image :'cityLevel',tilew:451,tileh:74,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_01","images/The_main_interface/dj_01.jpg?v=1");
	gbox.addTiles({id :'dj_01',image :'dj_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_02","images/The_main_interface/dj_02.jpg?v=1");
	gbox.addTiles({id :'dj_02',image :'dj_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dj_03","images/The_main_interface/dj_03.jpg?v=1");
	gbox.addTiles({id :'dj_03',image :'dj_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("farmer","images/The_main_interface/farmer.png?v=1");
	gbox.addTiles({id :'farmer',image :'farmer',tilew:1149,tileh:369,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("girl","images/The_main_interface/girl.png?v=1");
	gbox.addTiles({id :'girl',image :'girl',tilew:487,tileh:175,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_01","images/The_main_interface/gk_01.jpg?v=1");
	gbox.addTiles({id :'gk_01',image :'gk_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_02","images/The_main_interface/gk_02.jpg?v=1");
	gbox.addTiles({id :'gk_02',image :'gk_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("gk_03","images/The_main_interface/gk_03.jpg?v=1");
	gbox.addTiles({id :'gk_03',image :'gk_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_01","images/The_main_interface/jf_01.jpg?v=1");
	gbox.addTiles({id :'jf_01',image :'jf_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_02","images/The_main_interface/jf_02.jpg?v=1");
	gbox.addTiles({id :'jf_02',image :'jf_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jf_03","images/The_main_interface/jf_03.jpg?v=1");
	gbox.addTiles({id :'jf_03',image :'jf_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_01","images/The_main_interface/jgf_01.jpg?v=1");
	gbox.addTiles({id :'jgf_01',image :'jgf_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_02","images/The_main_interface/jgf_02.jpg?v=1");
	gbox.addTiles({id :'jgf_02',image :'jgf_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_03","images/The_main_interface/jgf_03.jpg?v=1");
	gbox.addTiles({id :'jgf_03',image :'jgf_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_01","images/The_main_interface/jg_01.jpg?v=1");
	gbox.addTiles({id :'jg_01',image :'jg_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_02","images/The_main_interface/jg_02.jpg?v=1");
	gbox.addTiles({id :'jg_02',image :'jg_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jg_03","images/The_main_interface/jg_03.jpg?v=1");
	gbox.addTiles({id :'jg_03',image :'jg_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_01","images/The_main_interface/jjc_01.jpg?v=1");
	gbox.addTiles({id :'jjc_01',image :'jjc_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_02","images/The_main_interface/jjc_02.jpg?v=1");
	gbox.addTiles({id :'jjc_02',image :'jjc_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jjc_03","images/The_main_interface/jjc_03.jpg?v=1");
	gbox.addTiles({id :'jjc_03',image :'jjc_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_01","images/The_main_interface/js_01.jpg?v=1");
	gbox.addTiles({id :'js_01',image :'js_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_02","images/The_main_interface/js_02.jpg?v=1");
	gbox.addTiles({id :'js_02',image :'js_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("js_03","images/The_main_interface/js_03.jpg?v=1");
	gbox.addTiles({id :'js_03',image :'js_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_01","images/The_main_interface/jxg_01.jpg?v=1");
	gbox.addTiles({id :'jxg_01',image :'jxg_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_02","images/The_main_interface/jxg_02.jpg?v=1");
	gbox.addTiles({id :'jxg_02',image :'jxg_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jxg_03","images/The_main_interface/jxg_03.jpg?v=1");
	gbox.addTiles({id :'jxg_03',image :'jxg_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jzs_zjm_01","images/The_main_interface/jzs_zjm_01.png?v=1");
	gbox.addTiles({id :'jzs_zjm_01',image :'jzs_zjm_01',tilew:808,tileh:497,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jzs_zjm_02","images/The_main_interface/jzs_zjm_02.png?v=1");
	gbox.addTiles({id :'jzs_zjm_02',image :'jzs_zjm_02',tilew:808,tileh:488,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jzs_zjm_03","images/The_main_interface/jzs_zjm_03.png?v=1");
	gbox.addTiles({id :'jzs_zjm_03',image :'jzs_zjm_03',tilew:324,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jzs_zjm_04","images/The_main_interface/jzs_zjm_04.png?v=1");
	gbox.addTiles({id :'jzs_zjm_04',image :'jzs_zjm_04',tilew:73,tileh:73,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_01","images/The_main_interface/kjg_01.jpg?v=1");
	gbox.addTiles({id :'kjg_01',image :'kjg_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_02","images/The_main_interface/kjg_02.jpg?v=1");
	gbox.addTiles({id :'kjg_02',image :'kjg_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_03","images/The_main_interface/kjg_03.jpg?v=1");
	gbox.addTiles({id :'kjg_03',image :'kjg_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_01","images/The_main_interface/lbc_01.jpg?v=1");
	gbox.addTiles({id :'lbc_01',image :'lbc_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_02","images/The_main_interface/lbc_02.jpg?v=1");
	gbox.addTiles({id :'lbc_02',image :'lbc_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("lbc_03","images/The_main_interface/lbc_03.jpg?v=1");
	gbox.addTiles({id :'lbc_03',image :'lbc_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("man_right","images/The_main_interface/man_right.png?v=1");
	gbox.addTiles({id :'man_right',image :'man_right',tilew:336,tileh:43,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_01","images/The_main_interface/mj_01.jpg?v=1");
	gbox.addTiles({id :'mj_01',image :'mj_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_02","images/The_main_interface/mj_02.jpg?v=1");
	gbox.addTiles({id :'mj_02',image :'mj_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_03","images/The_main_interface/mj_03.jpg?v=1");
	gbox.addTiles({id :'mj_03',image :'mj_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shinv","images/The_main_interface/shinv.png?v=1");
	gbox.addTiles({id :'shinv',image :'shinv',tilew:666,tileh:243,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_01","images/The_main_interface/tys_01.jpg?v=1");
	gbox.addTiles({id :'tys_01',image :'tys_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_02","images/The_main_interface/tys_02.jpg?v=1");
	gbox.addTiles({id :'tys_02',image :'tys_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("tys_03","images/The_main_interface/tys_03.jpg?v=1");
	gbox.addTiles({id :'tys_03',image :'tys_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_01","images/The_main_interface/wwg_01.jpg?v=1");
	gbox.addTiles({id :'wwg_01',image :'wwg_01',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_02","images/The_main_interface/wwg_02.jpg?v=1");
	gbox.addTiles({id :'wwg_02',image :'wwg_02',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wwg_03","images/The_main_interface/wwg_03.jpg?v=1");
	gbox.addTiles({id :'wwg_03',image :'wwg_03',tilew:62,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_18","images/The_main_interface/zjm_18.png?v=1");
	gbox.addTiles({id :'zjm_18',image :'zjm_18',tilew:24,tileh:202,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_35","images/The_main_interface/zjm_35.png?v=1");
	gbox.addTiles({id :'zjm_35',image :'zjm_35',tilew:72,tileh:22,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_36","images/The_main_interface/zjm_36.png?v=1");
	gbox.addTiles({id :'zjm_36',image :'zjm_36',tilew:50,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_37","images/The_main_interface/zjm_37.png?v=1");
	gbox.addTiles({id :'zjm_37',image :'zjm_37',tilew:50,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_39","images/The_main_interface/zjm_39.png?v=1");
	gbox.addTiles({id :'zjm_39',image :'zjm_39',tilew:50,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_43","images/The_main_interface/zjm_43.png?v=1");
	gbox.addTiles({id :'zjm_43',image :'zjm_43',tilew:20,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_44","images/The_main_interface/zjm_44.png?v=1");
	gbox.addTiles({id :'zjm_44',image :'zjm_44',tilew:20,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_45","images/The_main_interface/zjm_45.png?v=1");
	gbox.addTiles({id :'zjm_45',image :'zjm_45',tilew:20,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_46","images/The_main_interface/zjm_46.png?v=1");
	gbox.addTiles({id :'zjm_46',image :'zjm_46',tilew:20,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_47","images/The_main_interface/zjm_47.png?v=1");
	gbox.addTiles({id :'zjm_47',image :'zjm_47',tilew:20,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_48","images/The_main_interface/zjm_48.png?v=1");
	gbox.addTiles({id :'zjm_48',image :'zjm_48',tilew:49,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_49","images/The_main_interface/zjm_49.png?v=1");
	gbox.addTiles({id :'zjm_49',image :'zjm_49',tilew:49,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_50","images/The_main_interface/zjm_50.png?v=1");
	gbox.addTiles({id :'zjm_50',image :'zjm_50',tilew:49,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_bj","images/The_main_interface/zjm_an_bj.png?v=1");
	gbox.addTiles({id :'zjm_an_bj',image :'zjm_an_bj',tilew:551,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_cssj","images/The_main_interface/zjm_an_cssj.png?v=1");
	gbox.addTiles({id :'zjm_an_cssj',image :'zjm_an_cssj',tilew:104,tileh:62,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_gk_d","images/The_main_interface/zjm_an_gk_d.png?v=1");
	gbox.addTiles({id :'zjm_an_gk_d',image :'zjm_an_gk_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_gk_x","images/The_main_interface/zjm_an_gk_x.png?v=1");
	gbox.addTiles({id :'zjm_an_gk_x',image :'zjm_an_gk_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_jq_d","images/The_main_interface/zjm_an_jq_d.png?v=1");
	gbox.addTiles({id :'zjm_an_jq_d',image :'zjm_an_jq_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_jq_x","images/The_main_interface/zjm_an_jq_x.png?v=1");
	gbox.addTiles({id :'zjm_an_jq_x',image :'zjm_an_jq_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_jz","images/The_main_interface/zjm_an_jz.png?v=1");
	gbox.addTiles({id :'zjm_an_jz',image :'zjm_an_jz',tilew:21,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_jz_01","images/The_main_interface/zjm_an_jz_01.png?v=1");
	gbox.addTiles({id :'zjm_an_jz_01',image :'zjm_an_jz_01',tilew:21,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_px_d","images/The_main_interface/zjm_an_px_d.png?v=1");
	gbox.addTiles({id :'zjm_an_px_d',image :'zjm_an_px_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_px_x","images/The_main_interface/zjm_an_px_x.png?v=1");
	gbox.addTiles({id :'zjm_an_px_x',image :'zjm_an_px_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_rw_d","images/The_main_interface/zjm_an_rw_d.png?v=1");
	gbox.addTiles({id :'zjm_an_rw_d',image :'zjm_an_rw_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_rw_x","images/The_main_interface/zjm_an_rw_x.png?v=1");
	gbox.addTiles({id :'zjm_an_rw_x',image :'zjm_an_rw_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sj_1","images/The_main_interface/zjm_an_sj_1.png?v=1");
	gbox.addTiles({id :'zjm_an_sj_1',image :'zjm_an_sj_1',tilew:80,tileh:98,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sj_3","images/The_main_interface/zjm_an_sj_3.png?v=1");
	gbox.addTiles({id :'zjm_an_sj_3',image :'zjm_an_sj_3',tilew:72,tileh:22,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sj_d","images/The_main_interface/zjm_an_sj_d.png?v=1");
	gbox.addTiles({id :'zjm_an_sj_d',image :'zjm_an_sj_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sj_x","images/The_main_interface/zjm_an_sj_x.png?v=1");
	gbox.addTiles({id :'zjm_an_sj_x',image :'zjm_an_sj_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sz_d","images/The_main_interface/zjm_an_sz_d.png?v=1");
	gbox.addTiles({id :'zjm_an_sz_d',image :'zjm_an_sz_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_sz_x","images/The_main_interface/zjm_an_sz_x.png?v=1");
	gbox.addTiles({id :'zjm_an_sz_x',image :'zjm_an_sz_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_wj_d","images/The_main_interface/zjm_an_wj_d.png?v=1");
	gbox.addTiles({id :'zjm_an_wj_d',image :'zjm_an_wj_d',tilew:62,tileh:78,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_wj_x","images/The_main_interface/zjm_an_wj_x.png?v=1");
	gbox.addTiles({id :'zjm_an_wj_x',image :'zjm_an_wj_x',tilew:55,tileh:65,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_zy","images/The_main_interface/zjm_an_zy.png?v=1");
	gbox.addTiles({id :'zjm_an_zy',image :'zjm_an_zy',tilew:21,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_an_zy_01","images/The_main_interface/zjm_an_zy_01.png?v=1");
	gbox.addTiles({id :'zjm_an_zy_01',image :'zjm_an_zy_01',tilew:21,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_frd_1","images/The_main_interface/zjm_frd_1.png?v=1");
	gbox.addTiles({id :'zjm_frd_1',image :'zjm_frd_1',tilew:432,tileh:6,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jyt_2","images/The_main_interface/zjm_jyt_2.png?v=1");
	gbox.addTiles({id :'zjm_jyt_2',image :'zjm_jyt_2',tilew:431,tileh:6,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jyt_3","images/The_main_interface/zjm_jyt_3.png?v=1");
	gbox.addTiles({id :'zjm_jyt_3',image :'zjm_jyt_3',tilew:431,tileh:6,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jztx_1","images/The_main_interface/zjm_jztx_1.png?v=1");
	gbox.addTiles({id :'zjm_jztx_1',image :'zjm_jztx_1',tilew:292,tileh:127,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jztx_2","images/The_main_interface/zjm_jztx_2.png?v=1");
	gbox.addTiles({id :'zjm_jztx_2',image :'zjm_jztx_2',tilew:81,tileh:31,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jztx_3","images/The_main_interface/zjm_jztx_3.png?v=1");
	gbox.addTiles({id :'zjm_jztx_3',image :'zjm_jztx_3',tilew:81,tileh:31,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_jztx_4","images/The_main_interface/zjm_jztx_4.png?v=1");
	gbox.addTiles({id :'zjm_jztx_4',image :'zjm_jztx_4',tilew:81,tileh:31,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_zy01_ls","images/The_main_interface/zjm_zy01_ls.png?v=1");
	gbox.addTiles({id :'zjm_zy01_ls',image :'zjm_zy01_ls',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_zy02_ml","images/The_main_interface/zjm_zy02_ml.png?v=1");
	gbox.addTiles({id :'zjm_zy02_ml',image :'zjm_zy02_ml',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_zy03_sc","images/The_main_interface/zjm_zy03_sc.png?v=1");
	gbox.addTiles({id :'zjm_zy03_sc',image :'zjm_zy03_sc',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_zy04_tk","images/The_main_interface/zjm_zy04_tk.png?v=1");
	gbox.addTiles({id :'zjm_zy04_tk',image :'zjm_zy04_tk',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_zy05_tb","images/The_main_interface/zjm_zy05_tb.png?v=1");
	gbox.addTiles({id :'zjm_zy05_tb',image :'zjm_zy05_tb',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
};