var ProcessingSquareAvatarLoadImage = function()
{
	gbox.addImage("dazao","images/Processing_Square/dazao.png?v=1");
	gbox.addTiles({id :'dazao',image :'dazao',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dz_button1","images/Processing_Square/dz_button1.png?v=1");
	gbox.addTiles({id :'dz_button1',image :'dz_button1',tilew:26,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("dz_button2","images/Processing_Square/dz_button2.png?v=1");
	gbox.addTiles({id :'dz_button2',image :'dz_button2',tilew:26,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("hc_equipCombiningFont","images/Processing_Square/hc_equipCombiningFont.png?v=1");
	gbox.addTiles({id :'hc_equipCombiningFont',image :'hc_equipCombiningFont',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("hc_inlayFont","images/Processing_Square/hc_inlayFont.png?v=1");
	gbox.addTiles({id :'hc_inlayFont',image :'hc_inlayFont',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("hc_popupMenu","images/Processing_Square/hc_popupMenu.png?v=1");
	gbox.addTiles({id :'hc_popupMenu',image :'hc_popupMenu',tilew:84,tileh:101,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("hecheng","images/Processing_Square/hecheng.png?v=1");
	gbox.addTiles({id :'hecheng',image :'hecheng',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_0","images/Processing_Square/jgf_zjm_0.png?v=1");
	gbox.addTiles({id :'jgf_zjm_0',image :'jgf_zjm_0',tilew:278,tileh:200,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_01","images/Processing_Square/jgf_zjm_01.png?v=1");
	gbox.addTiles({id :'jgf_zjm_01',image :'jgf_zjm_01',tilew:748,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_09","images/Processing_Square/jgf_zjm_09.png?v=1");
	gbox.addTiles({id :'jgf_zjm_09',image :'jgf_zjm_09',tilew:748,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_1","images/Processing_Square/jgf_zjm_1.png?v=1");
	gbox.addTiles({id :'jgf_zjm_1',image :'jgf_zjm_1',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_10","images/Processing_Square/jgf_zjm_10.png?v=1");
	gbox.addTiles({id :'jgf_zjm_10',image :'jgf_zjm_10',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_17","images/Processing_Square/jgf_zjm_17.png?v=1");
	gbox.addTiles({id :'jgf_zjm_17',image :'jgf_zjm_17',tilew:292,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_18","images/Processing_Square/jgf_zjm_18.png?v=1");
	gbox.addTiles({id :'jgf_zjm_18',image :'jgf_zjm_18',tilew:292,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_19","images/Processing_Square/jgf_zjm_19.png?v=1");
	gbox.addTiles({id :'jgf_zjm_19',image :'jgf_zjm_19',tilew:292,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_2","images/Processing_Square/jgf_zjm_2.png?v=1");
	gbox.addTiles({id :'jgf_zjm_2',image :'jgf_zjm_2',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("blueStone","images/Processing_Square/jgf_zjm_20.png?v=1");
	gbox.addTiles({id :'blueStone',image :'blueStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("violetStone","images/Processing_Square/jgf_zjm_21.png?v=1");
	gbox.addTiles({id :'violetStone',image :'violetStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("brownStone","images/Processing_Square/jgf_zjm_22.png?v=1");
	gbox.addTiles({id :'brownStone',image :'brownStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("redStone","images/Processing_Square/jgf_zjm_23.png?v=1");
	gbox.addTiles({id :'redStone',image :'redStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("greenStone","images/Processing_Square/jgf_zjm_24.png?v=1");
	gbox.addTiles({id :'greenStone',image :'greenStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("yellowStone","images/Processing_Square/jgf_zjm_25.png?v=1");
	gbox.addTiles({id :'yellowStone',image :'yellowStone',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_30","images/Processing_Square/jgf_zjm_30.png?v=1");
	gbox.addTiles({id :'jgf_zjm_30',image :'jgf_zjm_30',tilew:805,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_31","images/Processing_Square/jgf_zjm_31.png?v=1");
	gbox.addTiles({id :'jgf_zjm_31',image :'jgf_zjm_31',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_34","images/Processing_Square/jgf_zjm_34.png?v=1");
	gbox.addTiles({id :'jgf_zjm_34',image :'jgf_zjm_34',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_35","images/Processing_Square/jgf_zjm_35.png?v=1");
	gbox.addTiles({id :'jgf_zjm_35',image :'jgf_zjm_35',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_48","images/Processing_Square/jgf_zjm_48.png?v=1");
	gbox.addTiles({id :'jgf_zjm_48',image :'jgf_zjm_48',tilew:40,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_50","images/Processing_Square/jgf_zjm_50.png?v=1");
	gbox.addTiles({id :'jgf_zjm_50',image :'jgf_zjm_50',tilew:40,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jglight","images/Processing_Square/jglight.png?v=1");
	gbox.addTiles({id :'jglight',image :'jglight',tilew:84,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jiagongFang","images/Processing_Square/jiagongFang.jpg?v=1");
	gbox.addTiles({id :'jiagongFang',image :'jiagongFang',tilew:1440,tileh:742,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("man","images/Processing_Square/man.png?v=1");
	gbox.addTiles({id :'man',image :'man',tilew:74,tileh:136,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("manAction","images/Processing_Square/manAction.png?v=1");
	gbox.addTiles({id :'manAction',image :'manAction',tilew:648,tileh:612,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("no_baoshi","images/Processing_Square/no_baoshi.png?v=1");
	gbox.addTiles({id :'no_baoshi',image :'no_baoshi',tilew:18,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("qianghua","images/Processing_Square/qianghua.png?v=1");
	gbox.addTiles({id :'qianghua',image :'qianghua',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_120","images/Processing_Square/ty_an_120.png?v=1");
	gbox.addTiles({id :'ty_an_120',image :'ty_an_120',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xiangqian","images/Processing_Square/xiangqian.png?v=1");
	gbox.addTiles({id :'xiangqian',image :'xiangqian',tilew:62,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("xiangqian_button1","images/Processing_Square/xiangqian_button1.png?v=1");
	gbox.addTiles({id :'xiangqian_button1',image :'xiangqian_button1',tilew:61,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("no_baoshi","images/Processing_Square/no_baoshi.png?v=1");
	gbox.addTiles({id :'no_baoshi',image :'no_baoshi',tilew:61,tileh:26,tilerow : 18,gapx : 20,gapy : 0});
	
};