var propsIconLoadImage = function()
{
	gbox.addImage("DJ_AJLH","images/Props_icon/DJ_AJLH.jpg?v=1");
	gbox.addTiles({id :'DJ_AJLH',image :'DJ_AJLH',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_BYDS","images/Props_icon/DJ_BYDS.jpg?v=1");
	gbox.addTiles({id :'DJ_BYDS',image :'DJ_BYDS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_BYXT","images/Props_icon/DJ_BYXT.jpg?v=1");
	gbox.addTiles({id :'DJ_BYXT',image :'DJ_BYXT',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_BYZS","images/Props_icon/DJ_BYZS.jpg?v=1");
	gbox.addTiles({id :'DJ_BYZS',image :'DJ_BYZS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_CS","images/Props_icon/DJ_CS.jpg?v=1");
	gbox.addTiles({id :'DJ_CS',image :'DJ_CS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_FLQ_1","images/Props_icon/DJ_FLQ_1.jpg?v=1");
	gbox.addTiles({id :'DJ_FLQ_1',image :'DJ_FLQ_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_FLQ_2","images/Props_icon/DJ_FLQ_2.jpg?v=1");
	gbox.addTiles({id :'DJ_FLQ_2',image :'DJ_FLQ_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_FLQ_3","images/Props_icon/DJ_FLQ_3.jpg?v=1");
	gbox.addTiles({id :'DJ_FLQ_3',image :'DJ_FLQ_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_GF_1","images/Props_icon/DJ_GF_1.jpg?v=1");
	gbox.addTiles({id :'DJ_GF_1',image :'DJ_GF_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_GF_2","images/Props_icon/DJ_GF_2.jpg?v=1");
	gbox.addTiles({id :'DJ_GF_2',image :'DJ_GF_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_GF_3","images/Props_icon/DJ_GF_3.jpg?v=1");
	gbox.addTiles({id :'DJ_GF_3',image :'DJ_GF_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_GF_4","images/Props_icon/DJ_GF_4.jpg?v=1");
	gbox.addTiles({id :'DJ_GF_4',image :'DJ_GF_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_GF_5","images/Props_icon/DJ_GF_5.jpg?v=1");
	gbox.addTiles({id :'DJ_GF_5',image :'DJ_GF_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_HJZM","images/Props_icon/DJ_HJZM.jpg?v=1");
	gbox.addTiles({id :'DJ_HJZM',image :'DJ_HJZM',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JCJ","images/Props_icon/DJ_JCJ.jpg?v=1");
	gbox.addTiles({id :'DJ_JCJ',image :'DJ_JCJ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JGJZ","images/Props_icon/DJ_JGJZ.jpg?v=1");
	gbox.addTiles({id :'DJ_JGJZ',image :'DJ_JGJZ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JNS","images/Props_icon/DJ_JNS.jpg?v=1");
	gbox.addTiles({id :'DJ_JNS',image :'DJ_JNS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JSJ","images/Props_icon/DJ_JSJ.jpg?v=1");
	gbox.addTiles({id :'DJ_JSJ',image :'DJ_JSJ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JXJ","images/Props_icon/DJ_JXJ.jpg?v=1");
	gbox.addTiles({id :'DJ_JXJ',image :'DJ_JXJ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JYS_1","images/Props_icon/DJ_JYS_1.jpg?v=1");
	gbox.addTiles({id :'DJ_JYS_1',image :'DJ_JYS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JYS_2","images/Props_icon/DJ_JYS_2.jpg?v=1");
	gbox.addTiles({id :'DJ_JYS_2',image :'DJ_JYS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_JYS_3","images/Props_icon/DJ_JYS_3.jpg?v=1");
	gbox.addTiles({id :'DJ_JYS_3',image :'DJ_JYS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_KJL_1","images/Props_icon/DJ_KJL_1.jpg?v=1");
	gbox.addTiles({id :'DJ_KJL_1',image :'DJ_KJL_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_KJL_2","images/Props_icon/DJ_KJL_2.jpg?v=1");
	gbox.addTiles({id :'DJ_KJL_2',image :'DJ_KJL_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_1","images/Props_icon/DJ_LB_1.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_1',image :'DJ_LB_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_2","images/Props_icon/DJ_LB_2.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_2',image :'DJ_LB_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_3","images/Props_icon/DJ_LB_3.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_3',image :'DJ_LB_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_4","images/Props_icon/DJ_LB_4.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_4',image :'DJ_LB_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_5","images/Props_icon/DJ_LB_5.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_5',image :'DJ_LB_5',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LB_6","images/Props_icon/DJ_LB_6.jpg?v=1");
	gbox.addTiles({id :'DJ_LB_6',image :'DJ_LB_6',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LDZM","images/Props_icon/DJ_LDZM.jpg?v=1");
	gbox.addTiles({id :'DJ_LDZM',image :'DJ_LDZM',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LS_1","images/Props_icon/DJ_LS_1.jpg?v=1");
	gbox.addTiles({id :'DJ_LS_1',image :'DJ_LS_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LS_2","images/Props_icon/DJ_LS_2.jpg?v=1");
	gbox.addTiles({id :'DJ_LS_2',image :'DJ_LS_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LS_3","images/Props_icon/DJ_LS_3.png?v=1");
	gbox.addTiles({id :'DJ_LS_3',image :'DJ_LS_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_LS_4","images/Props_icon/DJ_LS_4.png?v=1");
	gbox.addTiles({id :'DJ_LS_4',image :'DJ_LS_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MBL_1","images/Props_icon/DJ_MBL_1.jpg?v=1");
	gbox.addTiles({id :'DJ_MBL_1',image :'DJ_MBL_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MBL_2","images/Props_icon/DJ_MBL_2.jpg?v=1");
	gbox.addTiles({id :'DJ_MBL_2',image :'DJ_MBL_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MBL_3","images/Props_icon/DJ_MBL_3.jpg?v=1");
	gbox.addTiles({id :'DJ_MBL_3',image :'DJ_MBL_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MC_1","images/Props_icon/DJ_MC_1.jpg?v=1");
	gbox.addTiles({id :'DJ_MC_1',image :'DJ_MC_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MC_2","images/Props_icon/DJ_MC_2.jpg?v=1");
	gbox.addTiles({id :'DJ_MC_2',image :'DJ_MC_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MC_3","images/Props_icon/DJ_MC_3.jpg?v=1");
	gbox.addTiles({id :'DJ_MC_3',image :'DJ_MC_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MC_4","images/Props_icon/DJ_MC_4.jpg?v=1");
	gbox.addTiles({id :'DJ_MC_4',image :'DJ_MC_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MSK_1","images/Props_icon/DJ_MSK_1.jpg?v=1");
	gbox.addTiles({id :'DJ_MSK_1',image :'DJ_MSK_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MSK_2","images/Props_icon/DJ_MSK_2.jpg?v=1");
	gbox.addTiles({id :'DJ_MSK_2',image :'DJ_MSK_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_MSK_3","images/Props_icon/DJ_MSK_3.jpg?v=1");
	gbox.addTiles({id :'DJ_MSK_3',image :'DJ_MSK_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_PGJZ","images/Props_icon/DJ_PGJZ.jpg?v=1");
	gbox.addTiles({id :'DJ_PGJZ',image :'DJ_PGJZ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_QHZ_B","images/Props_icon/DJ_QHZ_B.jpg?v=1");
	gbox.addTiles({id :'DJ_QHZ_B',image :'DJ_QHZ_B',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_QHZ_G","images/Props_icon/DJ_QHZ_G.jpg?v=1");
	gbox.addTiles({id :'DJ_QHZ_G',image :'DJ_QHZ_G',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_QHZ_L","images/Props_icon/DJ_QHZ_L.jpg?v=1");
	gbox.addTiles({id :'DJ_QHZ_L',image :'DJ_QHZ_L',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_QHZ_Z","images/Props_icon/DJ_QHZ_Z.jpg?v=1");
	gbox.addTiles({id :'DJ_QHZ_Z',image :'DJ_QHZ_Z',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_RCK","images/Props_icon/DJ_RCK.jpg?v=1");
	gbox.addTiles({id :'DJ_RCK',image :'DJ_RCK',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SEJL","images/Props_icon/DJ_SEJL.jpg?v=1");
	gbox.addTiles({id :'DJ_SEJL',image :'DJ_SEJL',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SGJZ","images/Props_icon/DJ_SGJZ.jpg?v=1");
	gbox.addTiles({id :'DJ_SGJZ',image :'DJ_SGJZ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SL","images/Props_icon/DJ_SL.jpg?v=1");
	gbox.addTiles({id :'DJ_SL',image :'DJ_SL',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SL_1","images/Props_icon/DJ_SL_1.jpg?v=1");
	gbox.addTiles({id :'DJ_SL_1',image :'DJ_SL_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SL_2","images/Props_icon/DJ_SL_2.jpg?v=1");
	gbox.addTiles({id :'DJ_SL_2',image :'DJ_SL_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SL_3","images/Props_icon/DJ_SL_3.jpg?v=1");
	gbox.addTiles({id :'DJ_SL_3',image :'DJ_SL_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_SL_4","images/Props_icon/DJ_SL_4.jpg?v=1");
	gbox.addTiles({id :'DJ_SL_4',image :'DJ_SL_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TB_1","images/Props_icon/DJ_TB_1.jpg?v=1");
	gbox.addTiles({id :'DJ_TB_1',image :'DJ_TB_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TB_2","images/Props_icon/DJ_TB_2.jpg?v=1");
	gbox.addTiles({id :'DJ_TB_2',image :'DJ_TB_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TB_3","images/Props_icon/DJ_TB_3.jpg?v=1");
	gbox.addTiles({id :'DJ_TB_3',image :'DJ_TB_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TB_4","images/Props_icon/DJ_TB_4.jpg?v=1");
	gbox.addTiles({id :'DJ_TB_4',image :'DJ_TB_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TD_1","images/Props_icon/DJ_TD_1.jpg?v=1");
	gbox.addTiles({id :'DJ_TD_1',image :'DJ_TD_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TD_2","images/Props_icon/DJ_TD_2.jpg?v=1");
	gbox.addTiles({id :'DJ_TD_2',image :'DJ_TD_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TD_3","images/Props_icon/DJ_TD_3.jpg?v=1");
	gbox.addTiles({id :'DJ_TD_3',image :'DJ_TD_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TD_4","images/Props_icon/DJ_TD_4.jpg?v=1");
	gbox.addTiles({id :'DJ_TD_4',image :'DJ_TD_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TZP_1","images/Props_icon/DJ_TZP_1.jpg?v=1");
	gbox.addTiles({id :'DJ_TZP_1',image :'DJ_TZP_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TZP_2","images/Props_icon/DJ_TZP_2.jpg?v=1");
	gbox.addTiles({id :'DJ_TZP_2',image :'DJ_TZP_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_TZP_3","images/Props_icon/DJ_TZP_3.jpg?v=1");
	gbox.addTiles({id :'DJ_TZP_3',image :'DJ_TZP_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_WJSXK","images/Props_icon/DJ_WJSXK.jpg?v=1");
	gbox.addTiles({id :'DJ_WJSXK',image :'DJ_WJSXK',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_XSK","images/Props_icon/DJ_XSK.jpg?v=1");
	gbox.addTiles({id :'DJ_XSK',image :'DJ_XSK',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_YG","images/Props_icon/DJ_YG.jpg?v=1");
	gbox.addTiles({id :'DJ_YG',image :'DJ_YG',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_YGJZ","images/Props_icon/DJ_YGJZ.jpg?v=1");
	gbox.addTiles({id :'DJ_YGJZ',image :'DJ_YGJZ',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_YMS","images/Props_icon/DJ_YMS.jpg?v=1");
	gbox.addTiles({id :'DJ_YMS',image :'DJ_YMS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_YRD","images/Props_icon/DJ_YRD.jpg?v=1");
	gbox.addTiles({id :'DJ_YRD',image :'DJ_YRD',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZCL","images/Props_icon/DJ_ZCL.jpg?v=1");
	gbox.addTiles({id :'DJ_ZCL',image :'DJ_ZCL',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZDK_1","images/Props_icon/DJ_ZDK_1.jpg?v=1");
	gbox.addTiles({id :'DJ_ZDK_1',image :'DJ_ZDK_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZDK_2","images/Props_icon/DJ_ZDK_2.jpg?v=1");
	gbox.addTiles({id :'DJ_ZDK_2',image :'DJ_ZDK_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZDK_3","images/Props_icon/DJ_ZDK_3.jpg?v=1");
	gbox.addTiles({id :'DJ_ZDK_3',image :'DJ_ZDK_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZML","images/Props_icon/DJ_ZML.jpg?v=1");
	gbox.addTiles({id :'DJ_ZML',image :'DJ_ZML',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZQ_CB","images/Props_icon/DJ_ZQ_CB.jpg?v=1");
	gbox.addTiles({id :'DJ_ZQ_CB',image :'DJ_ZQ_CB',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZQ_CS","images/Props_icon/DJ_ZQ_CS.jpg?v=1");
	gbox.addTiles({id :'DJ_ZQ_CS',image :'DJ_ZQ_CS',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("DJ_ZQ_GW","images/Props_icon/DJ_ZQ_GW.jpg?v=1");
	gbox.addTiles({id :'DJ_ZQ_GW',image :'DJ_ZQ_GW',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	

};