/*
 * 科教馆
 */
var scienceEcLoadImage = function()
{
	gbox.addImage("kjg_zjm_42","images/ScienceEC/kjg_zjm_42.jpg?v=1");
	gbox.addTiles({id :'kjg_zjm_42',image :'kjg_zjm_42',tilew:490,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_01","images/ScienceEC/bz_kj_01.jpg?v=1");
	gbox.addTiles({id :'bz_kj_01',image :'bz_kj_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_02","images/ScienceEC/bz_kj_02.jpg?v=1");
	gbox.addTiles({id :'bz_kj_02',image :'bz_kj_02',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_03","images/ScienceEC/bz_kj_03.jpg?v=1");
	gbox.addTiles({id :'bz_kj_03',image :'bz_kj_03',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_04","images/ScienceEC/bz_kj_04.jpg?v=1");
	gbox.addTiles({id :'bz_kj_04',image :'bz_kj_04',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_05","images/ScienceEC/bz_kj_05.jpg?v=1");
	gbox.addTiles({id :'bz_kj_05',image :'bz_kj_05',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_06","images/ScienceEC/bz_kj_06.jpg?v=1");
	gbox.addTiles({id :'bz_kj_06',image :'bz_kj_06',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_07","images/ScienceEC/bz_kj_07.jpg?v=1");
	gbox.addTiles({id :'bz_kj_07',image :'bz_kj_07',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_08","images/ScienceEC/bz_kj_08.jpg?v=1");
	gbox.addTiles({id :'bz_kj_08',image :'bz_kj_08',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_09","images/ScienceEC/bz_kj_09.jpg?v=1");
	gbox.addTiles({id :'bz_kj_09',image :'bz_kj_09',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_10","images/ScienceEC/bz_kj_10.jpg?v=1");
	gbox.addTiles({id :'bz_kj_10',image :'bz_kj_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_11","images/ScienceEC/bz_kj_11.jpg?v=1");
	gbox.addTiles({id :'bz_kj_11',image :'bz_kj_11',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_12","images/ScienceEC/bz_kj_12.jpg?v=1");
	gbox.addTiles({id :'bz_kj_12',image :'bz_kj_12',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_13","images/ScienceEC/bz_kj_13.jpg?v=1");
	gbox.addTiles({id :'bz_kj_13',image :'bz_kj_13',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_14","images/ScienceEC/bz_kj_14.jpg?v=1");
	gbox.addTiles({id :'bz_kj_14',image :'bz_kj_14',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_15","images/ScienceEC/bz_kj_15.jpg?v=1");
	gbox.addTiles({id :'bz_kj_15',image :'bz_kj_15',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_16","images/ScienceEC/bz_kj_16.jpg?v=1");
	gbox.addTiles({id :'bz_kj_16',image :'bz_kj_16',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_17","images/ScienceEC/bz_kj_17.jpg?v=1");
	gbox.addTiles({id :'bz_kj_17',image :'bz_kj_17',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_18","images/ScienceEC/bz_kj_18.jpg?v=1");
	gbox.addTiles({id :'bz_kj_18',image :'bz_kj_18',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_19","images/ScienceEC/bz_kj_19.jpg?v=1");
	gbox.addTiles({id :'bz_kj_19',image :'bz_kj_19',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_20","images/ScienceEC/bz_kj_20.jpg?v=1");
	gbox.addTiles({id :'bz_kj_20',image :'bz_kj_20',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_21","images/ScienceEC/bz_kj_21.jpg?v=1");
	gbox.addTiles({id :'bz_kj_21',image :'bz_kj_21',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_22","images/ScienceEC/bz_kj_22.jpg?v=1");
	gbox.addTiles({id :'bz_kj_22',image :'bz_kj_22',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_23","images/ScienceEC/bz_kj_23.jpg?v=1");
	gbox.addTiles({id :'bz_kj_23',image :'bz_kj_23',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_24","images/ScienceEC/bz_kj_24.jpg?v=1");
	gbox.addTiles({id :'bz_kj_24',image :'bz_kj_24',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_25","images/ScienceEC/bz_kj_25.jpg?v=1");
	gbox.addTiles({id :'bz_kj_25',image :'bz_kj_25',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_26","images/ScienceEC/bz_kj_26.jpg?v=1");
	gbox.addTiles({id :'bz_kj_26',image :'bz_kj_26',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_27","images/ScienceEC/bz_kj_27.jpg?v=1");
	gbox.addTiles({id :'bz_kj_27',image :'bz_kj_27',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_28","images/ScienceEC/bz_kj_28.jpg?v=1");
	gbox.addTiles({id :'bz_kj_28',image :'bz_kj_28',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_29","images/ScienceEC/bz_kj_29.jpg?v=1");
	gbox.addTiles({id :'bz_kj_29',image :'bz_kj_29',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("bz_kj_30","images/ScienceEC/bz_kj_30.jpg?v=1");
	gbox.addTiles({id :'bz_kj_30',image :'bz_kj_30',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjgHitRect","images/ScienceEC/kjgHitRect.png?v=1");
	gbox.addTiles({id :'kjgHitRect',image :'kjgHitRect',tilew:204,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjgPassRect","images/ScienceEC/kjgPassRect.png?v=1");
	gbox.addTiles({id :'kjgPassRect',image :'kjgPassRect',tilew:204,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_01","images/ScienceEC/kjg_zjm_01.png?v=1");
	gbox.addTiles({id :'kjg_zjm_01',image :'kjg_zjm_01',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_02","images/ScienceEC/kjg_zjm_02.png?v=1");
	gbox.addTiles({id :'kjg_zjm_02',image :'kjg_zjm_02',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_03","images/ScienceEC/kjg_zjm_03.png?v=1");
	gbox.addTiles({id :'kjg_zjm_03',image :'kjg_zjm_03',tilew:325,tileh:40,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_04","images/ScienceEC/kjg_zjm_04.png?v=1");
	gbox.addTiles({id :'kjg_zjm_04',image :'kjg_zjm_04',tilew:244,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_05","images/ScienceEC/kjg_zjm_05.png?v=1");
	gbox.addTiles({id :'kjg_zjm_05',image :'kjg_zjm_05',tilew:497,tileh:300,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_06","images/ScienceEC/kjg_zjm_06.png?v=1");
	gbox.addTiles({id :'kjg_zjm_06',image :'kjg_zjm_06',tilew:508,tileh:301,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_08","images/ScienceEC/kjg_zjm_08.png?v=1");
	gbox.addTiles({id :'kjg_zjm_08',image :'kjg_zjm_08',tilew:44,tileh:44,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_09","images/ScienceEC/kjg_zjm_09.png?v=1");
	gbox.addTiles({id :'kjg_zjm_09',image :'kjg_zjm_09',tilew:488,tileh:55,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_11","images/ScienceEC/kjg_zjm_11.png?v=1");
	gbox.addTiles({id :'kjg_zjm_11',image :'kjg_zjm_11',tilew:204,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_22","images/ScienceEC/kjg_zjm_22.png?v=1");
	gbox.addTiles({id :'kjg_zjm_22',image :'kjg_zjm_22',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_23","images/ScienceEC/kjg_zjm_23.png?v=1");
	gbox.addTiles({id :'kjg_zjm_23',image :'kjg_zjm_23',tilew:53,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_24","images/ScienceEC/kjg_zjm_24.png?v=1");
	gbox.addTiles({id :'kjg_zjm_24',image :'kjg_zjm_24',tilew:44,tileh:44,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_35","images/ScienceEC/kjg_zjm_35.png?v=1");
	gbox.addTiles({id :'kjg_zjm_35',image :'kjg_zjm_35',tilew:244,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_36","images/ScienceEC/kjg_zjm_36.png?v=1");
	gbox.addTiles({id :'kjg_zjm_36',image :'kjg_zjm_36',tilew:244,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_37","images/ScienceEC/kjg_zjm_37.png?v=1");
	gbox.addTiles({id :'kjg_zjm_37',image :'kjg_zjm_37',tilew:40,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_39","images/ScienceEC/kjg_zjm_39.png?v=1");
	gbox.addTiles({id :'kjg_zjm_39',image :'kjg_zjm_39',tilew:40,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kjg_zjm_41","images/ScienceEC/kjg_zjm_41.png?v=1");
	gbox.addTiles({id :'kjg_zjm_41',image :'kjg_zjm_41',tilew:40,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_01","images/ScienceEC/nz_kj_01.jpg?v=1");
	gbox.addTiles({id :'nz_kj_01',image :'nz_kj_01',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_02","images/ScienceEC/nz_kj_02.jpg?v=1");
	gbox.addTiles({id :'nz_kj_02',image :'nz_kj_02',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_03","images/ScienceEC/nz_kj_03.jpg?v=1");
	gbox.addTiles({id :'nz_kj_03',image :'nz_kj_03',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_04","images/ScienceEC/nz_kj_04.jpg?v=1");
	gbox.addTiles({id :'nz_kj_04',image :'nz_kj_04',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_05","images/ScienceEC/nz_kj_05.jpg?v=1");
	gbox.addTiles({id :'nz_kj_05',image :'nz_kj_05',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_06","images/ScienceEC/nz_kj_06.jpg?v=1");
	gbox.addTiles({id :'nz_kj_06',image :'nz_kj_06',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_07","images/ScienceEC/nz_kj_07.jpg?v=1");
	gbox.addTiles({id :'nz_kj_07',image :'nz_kj_07',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_08","images/ScienceEC/nz_kj_08.jpg?v=1");
	gbox.addTiles({id :'nz_kj_08',image :'nz_kj_08',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_09","images/ScienceEC/nz_kj_09.jpg?v=1");
	gbox.addTiles({id :'nz_kj_09',image :'nz_kj_09',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_10","images/ScienceEC/nz_kj_10.jpg?v=1");
	gbox.addTiles({id :'nz_kj_10',image :'nz_kj_10',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_11","images/ScienceEC/nz_kj_11.jpg?v=1");
	gbox.addTiles({id :'nz_kj_11',image :'nz_kj_11',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_12","images/ScienceEC/nz_kj_12.jpg?v=1");
	gbox.addTiles({id :'nz_kj_12',image :'nz_kj_12',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_13","images/ScienceEC/nz_kj_13.jpg?v=1");
	gbox.addTiles({id :'nz_kj_13',image :'nz_kj_13',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_14","images/ScienceEC/nz_kj_14.jpg?v=1");
	gbox.addTiles({id :'nz_kj_14',image :'nz_kj_14',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_15","images/ScienceEC/nz_kj_15.jpg?v=1");
	gbox.addTiles({id :'nz_kj_15',image :'nz_kj_15',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nz_kj_16","images/ScienceEC/nz_kj_16.jpg?v=1");
	gbox.addTiles({id :'nz_kj_16',image :'nz_kj_16',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});

};