/*
 * 城郊
 */
var SuburbsLoadImage = function()
{
	console.log('开始加载城郊图片');
	gbox.addImage("army_bottom_enemy","images/Suburbs/army_bottom_enemy.png?v=1");
	gbox.addTiles({id :'army_bottom_enemy',image :'army_bottom_enemy',tilew:1855,tileh:487,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_bottom_enemy_focus","images/Suburbs/army_bottom_enemy_focus.png?v=1");
	gbox.addTiles({id :'army_bottom_enemy_focus',image :'army_bottom_enemy_focus',tilew:184,tileh:102,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_bottom_mine","images/Suburbs/army_bottom_mine.png?v=1");
	gbox.addTiles({id :'army_bottom_mine',image :'army_bottom_mine',tilew:1855,tileh:487,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_bottom_mine_focus","images/Suburbs/army_bottom_mine_focus.png?v=1");
	gbox.addTiles({id :'army_bottom_mine_focus',image :'army_bottom_mine_focus',tilew:184,tileh:102,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_top_enemy","images/Suburbs/army_top_enemy.png?v=1");
	gbox.addTiles({id :'army_top_enemy',image :'army_top_enemy',tilew:1879,tileh:427,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_top_enemy_focus","images/Suburbs/army_top_enemy_focus.png?v=1");
	gbox.addTiles({id :'army_top_enemy_focus',image :'army_top_enemy_focus',tilew:157,tileh:82,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_top_mine","images/Suburbs/army_top_mine.png?v=1");
	gbox.addTiles({id :'army_top_mine',image :'army_top_mine',tilew:1879,tileh:427,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("army_top_mine_focus","images/Suburbs/army_top_mine_focus.png?v=1");
	gbox.addTiles({id :'army_top_mine_focus',image :'army_top_mine_focus',tilew:156,tileh:82,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("chengshu","images/Suburbs/chengshu.png?v=1");
	gbox.addTiles({id :'chengshu',image :'chengshu',tilew:365,tileh:283,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("envCity1","images/Suburbs/envCity1.png?v=1");
	gbox.addTiles({id :'envCity1',image :'envCity1',tilew:700,tileh:420,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("environs","images/Suburbs/environs.jpg?v=1");
	gbox.addTiles({id :'environs',image :'environs',tilew:2017,tileh:1394,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("envMineLight","images/Suburbs/envMineLight.png?v=1");
	gbox.addTiles({id :'envMineLight',image :'envMineLight',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("envMineLightR","images/Suburbs/envMineLightR.png?v=1");
	gbox.addTiles({id :'envMineLightR',image :'envMineLightR',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("farmlandAlert","images/Suburbs/farmlandAlert.png?v=1");
	gbox.addTiles({id :'farmlandAlert',image :'farmlandAlert',tilew:274,tileh:119,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("farmlandBtn","images/Suburbs/farmlandBtn.png?v=1");
	gbox.addTiles({id :'farmlandBtn',image :'farmlandBtn',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("farmlandCancel","images/Suburbs/farmlandCancel.png?v=1");
	gbox.addTiles({id :'farmlandCancel',image :'farmlandCancel',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("farmlandEnter","images/Suburbs/farmlandEnter.png?v=1");
	gbox.addTiles({id :'farmlandEnter',image :'farmlandEnter',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("FarmlandUP","images/Suburbs/FarmlandUP.png?v=1");
	gbox.addTiles({id :'FarmlandUP',image :'FarmlandUP',tilew:448,tileh:186,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ferrumchongtu","images/Suburbs/ferrumchongtu.png?v=1");
	gbox.addTiles({id :'ferrumchongtu',image :'ferrumchongtu',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ferrumchongtu2","images/Suburbs/ferrumchongtu2.png?v=1");
	gbox.addTiles({id :'ferrumchongtu2',image :'ferrumchongtu2',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ferrumkaiqi1","images/Suburbs/ferrumkaiqi1.png?v=1");
	gbox.addTiles({id :'ferrumkaiqi1',image :'ferrumkaiqi1',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ferrumwancheng","images/Suburbs/ferrumwancheng.png?v=1");
	gbox.addTiles({id :'ferrumwancheng',image :'ferrumwancheng',tilew:28,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ferrumwancheng1","images/Suburbs/ferrumwancheng1.png?v=1");
	gbox.addTiles({id :'ferrumwancheng1',image :'ferrumwancheng1',tilew:28,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodAni","images/Suburbs/foodAni.png?v=1");
	gbox.addTiles({id :'foodAni',image :'foodAni',tilew:665,tileh:85,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodchengshu1","images/Suburbs/foodchengshu1.png?v=1");
	gbox.addTiles({id :'foodchengshu1',image :'foodchengshu1',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodchengshu2","images/Suburbs/foodchengshu2.png?v=1");
	gbox.addTiles({id :'foodchengshu2',image :'foodchengshu2',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodGreen","images/Suburbs/foodGreen.png?v=1");
	gbox.addTiles({id :'foodGreen',image :'foodGreen',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodGreenLight","images/Suburbs/foodGreenLight.png?v=1");
	gbox.addTiles({id :'foodGreenLight',image :'foodGreenLight',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("foodLight","images/Suburbs/foodLight.png?v=1");
	gbox.addTiles({id :'foodLight',image :'foodLight',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("grainOpen","images/Suburbs/grainOpen.png?v=1");
	gbox.addTiles({id :'grainOpen',image :'grainOpen',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("grainOpenLight","images/Suburbs/grainOpenLight.png?v=1");
	gbox.addTiles({id :'grainOpenLight',image :'grainOpenLight',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("influence","images/Suburbs/influence.png?v=1");
	gbox.addTiles({id :'influence',image :'influence',tilew:256,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kuangshikaiqi2","images/Suburbs/kuangshikaiqi2.png?v=1");
	gbox.addTiles({id :'kuangshikaiqi2',image :'kuangshikaiqi2',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kuangshikaiqi3","images/Suburbs/kuangshikaiqi3.png?v=1");
	gbox.addTiles({id :'kuangshikaiqi3',image :'kuangshikaiqi3',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("kuangshikaiqi4","images/Suburbs/kuangshikaiqi4.png?v=1");
	gbox.addTiles({id :'kuangshikaiqi4',image :'kuangshikaiqi4',tilew:132,tileh:110,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_01","images/Suburbs/nc_tb_01.png?v=1");
	gbox.addTiles({id :'nc_tb_01',image :'nc_tb_01',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_02","images/Suburbs/nc_tb_02.png?v=1");
	gbox.addTiles({id :'nc_tb_02',image :'nc_tb_02',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_03","images/Suburbs/nc_tb_03.png?v=1");
	gbox.addTiles({id :'nc_tb_03',image :'nc_tb_03',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_04","images/Suburbs/nc_tb_04.png?v=1");
	gbox.addTiles({id :'nc_tb_04',image :'nc_tb_04',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_05","images/Suburbs/nc_tb_05.png?v=1");
	gbox.addTiles({id :'nc_tb_05',image :'nc_tb_05',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_06","images/Suburbs/nc_tb_06.png?v=1");
	gbox.addTiles({id :'nc_tb_06',image :'nc_tb_06',tilew:60,tileh:60,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_09_1","images/Suburbs/nc_tb_09_1.jpg?v=1");
	gbox.addTiles({id :'nc_tb_09_1',image :'nc_tb_09_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_09_2","images/Suburbs/nc_tb_09_2.jpg?v=1");
	gbox.addTiles({id :'nc_tb_09_2',image :'nc_tb_09_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_09_3","images/Suburbs/nc_tb_09_3.jpg?v=1");
	gbox.addTiles({id :'nc_tb_09_3',image :'nc_tb_09_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_09_4","images/Suburbs/nc_tb_09_4.jpg?v=1");
	gbox.addTiles({id :'nc_tb_09_4',image :'nc_tb_09_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_10_1","images/Suburbs/nc_tb_10_1.jpg?v=1");
	gbox.addTiles({id :'nc_tb_10_1',image :'nc_tb_10_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_10_2","images/Suburbs/nc_tb_10_2.jpg?v=1");
	gbox.addTiles({id :'nc_tb_10_2',image :'nc_tb_10_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_10_3","images/Suburbs/nc_tb_10_3.jpg?v=1");
	gbox.addTiles({id :'nc_tb_10_3',image :'nc_tb_10_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_10_4","images/Suburbs/nc_tb_10_4.jpg?v=1");
	gbox.addTiles({id :'nc_tb_10_4',image :'nc_tb_10_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_11_1","images/Suburbs/nc_tb_11_1.jpg?v=1");
	gbox.addTiles({id :'nc_tb_11_1',image :'nc_tb_11_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_11_2","images/Suburbs/nc_tb_11_2.jpg?v=1");
	gbox.addTiles({id :'nc_tb_11_2',image :'nc_tb_11_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_11_3","images/Suburbs/nc_tb_11_3.jpg?v=1");
	gbox.addTiles({id :'nc_tb_11_3',image :'nc_tb_11_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_11_4","images/Suburbs/nc_tb_11_4.jpg?v=1");
	gbox.addTiles({id :'nc_tb_11_4',image :'nc_tb_11_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_12_1","images/Suburbs/nc_tb_12_1.jpg?v=1");
	gbox.addTiles({id :'nc_tb_12_1',image :'nc_tb_12_1',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_12_2","images/Suburbs/nc_tb_12_2.jpg?v=1");
	gbox.addTiles({id :'nc_tb_12_2',image :'nc_tb_12_2',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_12_3","images/Suburbs/nc_tb_12_3.jpg?v=1");
	gbox.addTiles({id :'nc_tb_12_3',image :'nc_tb_12_3',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("nc_tb_12_4","images/Suburbs/nc_tb_12_4.jpg?v=1");
	gbox.addTiles({id :'nc_tb_12_4',image :'nc_tb_12_4',tilew:30,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("selectedArmy","images/Suburbs/selectedArmy.png?v=1");
	gbox.addTiles({id :'selectedArmy',image :'selectedArmy',tilew:202,tileh:169,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shitou","images/Suburbs/shitou.png?v=1");
	gbox.addTiles({id :'shitou',image :'shitou',tilew:28,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shitoushengzhang","images/Suburbs/shitoushengzhang.png?v=1");
	gbox.addTiles({id :'shitoushengzhang',image :'shitoushengzhang',tilew:181,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shitoushengzhang1","images/Suburbs/shitoushengzhang1.png?v=1");
	gbox.addTiles({id :'shitoushengzhang1',image :'shitoushengzhang1',tilew:181,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("shitoushili","images/Suburbs/shitoushili.png?v=1");
	gbox.addTiles({id :'shitoushili',image :'shitoushili',tilew:181,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("stoneLight","images/Suburbs/stoneLight.png?v=1");
	gbox.addTiles({id :'stoneLight',image :'stoneLight',tilew:181,tileh:120,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodAni","images/Suburbs/woodAni.png?v=1");
	gbox.addTiles({id :'woodAni',image :'woodAni',tilew:200,tileh:50,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodchengshu1","images/Suburbs/woodchengshu1.png?v=1");
	gbox.addTiles({id :'woodchengshu1',image :'woodchengshu1',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodchengshu2","images/Suburbs/woodchengshu2.png?v=1");
	gbox.addTiles({id :'woodchengshu2',image :'woodchengshu2',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodchongtu","images/Suburbs/woodchongtu.png?v=1");
	gbox.addTiles({id :'woodchongtu',image :'woodchongtu',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodLight","images/Suburbs/woodLight.png?v=1");
	gbox.addTiles({id :'woodLight',image :'woodLight',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodOpen","images/Suburbs/woodOpen.png?v=1");
	gbox.addTiles({id :'woodOpen',image :'woodOpen',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodOpenLight","images/Suburbs/woodOpenLight.png?v=1");
	gbox.addTiles({id :'woodOpenLight',image :'woodOpenLight',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodshengchan1","images/Suburbs/woodshengchan1.png?v=1");
	gbox.addTiles({id :'woodshengchan1',image :'woodshengchan1',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("woodshengchan2","images/Suburbs/woodshengchan2.png?v=1");
	gbox.addTiles({id :'woodshengchan2',image :'woodshengchan2',tilew:148,tileh:99,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_03","images/Suburbs/zd_ct_03.png?v=1");
	gbox.addTiles({id :'zd_ct_03',image :'zd_ct_03',tilew:317,tileh:253,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_04","images/Suburbs/zd_ct_04.png?v=1");
	gbox.addTiles({id :'zd_ct_04',image :'zd_ct_04',tilew:156,tileh:32,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_05","images/Suburbs/zd_ct_05.png?v=1");
	gbox.addTiles({id :'zd_ct_05',image :'zd_ct_05',tilew:156,tileh:32,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_06","images/Suburbs/zd_ct_06.png?v=1");
	gbox.addTiles({id :'zd_ct_06',image :'zd_ct_06',tilew:156,tileh:32,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_07","images/Suburbs/zd_ct_07.png?v=1");
	gbox.addTiles({id :'zd_ct_07',image :'zd_ct_07',tilew:100,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zd_ct_08","images/Suburbs/zd_ct_08.png?v=1");
	gbox.addTiles({id :'zd_ct_08',image :'zd_ct_08',tilew:100,tileh:30,tilerow : 1,gapx : 0,gapy : 0});
	console.log('完成城郊图片加载');
};