var universalLoadImage = function()
{
	gbox.addImage("buildUpLevel","images/Universal/buildUpLevel.png?v=1");
	gbox.addTiles({id :'buildUpLevel',image :'buildUpLevel',tilew:1600,tileh:495,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ckjz_zjm_01","images/Universal/ckjz_zjm_01.png?v=1");
	gbox.addTiles({id :'ckjz_zjm_01',image :'ckjz_zjm_01',tilew:465,tileh:310,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("hit","images/Universal/hit.png?v=1");
	gbox.addTiles({id :'hit',image :'hit',tilew:35,tileh:35,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_09","images/Universal/jgf_zjm_09.png?v=1");
	gbox.addTiles({id :'jgf_zjm_09',image :'jgf_zjm_09',tilew:748,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jgf_zjm_3_","images/Universal/jgf_zjm_3_.png?v=1");
	gbox.addTiles({id :'jgf_zjm_3_',image :'jgf_zjm_3_',tilew:36,tileh:36,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("jq_zjm_29","images/Universal/jq_zjm_29.png?v=1");
	gbox.addTiles({id :'jq_zjm_29',image :'jq_zjm_29',tilew:317,tileh:253,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("mj_zjm_05","images/Universal/mj_zjm_05.png?v=1");
	gbox.addTiles({id :'mj_zjm_05',image :'mj_zjm_05',tilew:325,tileh:265,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("toolTip","images/Universal/toolTip.png?v=1");
	gbox.addTiles({id :'toolTip',image :'toolTip',tilew:222,tileh:1,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_01","images/Universal/ty_an_01.png?v=1");
	gbox.addTiles({id :'ty_an_01',image :'ty_an_01',tilew:23,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_02","images/Universal/ty_an_02.png?v=1");
	gbox.addTiles({id :'ty_an_02',image :'ty_an_02',tilew:28,tileh:28,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_03","images/Universal/ty_an_03.png?v=1");
	gbox.addTiles({id :'ty_an_03',image :'ty_an_03',tilew:28,tileh:28,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_04","images/Universal/ty_an_04.png?v=1");
	gbox.addTiles({id :'ty_an_04',image :'ty_an_04',tilew:23,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_05","images/Universal/ty_an_05.png?v=1");
	gbox.addTiles({id :'ty_an_05',image :'ty_an_05',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_06","images/Universal/ty_an_06.png?v=1");
	gbox.addTiles({id :'ty_an_06',image :'ty_an_06',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_07","images/Universal/ty_an_07.png?v=1");
	gbox.addTiles({id :'ty_an_07',image :'ty_an_07',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_08","images/Universal/ty_an_08.png?v=1");
	gbox.addTiles({id :'ty_an_08',image :'ty_an_08',tilew:50,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_09","images/Universal/ty_an_09.png?v=1");
	gbox.addTiles({id :'ty_an_09',image :'ty_an_09',tilew:84,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_10","images/Universal/ty_an_10.png?v=1");
	gbox.addTiles({id :'ty_an_10',image :'ty_an_10',tilew:84,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_100","images/Universal/ty_an_100.png?v=1");
	gbox.addTiles({id :'ty_an_100',image :'ty_an_100',tilew:70,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_101","images/Universal/ty_an_101.png?v=1");
	gbox.addTiles({id :'ty_an_101',image :'ty_an_101',tilew:116,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_102","images/Universal/ty_an_102.png?v=1");
	gbox.addTiles({id :'ty_an_102',image :'ty_an_102',tilew:116,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_103","images/Universal/ty_an_103.png?v=1");
	gbox.addTiles({id :'ty_an_103',image :'ty_an_103',tilew:116,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	
	gbox.addImage("ty_an_11","images/Universal/ty_an_11.png?v=1");
	gbox.addTiles({id :'ty_an_11',image :'ty_an_11',tilew:84,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	
	gbox.addImage("ty_an_12","images/Universal/ty_an_12.png?v=1");
	gbox.addTiles({id :'ty_an_12',image :'ty_an_12',tilew:23,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_120","images/Universal/ty_an_120.png?v=1");
	gbox.addTiles({id :'ty_an_120',image :'ty_an_120',tilew:53,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_121","images/Universal/ty_an_121.png?v=1");
	gbox.addTiles({id :'ty_an_121',image :'ty_an_121',tilew:70,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_122","images/Universal/ty_an_122.png?v=1");
	gbox.addTiles({id :'ty_an_122',image :'ty_an_122',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_123","images/Universal/ty_an_123.png?v=1");
	gbox.addTiles({id :'ty_an_123',image :'ty_an_123',tilew:18,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_124","images/Universal/ty_an_124.png?v=1");
	gbox.addTiles({id :'ty_an_124',image :'ty_an_124',tilew:18,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_125","images/Universal/ty_an_125.png?v=1");
	gbox.addTiles({id :'ty_an_125',image :'ty_an_125',tilew:18,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_126","images/Universal/ty_an_126.png?v=1");
	gbox.addTiles({id :'ty_an_126',image :'ty_an_126',tilew:18,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_127","images/Universal/ty_an_127.png?v=1");
	gbox.addTiles({id :'ty_an_127',image :'ty_an_127',tilew:808,tileh:496,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_128","images/Universal/ty_an_128.png?v=1");
	gbox.addTiles({id :'ty_an_128',image :'ty_an_128',tilew:36,tileh:36,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_129","images/Universal/ty_an_129.png?v=1");
	gbox.addTiles({id :'ty_an_129',image :'ty_an_129',tilew:36,tileh:36,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_13","images/Universal/ty_an_13.png?v=1");
	gbox.addTiles({id :'ty_an_13',image :'ty_an_13',tilew:15,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_130","images/Universal/ty_an_130.png?v=1");
	gbox.addTiles({id :'ty_an_130',image :'ty_an_130',tilew:1023,tileh:542,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_131","images/Universal/ty_an_131.png?v=1");
	gbox.addTiles({id :'ty_an_131',image :'ty_an_131',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_132","images/Universal/ty_an_132.png?v=1");
	gbox.addTiles({id :'ty_an_132',image :'ty_an_132',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_133","images/Universal/ty_an_133.png?v=1");
	gbox.addTiles({id :'ty_an_133',image :'ty_an_133',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_134","images/Universal/ty_an_134.png?v=1");
	gbox.addTiles({id :'ty_an_134',image :'ty_an_134',tilew:34,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_135","images/Universal/ty_an_135.png?v=1");
	gbox.addTiles({id :'ty_an_135',image :'ty_an_135',tilew:46,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_136","images/Universal/ty_an_136.png?v=1");
	gbox.addTiles({id :'ty_an_136',image :'ty_an_136',tilew:46,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_137","images/Universal/ty_an_137.png?v=1");
	gbox.addTiles({id :'ty_an_137',image :'ty_an_137',tilew:46,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_14","images/Universal/ty_an_14.png?v=1");
	gbox.addTiles({id :'ty_an_14',image :'ty_an_14',tilew:15,tileh:6,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_15","images/Universal/ty_an_15.png?v=1");
	gbox.addTiles({id :'ty_an_15',image :'ty_an_15',tilew:15,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_16","images/Universal/ty_an_16.png?v=1");
	gbox.addTiles({id :'ty_an_16',image :'ty_an_16',tilew:15,tileh:6,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_17","images/Universal/ty_an_17.png?v=1");
	gbox.addTiles({id :'ty_an_17',image :'ty_an_17',tilew:16,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_18","images/Universal/ty_an_18.png?v=1");
	gbox.addTiles({id :'ty_an_18',image :'ty_an_18',tilew:16,tileh:15,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_19","images/Universal/ty_an_19.png?v=1");
	gbox.addTiles({id :'ty_an_19',image :'ty_an_19',tilew:16,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_20","images/Universal/ty_an_20.png?v=1");
	gbox.addTiles({id :'ty_an_20',image :'ty_an_20',tilew:16,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_21","images/Universal/ty_an_21.png?v=1");
	gbox.addTiles({id :'ty_an_21',image :'ty_an_21',tilew:16,tileh:10,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_22","images/Universal/ty_an_22.png?v=1");
	gbox.addTiles({id :'ty_an_22',image :'ty_an_22',tilew:18,tileh:11,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_23","images/Universal/ty_an_23.png?v=1");
	gbox.addTiles({id :'ty_an_23',image :'ty_an_23',tilew:18,tileh:11,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_24","images/Universal/ty_an_24.png?v=1");
	gbox.addTiles({id :'ty_an_24',image :'ty_an_24',tilew:11,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_25","images/Universal/ty_an_25.png?v=1");
	gbox.addTiles({id :'ty_an_25',image :'ty_an_25',tilew:11,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_26","images/Universal/ty_an_26.png?v=1");
	gbox.addTiles({id :'ty_an_26',image :'ty_an_26',tilew:274,tileh:119,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_27","images/Universal/ty_an_27.png?v=1");
	gbox.addTiles({id :'ty_an_27',image :'ty_an_27',tilew:808,tileh:488,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_32","images/Universal/ty_an_32.png?v=1");
	gbox.addTiles({id :'ty_an_32',image :'ty_an_32',tilew:140,tileh:198,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_33","images/Universal/ty_an_33.png?v=1");
	gbox.addTiles({id :'ty_an_33',image :'ty_an_33',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_34","images/Universal/ty_an_34.png?v=1");
	gbox.addTiles({id :'ty_an_34',image :'ty_an_34',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_35","images/Universal/ty_an_35.png?v=1");
	gbox.addTiles({id :'ty_an_35',image :'ty_an_35',tilew:139,tileh:53,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_36","images/Universal/ty_an_36.png?v=1");
	gbox.addTiles({id :'ty_an_36',image :'ty_an_36',tilew:70,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_37","images/Universal/ty_an_37.png?v=1");
	gbox.addTiles({id :'ty_an_37',image :'ty_an_37',tilew:70,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_38","images/Universal/ty_an_38.png?v=1");
	gbox.addTiles({id :'ty_an_38',image :'ty_an_38',tilew:21,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_39","images/Universal/ty_an_39.png?v=1");
	gbox.addTiles({id :'ty_an_39',image :'ty_an_39',tilew:70,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_40","images/Universal/ty_an_40.png?v=1");
	gbox.addTiles({id :'ty_an_40',image :'ty_an_40',tilew:70,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_45","images/Universal/ty_an_45.png?v=1");
	gbox.addTiles({id :'ty_an_45',image :'ty_an_45',tilew:18,tileh:11,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_46","images/Universal/ty_an_46.png?v=1");
	gbox.addTiles({id :'ty_an_46',image :'ty_an_46',tilew:18,tileh:11,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_47","images/Universal/ty_an_47.png?v=1");
	gbox.addTiles({id :'ty_an_47',image :'ty_an_47',tilew:11,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_48","images/Universal/ty_an_48.png?v=1");
	gbox.addTiles({id :'ty_an_48',image :'ty_an_48',tilew:11,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_49","images/Universal/ty_an_49.png?v=1");
	gbox.addTiles({id :'ty_an_49',image :'ty_an_49',tilew:13,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_50","images/Universal/ty_an_50.png?v=1");
	gbox.addTiles({id :'ty_an_50',image :'ty_an_50',tilew:13,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_51","images/Universal/ty_an_51.png?v=1");
	gbox.addTiles({id :'ty_an_51',image :'ty_an_51',tilew:13,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_52","images/Universal/ty_an_52.png?v=1");
	gbox.addTiles({id :'ty_an_52',image :'ty_an_52',tilew:13,tileh:18,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_55","images/Universal/ty_an_55.png?v=1");
	gbox.addTiles({id :'ty_an_55',image :'ty_an_55',tilew:274,tileh:119,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_56","images/Universal/ty_an_56.png?v=1");
	gbox.addTiles({id :'ty_an_56',image :'ty_an_56',tilew:179,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_57","images/Universal/ty_an_57.jpg?v=1");
	gbox.addTiles({id :'ty_an_57',image :'ty_an_57',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_58","images/Universal/ty_an_58.jpg?v=1");
	gbox.addTiles({id :'ty_an_58',image :'ty_an_58',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_60","images/Universal/ty_an_60.jpg?v=1");
	gbox.addTiles({id :'ty_an_60',image :'ty_an_60',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_62","images/Universal/ty_an_62.jpg?v=1");
	gbox.addTiles({id :'ty_an_62',image :'ty_an_62',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_64","images/Universal/ty_an_64.jpg?v=1");
	gbox.addTiles({id :'ty_an_64',image :'ty_an_64',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_65","images/Universal/ty_an_65.jpg?v=1");
	gbox.addTiles({id :'ty_an_65',image :'ty_an_65',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_66","images/Universal/ty_an_66.jpg?v=1");
	gbox.addTiles({id :'ty_an_66',image :'ty_an_66',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_68","images/Universal/ty_an_68.jpg?v=1");
	gbox.addTiles({id :'ty_an_68',image :'ty_an_68',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_69","images/Universal/ty_an_69.jpg?v=1");
	gbox.addTiles({id :'ty_an_69',image :'ty_an_69',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_71","images/Universal/ty_an_71.jpg?v=1");
	gbox.addTiles({id :'ty_an_71',image :'ty_an_71',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_72","images/Universal/ty_an_72.png?v=1");
	gbox.addTiles({id :'ty_an_72',image :'ty_an_72',tilew:42,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_73","images/Universal/ty_an_73.png?v=1");
	gbox.addTiles({id :'ty_an_73',image :'ty_an_73',tilew:42,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_74","images/Universal/ty_an_74.jpg?v=1");
	gbox.addTiles({id :'ty_an_74',image :'ty_an_74',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_76","images/Universal/ty_an_76.jpg?v=1");
	gbox.addTiles({id :'ty_an_76',image :'ty_an_76',tilew:21,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_77","images/Universal/ty_an_77.png?v=1");
	gbox.addTiles({id :'ty_an_77',image :'ty_an_77',tilew:42,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_95","images/Universal/ty_an_95.png?v=1");
	gbox.addTiles({id :'ty_an_95',image :'ty_an_95',tilew:62,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_96","images/Universal/ty_an_96.png?v=1");
	gbox.addTiles({id :'ty_an_96',image :'ty_an_96',tilew:62,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_97","images/Universal/ty_an_97.png?v=1");
	gbox.addTiles({id :'ty_an_97',image :'ty_an_97',tilew:62,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_98","images/Universal/ty_an_98.png?v=1");
	gbox.addTiles({id :'ty_an_98',image :'ty_an_98',tilew:70,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_an_99","images/Universal/ty_an_99.png?v=1");
	gbox.addTiles({id :'ty_an_99',image :'ty_an_99',tilew:70,tileh:20,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_01","images/Universal/ty_tdt_01.png?v=1");
	gbox.addTiles({id :'ty_tdt_01',image :'ty_tdt_01',tilew:30,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_02","images/Universal/ty_tdt_02.png?v=1");
	gbox.addTiles({id :'ty_tdt_02',image :'ty_tdt_02',tilew:30,tileh:1,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_03","images/Universal/ty_tdt_03.png?v=1");
	gbox.addTiles({id :'ty_tdt_03',image :'ty_tdt_03',tilew:30,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_04","images/Universal/ty_tdt_04.png?v=1");
	gbox.addTiles({id :'ty_tdt_04',image :'ty_tdt_04',tilew:16,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_05","images/Universal/ty_tdt_05.png?v=1");
	gbox.addTiles({id :'ty_tdt_05',image :'ty_tdt_05',tilew:16,tileh:1,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_06","images/Universal/ty_tdt_06.png?v=1");
	gbox.addTiles({id :'ty_tdt_06',image :'ty_tdt_06',tilew:16,tileh:16,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_07","images/Universal/ty_tdt_07.png?v=1");
	gbox.addTiles({id :'ty_tdt_07',image :'ty_tdt_07',tilew:21,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_08","images/Universal/ty_tdt_08.png?v=1");
	gbox.addTiles({id :'ty_tdt_08',image :'ty_tdt_08',tilew:21,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_09","images/Universal/ty_tdt_09.png?v=1");
	gbox.addTiles({id :'ty_tdt_09',image :'ty_tdt_09',tilew:21,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_10","images/Universal/ty_tdt_10.png?v=1");
	gbox.addTiles({id :'ty_tdt_10',image :'ty_tdt_10',tilew:21,tileh:21,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_11","images/Universal/ty_tdt_11.png?v=1");
	gbox.addTiles({id :'ty_tdt_11',image :'ty_tdt_11',tilew:21,tileh:26,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_12","images/Universal/ty_tdt_12.png?v=1");
	gbox.addTiles({id :'ty_tdt_12',image :'ty_tdt_12',tilew:34,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_13","images/Universal/ty_tdt_13.png?v=1");
	gbox.addTiles({id :'ty_tdt_13',image :'ty_tdt_13',tilew:20,tileh:25,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_14","images/Universal/ty_tdt_14.png?v=1");
	gbox.addTiles({id :'ty_tdt_14',image :'ty_tdt_14',tilew:20,tileh:37,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_15","images/Universal/ty_tdt_15.png?v=1");
	gbox.addTiles({id :'ty_tdt_15',image :'ty_tdt_15',tilew:1,tileh:23,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_16","images/Universal/ty_tdt_16.png?v=1");
	gbox.addTiles({id :'ty_tdt_16',image :'ty_tdt_16',tilew:12,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_17","images/Universal/ty_tdt_17.png?v=1");
	gbox.addTiles({id :'ty_tdt_17',image :'ty_tdt_17',tilew:12,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_18","images/Universal/ty_tdt_18.png?v=1");
	gbox.addTiles({id :'ty_tdt_18',image :'ty_tdt_18',tilew:12,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("ty_tdt_19","images/Universal/ty_tdt_19.png?v=1");
	gbox.addTiles({id :'ty_tdt_19',image :'ty_tdt_19',tilew:12,tileh:12,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wj_zjm_79","images/Universal/wj_zjm_79.png?v=1");
	gbox.addTiles({id :'wj_zjm_79',image :'wj_zjm_79',tilew:22,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wj_zjm_80","images/Universal/wj_zjm_80.png?v=1");
	gbox.addTiles({id :'wj_zjm_80',image :'wj_zjm_80',tilew:22,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("wj_zjm_81","images/Universal/wj_zjm_81.png?v=1");
	gbox.addTiles({id :'wj_zjm_81',image :'wj_zjm_81',tilew:22,tileh:57,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_01","images/Universal/zj_tx_f_01.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_01',image :'zj_tx_f_01',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_02","images/Universal/zj_tx_f_02.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_02',image :'zj_tx_f_02',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_03","images/Universal/zj_tx_f_03.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_03',image :'zj_tx_f_03',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_04","images/Universal/zj_tx_f_04.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_04',image :'zj_tx_f_04',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_05","images/Universal/zj_tx_f_05.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_05',image :'zj_tx_f_05',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_06","images/Universal/zj_tx_f_06.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_06',image :'zj_tx_f_06',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_07","images/Universal/zj_tx_f_07.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_07',image :'zj_tx_f_07',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_08","images/Universal/zj_tx_f_08.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_08',image :'zj_tx_f_08',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_09","images/Universal/zj_tx_f_09.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_09',image :'zj_tx_f_09',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_10","images/Universal/zj_tx_f_10.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_10',image :'zj_tx_f_10',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_11","images/Universal/zj_tx_f_11.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_11',image :'zj_tx_f_11',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_12","images/Universal/zj_tx_f_12.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_12',image :'zj_tx_f_12',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_13","images/Universal/zj_tx_f_13.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_13',image :'zj_tx_f_13',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_14","images/Universal/zj_tx_f_14.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_14',image :'zj_tx_f_14',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_15","images/Universal/zj_tx_f_15.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_15',image :'zj_tx_f_15',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_f_16","images/Universal/zj_tx_f_16.jpg?v=1");
	gbox.addTiles({id :'zj_tx_f_16',image :'zj_tx_f_16',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_01","images/Universal/zj_tx_m_01.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_01',image :'zj_tx_m_01',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_02","images/Universal/zj_tx_m_02.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_02',image :'zj_tx_m_02',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_03","images/Universal/zj_tx_m_03.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_03',image :'zj_tx_m_03',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_04","images/Universal/zj_tx_m_04.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_04',image :'zj_tx_m_04',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_05","images/Universal/zj_tx_m_05.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_05',image :'zj_tx_m_05',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_06","images/Universal/zj_tx_m_06.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_06',image :'zj_tx_m_06',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_07","images/Universal/zj_tx_m_07.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_07',image :'zj_tx_m_07',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_08","images/Universal/zj_tx_m_08.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_08',image :'zj_tx_m_08',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_09","images/Universal/zj_tx_m_09.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_09',image :'zj_tx_m_09',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_10","images/Universal/zj_tx_m_10.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_10',image :'zj_tx_m_10',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_11","images/Universal/zj_tx_m_11.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_11',image :'zj_tx_m_11',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_12","images/Universal/zj_tx_m_12.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_12',image :'zj_tx_m_12',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_13","images/Universal/zj_tx_m_13.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_13',image :'zj_tx_m_13',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_14","images/Universal/zj_tx_m_14.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_14',image :'zj_tx_m_14',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_15","images/Universal/zj_tx_m_15.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_15',image :'zj_tx_m_15',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zj_tx_m_16","images/Universal/zj_tx_m_16.jpg?v=1");
	gbox.addTiles({id :'zj_tx_m_16',image :'zj_tx_m_16',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_ltk_08","images/Universal/zjm_ltk_08.png?v=1");
	gbox.addTiles({id :'zjm_ltk_08',image :'zjm_ltk_08',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("zjm_ltk_07","images/Universal/zjm_ltk_07.png?v=1");
	gbox.addTiles({id :'zjm_ltk_07',image :'zjm_ltk_07',tilew:80,tileh:80,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("loading_01","images/Universal/loading_01.png?v=1");
	gbox.addTiles({id :'loading_01',image :'loading_01',tilew:599,tileh:27,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("loading_02","images/Universal/loading_02.png?v=1");
	gbox.addTiles({id :'loading_02',image :'loading_02',tilew:551,tileh:11,tilerow : 1,gapx : 0,gapy : 0});
	gbox.addImage("loading_03","images/Universal/loading_03.png?v=1");
	gbox.addTiles({id :'loading_03',image :'loading_03',tilew:774,tileh:443,tilerow : 1,gapx : 0,gapy : 0});
	
};